### ISSUE TITLE
Errors when sharing package files

### ISSUE THREAD

**Issue by ofek** [devpi/devpi#1014]
I'm trying to have a replica set up with shared `+files`. The files on each server is actually a cloud storage bucket that is FUSE mounted.

The first request via pip for any given wheel fails almost all of the time but subsequent tries for that package always succeeds:

```❯ pip install textual -I --no-cache-dir --index-url http://IP_ADDRESS/mirror/root/pypi/+simple/ --trusted-host IP_ADDRESS
Looking in indexes: http://IP_ADDRESS/mirror/root/pypi/+simple/
Collecting textual
  Downloading http://IP_ADDRESS/mirror/root/pypi/%2Bf/ebf/5f04a96721adb/textual-0.41.0-py3-none-any.whl (480 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.9/480.9 kB 7.6 MB/s eta 0:00:00
Collecting importlib-metadata>=4.11.3 (from textual)
  Downloading http://IP_ADDRESS/mirror/root/pypi/%2Bf/3eb/b78df84a805d7/importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Collecting markdown-it-py>=2.1.0 (from markdown-it-py[linkify,plugins]>=2.1.0->textual)
  Downloading http://IP_ADDRESS/mirror/root/pypi/%2Bf/355/216845c60bd96/markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 4.8 MB/s eta 0:00:00
Collecting rich>=13.3.3 (from textual)
  Downloading http://IP_ADDRESS/mirror/root/pypi/%2Bf/6da/14c108c4866ee/rich-13.7.0-py3-none-any.whl (240 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.6/240.6 kB 14.4 MB/s eta 0:00:00
Collecting typing-extensions<5.0.0,>=4.4.0 (from textual)
  ERROR: HTTP error 404 while getting http://IP_ADDRESS/mirror/root/pypi/%2Bf/8f9/2fc8806f9a6b6/typing_extensions-4.8.0-py3-none-any.whl (from http://IP_ADDRESS/mirror/root/pypi/+simple/typing-extensions/) (requires-python:>=3.8)
ERROR: Could not install requirement typing-extensions<5.0.0,>=4.4.0 from http://IP_ADDRESS/mirror/root/pypi/%2Bf/8f9/2fc8806f9a6b6/typing_extensions-4.8.0-py3-none-any.whl (from textual) because of HTTP error 404 Client Error: Not Found for url: http://IP_ADDRESS/mirror/root/pypi/%2Bf/8f9/2fc8806f9a6b6/typing_extensions-4.8.0-py3-none-any.whl for URL http://IP_ADDRESS/mirror/root/pypi/%2Bf/8f9/2fc8806f9a6b6/typing_extensions-4.8.0-py3-none-any.whl (from http://IP_ADDRESS/mirror/root/pypi/+simple/typing-extensions/) (requires-python:>=3.8)
```

If I were to run that again `typing-extensions` would download successfully but then whatever comes next would fail.

I have tried using various methods but basically this is the startup logic on each server:

```bash
CONFIG_FILE=/root/config/devpi-config.yml
MASTER_URL="http://pypi-mirror-0.devpi.$POD_NAMESPACE.svc.cluster.local:8080"

echo "==:> Initializing server"
if [[ "$POD_NAME" =~ -0$ ]]; then
    devpi-init --configfile $CONFIG_FILE --role master
else
    devpi-init --configfile $CONFIG_FILE --role replica --master-url $MASTER_URL
fi

# Bucket mounted to /root/packages
# Artifacts path is the server directory path /root/devpi/+files
ln -s /root/packages $ARTIFACTS_PATH

echo "==:> Starting server"
if [[ "$POD_NAME" =~ -0$ ]]; then
    devpi-server --configfile $CONFIG_FILE --role master &
else
    devpi-server --configfile $CONFIG_FILE --role replica --master-url $MASTER_URL --replica-file-search-path $ARTIFACTS_PATH --replica-max-retries 1000 &
fi
```

The following are some errors that might occur (I've seen a fourth but I don't have the output anymore):

```
2023-11-16 16:44:16,065 INFO  [req225] GET /mirror/root/pypi/+f/8f9/2fc8806f9a6b6/typing_extensions-4.8.0-py3-none-any.whl
2023-11-16 16:44:16,069 ERROR [req225] [Rtx7] while handling http://34.98.93.227/mirror/root/pypi/+f/8f9/2fc8806f9a6b6/typing_extensions-4.8.0-py3-none-any.whl:
no such file
```

```
2023-11-16 18:03:53,045 WARNI [NOTI] Waiting for file root/pypi/+f/58c/d2187c01e70e6/requests-2.31.0-py3-none-any.whl in event serial 3
2023-11-16 18:03:53,442 INFO  [FREP] retrieving file from master for serial 3: root/pypi/+f/58c/d2187c01e70e6/requests-2.31.0-py3-none-any.whl
2023-11-16 18:03:53,554 ERROR [FREP] error downloading 'root/pypi/+f/58c/d2187c01e70e6/requests-2.31.0-py3-none-any.whl' from master, will be retried later: Internal Server Error
2023-11-16 18:03:53,559 WARNI [FREP] Error during file replication for root/pypi/+f/58c/d2187c01e70e6/requests-2.31.0-py3-none-any.whl: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/devpi_server/replica.py", line 740, in process_next
    handler(index_type, serial, key, keyname, value, back_serial)
  File "/usr/local/lib/python3.11/site-packages/devpi_server/replica.py", line 1033, in handler
    self.importer(
  File "/usr/local/lib/python3.11/site-packages/devpi_server/replica.py", line 971, in importer
    raise FileReplicationError(r, relpath)
devpi_server.replica.FileReplicationError: FileReplicationError with http://pypi-mirror-0.devpi.dependency-service.svc.cluster.local:8080/root/pypi/+f/58c/d2187c01e70e6/requests-2.31.0-py3-none-any.whl, code=500, reason=Internal Server Error, relpath=root/pypi/+f/58c/d2187c01e70e6/requests-2.31.0-py3-none-any.whl, message=failed
```

```
2023-11-16 19:02:08,717 ERROR Exception while serving /root/pypi/+f/90b/77e79eaa3eba6/idna-3.4-py3-none-any.whl
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/usr/local/lib/python3.11/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/usr/local/lib/python3.11/site-packages/waitress/task.py", line 456, in execute
    for chunk in app_iter:
  File "/usr/local/lib/python3.11/site-packages/pyramid/response.py", line 89, in __next__
    val = self.file.read(self.block_size)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory
```

Am I doing something wrong?

**Comment by fschulze** [comment]
The storage backend is written with the assumption of using a local file system. Network based file systems can introduce all sorts weirdness. For example downloading files relies on atomic renames. In other words, when a file is downloaded it is using a temporary name and when it is finished it is renamed to the actual name. If the FUSE backed filesystem introduces a delay, the symptoms you describe can occur. I would suggest a block based network storage which uses a journaling file system. Something like iSCSI or the new NVMe over TCP. The file system semantics work much better in such cases, but other considerations, like what happens on disconnects etc are then important to think about.

**Comment by fschulze** [comment]
I only just notices that you also wrote ``sharing``. Do you mean that several replicas share the same network file system? That can add further complications, as replicas are written under the assumption that there is only one writing process.

**Comment by ofek** [comment]
Every server has their own server directory but the `+files` directory used to store wheels and source distributions is a symbolic link to a mounted bucket that is shared by each. Is there a way to make this work? I really only want to share the artifact storage.

**Comment by fschulze** [comment]
There is no tested support for that. As I said, the most likely to work is a block based storage with a good journaling file system, but there is no guarantee. This might be possible in the future with several changes in the storage layer, but there is no one paying for its development at the moment and there are several things with higher priority to be done first.

**Comment by ofek** [comment]
Okay no worries, I'll just have a single server with high CPU & memory. While you're here, do you know how much storage is consumed after the initial indexing is finished? I understand the artifacts themselves are just based on what is actually used/mirrored but I mean metadata.

**Comment by fschulze** [comment]
It mainly depends on how much documentation you have uploaded. The index of an empty instance with root/pypi is a few megabytes. The index on m.devpi.net which includes quite a few documentation files has ~750MB. If you don't need the search, you can disable it with ``--indexer-backend=null``. The devpi metadata database also depends on content, but also the amount of changes. It can easily become a few GB. For m.devpi.net it is currently ~10GB. This will be improved quite a bit with the next upcoming major version, but there is no ETA for it yet.

**Comment by ofek** [comment]
There would be no documentation I think because were just using it as a mirror. I will disable the indexer backend, thanks! My plan to serve this now is 8 vCPU and 4 GB RAM; does that sound sufficient to you for constant usage? We will also be caching artifacts with a CDN.

**Comment by fschulze** [comment]
It should when used mainly as mirror, but keep monitoring it.
