### ISSUE TITLE
Add `upload-time` support to links parsed from a JSON API

### ISSUE THREAD

**Issue by fschulze** [devpi/devpi#1061]
See https://github.com/devpi/devpi/pull/1023

**Comment by pelson** [comment]
Sorry for cross-posting, but realised that I shouldn't have put the comment in the closed PR since this issue exists.


I was just contributing to [pypi-timemachine](https://github.com/astrofrog/pypi-timemachine), which is essentially doing the same thing as uv's exclude-newer, and noted this PR - having something like this would be super useful for that use case.

In https://github.com/devpi/devpi-constrained/issues/12 I proposed seeing if there is an option, and interest, to re-use parts of [simple-repository](https://github.com/astrofrog/pypi-timemachine) for handling some of the data model and logic. Since fschulze suggests that there is a significant internal re-write, perhaps it is a good option to re-use such a library. I don't think simple-repository is perfect at this point, but it is a pretty good start, and I think integrating it into something like devpi would certainly lead to some improvement on the simple-repository side (which I would be most happy to do!).

**Comment by radoering** [comment]
Since it has been two years now, I wonder if it makes sense to revisit #1023? Given the recent increase in supply chain attacks, I am seriously considering whether we should patch our devpi instance with #1023. However, I am afraid patching it on our own may complicate future updates...

**Comment by fschulze** [comment]
The 7.x release is much closer. If I had more people supporting devpi development either through GitHub Sponsors or direct support contracts I could spend more time on it and add such features quicker. The backend changes required were quite substantial and took a lot of time to get right and be flexible enough to support all the current and upcoming changes to the simple API.

**Comment by fschulze** [comment]
I released 7.0.0.dev2 for testing at:
https://m.devpi.net/fschulze/dev/devpi-server/7.0.0.dev2
https://m.devpi.net/fschulze/dev/+f/c1d/df86886ff9659/devpi_server-7.0.0.dev2-py3-none-any.whl

Be aware that this is a development release. It is very close to a release candidate, but I might make one more database schema change soon. This requires an export/import cycle for the data and can **not** be used in place of a 6.x installation.

There is full support for ``upload-time`` on local and remote indexes.

**Comment by radoering** [comment]
When I install 7.0.0.dev2 via

```
pip install --index-url https://m.devpi.net/fschulze/dev/+simple/ devpi-server==7.0.0.dev2
```

and run `devpi-init` afterwards, I get the following error:

```
Traceback (most recent call last):
  File "/home/testvenv/bin/devpi-init", line 5, in <module>
    from devpi_server.init import init
  File "/home/testvenv/lib/python3.12/site-packages/devpi_server/init.py", line 1, in <module>
    from .main import CommandRunner
  File "/home/testvenv/lib/python3.12/site-packages/devpi_server/main.py", line 16, in <module>
    from .keyfs import KeyFS
  File "/home/testvenv/lib/python3.12/site-packages/devpi_server/keyfs.py", line 41, in <module>
    from .model.root import CachingRootModel
  File "/home/testvenv/lib/python3.12/site-packages/devpi_server/model/root.py", line 8, in <module>
    from .user import User
  File "/home/testvenv/lib/python3.12/site-packages/devpi_server/model/user.py", line 5, in <module>
    from .local import LocalIndex
  File "/home/testvenv/lib/python3.12/site-packages/devpi_server/model/local.py", line 21, in <module>
    from devpi_common.metadata import version_sort_string
ImportError: cannot import name 'version_sort_string' from 'devpi_common.metadata' (/home/testvenv/lib/python3.12/site-packages/devpi_common/metadata.py)
```

The devpi-common version that was installed is 4.1.1

Am I doing anything wrong?

**Comment by fschulze** [comment]
Nope, I did something wrong. Here is a new release:
https://m.devpi.net/fschulze/dev/devpi-server/7.0.0.dev3
https://m.devpi.net/fschulze/dev/+f/ebe/e7d722dc10eb4/devpi_server-7.0.0.dev3-py3-none-any.whl

**Comment by radoering** [comment]
Thanks for the update. I tried it with a PyPI mirror and it seems to work fine. 👍

**Comment by fschulze** [comment]
I have made a devpi-server 7.0.0b1 release:
https://m.devpi.net/fschulze/dev/devpi-server/7.0.0b1
https://m.devpi.net/fschulze/dev/+f/b14/9433cd1697d92/devpi_server-7.0.0b1-py3-none-any.whl

Be aware that this release requires an export/import cycle, only use it in a test environment for now or be prepared to possibly do another export/import cycle and make backups.

**Comment by fschulze** [comment]
I released 7.0.0b2:
https://m.devpi.net/fschulze/dev/devpi-server/7.0.0b2
https://m.devpi.net/fschulze/dev/+f/d47/67b4b958e950c/devpi_server-7.0.0b2-py3-none-any.whl

It has an unrelated fix for a relatively common simple links parsing problem in 7.0.0b1. This is a drop-in replacement for 7.0.0b1.

**Comment by hynek** [comment]
> Nope, I did something wrong. Here is a new release: https://m.devpi.net/fschulze/dev/devpi-server/7.0.0.dev3 https://m.devpi.net/fschulze/dev/+f/ebe/e7d722dc10eb4/devpi_server-7.0.0.dev3-py3-none-any.whl

Any chance you could upload a pre-release to PyPI.org? I (and I'm sure many others) have no way to deploy applications that pull in packages from private indexes.

Thanks for working on this timely and important feature!

**Comment by fschulze** [comment]
@hynek do you have any experience in doing so for a major release with breaking changes? So far I'm waiting for internal testing results from a heavy user, but that will take till end of June. I haven't written a release announcement either yet, which I think might be important even for a pre-release. On the other hand normal users will not get a pre-release via pip or uv by default. Also having a beta label sounds safe enough for now. I think I will await a possible reply from you and sleep over it one more day.

**Comment by hynek** [comment]
> [@hynek](https://github.com/hynek) do you have any experience in doing so for a major release with breaking changes? So far I'm waiting for internal testing results from a heavy user, 

Is it FC? ;)

> but that will take till end of June. I haven't written a release announcement either yet, which I think might be important even for a pre-release. On the other hand normal users will not get a pre-release via pip or uv by default. Also having a beta label sounds safe enough for now. I think I will await a possible reply from you and sleep over it one more day.

sorry for sleeping 4 days, but my FOSS life ATM is madness, too.

I do not have such experience, but I’ve seen many projects do that and I think it’s up to you if you want to accompany an RC with an announcement? I mean you can soft-launch it first, wait how it shakes out, and if everything runs smoothly market it stronger (or push another RC)?

Pretty sure there’s gonna be plenty of interest, given it will enable the biggest security mechanism in years.

**Comment by fschulze** [comment]
devpi-server 7.0.0b3 is now on PyPI

**Comment by hynek** [comment]
Happy to report that I've successfully done the export/import dance and applied cooldowns to my work dependencies! ✨

**Comment by hynek** [comment]
FYI, I've somehow managed to get a corrupt cache file. In my case it was `KeyError: "There is no item named 'flask_login-0.6.3.dist-info/METADATA' in the archive"` which made the server throw 500s. I could solve it by deleting the wheel inside `.devpi` on the server.

It might've been due to me trying to abort an `uv sync --upgrade` and maybe the wheel was truncated? In hindsight I should've kept the wheel.

---

As a sidenote for those reading along: tt shouldn't be surprising, but `uv lock --upgrade` is a lot slower now, because there's a lot more work behind the scenes. Example:

```
$ uv sync --upgrade
Resolved 90 packages in 1m 05s
```

Unless there were wheel builds involved, this used to be seconds.

**Comment by hynek** [comment]
Hmm, there seems to be something else going on. I've got the same projects fail in CI/CD due to 404s on Linux wheels (my local system is macOS). The only "fix" that I've found is opening the project in the devpi web UI. It looks like the transparent proxy part of devpi is not quite as functional as in 6.x.

I will have to roll back so it doesn't disrupt my coworkers; lmk if there's anything I can collect for you before doing so.


**edit** jftr here's our nginx config – was it necessary to change anything about it for devpi 7?

<details>

```
server {
    server_name pypi.vm.ag deferred;
    listen      10.5.2.2:443 ssl;

    http2 on;

    gzip             on;
    gzip_min_length  2000;
    gzip_proxied     any;
    gzip_types       text/html application/json;

    ssl_certificate      /etc/ssl/certs/*.vm.ag_all.crt;
    ssl_certificate_key  /etc/ssl/private/*.vm.ag.key;

    access_log /var/log/nginx/proxy/pypi/access.log;
    error_log /var/log/nginx/proxy/pypi/error.log;

    root /vrmd/pypi/.devpi/server;
    client_max_body_size 20M;

    # Chunked transfers break pip 8/9 interop.
    chunked_transfer_encoding off;

    # try serving static files directly
    location ~ /\+f/ {
        # workaround to pass non-GET/HEAD requests through to the named location below
        error_page 418 = @proxy_to_app;
        if ($request_method !~ (GET)|(HEAD)) {
            return 418;
        }

        expires max;
        try_files /+files$uri @proxy_to_app;
    }
    # try serving docs directly
    location ~ /\+doc/ {
        try_files $uri @proxy_to_app;
    }
    location / {
        # workaround to pass all requests to / through to the named location below
        error_page 418 = @proxy_to_app;
        return 418;
    }
    location @proxy_to_app {
        proxy_pass http://127.0.0.1:3141;
        proxy_set_header X-outside-url $scheme://$host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        expires -1;  # no-cache
    }
}
```

</details>

**Comment by fschulze** [comment]
@hynek names and versions of any public stuff failing would be very helpful.

Nginx config didn't change in 7.x.

For ``flask-login`` the issue comes from name normalization, the filename is ``Flask_Login-0.6.3.dist-info/METADATA`` in the wheel. I need to look into testing for some variants.

Regarding ``uv`` I noticed a slowdown myself. I thought it might have to do with the additional security checks ``uv`` is now doing. Also I cleaned out my local ``uv`` cache *and* updated my local ``devpi-server``, so I blamed it on that. For me ``uv`` now seems slightly slower than before, but not as bad as a few days ago when I did all that. I need to look into that further.

**Comment by fschulze** [comment]
@hynek also check what exactly the 404s are for. Due to the ``METADATA`` reading from wheels I had 404s on ``.metadata`` requests before caused by version parsing in b2.

**Comment by hynek** [comment]
> [@hynek](https://github.com/hynek) names and versions of any public stuff failing would be very helpful.

These packages failed until I opened them in the web UI (they failed in reverse order but I don't think that's relevant):

- https://pypi.vm.ag/root/pypi/+f/cba/69cb73723c3f3/frozenlist-1.8.0-cp314-cp314-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl)
- https://pypi.vm.ag/root/pypi/+f/66a/dcc2aff09b3f1/pyjwt-2.13.0-py3-none-any.whl
- https://pypi.vm.ag/root/pypi/+f/470/8045e2d7a6c6b/aiohappyeyeballs-2.6.2-py3-none-any.whl
- https://pypi.vm.ag/root/pypi/+f/053/243f8b92b9905/aiosignal-1.4.0-py3-none-any.whl
- https://pypi.vm.ag/root/pypi/+f/fde/2ab74a5a7df2b/prometheus_async-26.1.0-py3-none-any.whl
- https://pypi.vm.ag/root/pypi/+f/01d/9bbc4a2d76bf0/dnspython-2.8.0-py3-none-any.whl)
- https://pypi.vm.ag/root/pypi/+f/652/d097d114dc907/verlib-0.1.tar.gz)
- https://pypi.vm.ag/root/pypi/+f/39e/3809566ff8535/async_timeout-5.0.1-py3-none-any.whl
- https://pypi.vm.ag/root/pypi/+f/939/5002973c827b3/lxml-6.1.1-cp314-cp314-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl
- https://pypi.vm.ag/root/pypi/+f/634/e385930fb6d2d/aiohttp-3.14.1-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl

So a mixture of generic wheels, platform-specific wheels, and source distributions. It might be that it passed for me locally because the packages were cached by uv.

The devpi log just said:

```
2026-06-18T09:36:38.014555+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:36:37,998 ERROR [req504] [Rtx183] while handling https://pypi.vm.ag/root/pypi/+f/
fde/2ab74a5a7df2b/prometheus_async-26.1.0-py3-none-any.whl:
2026-06-18T09:36:38.014677+02:00 c-0a01 pypi[2567501]: no such file
```

what might be interesting is that in the beginning I got a few of

> 2026-06-18T09:29:11.154760+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:29:11,153 WARNI [req433] [Rtx180] serving stale projects for 'pypi', getting data timed out after 5 seconds

**and** the web ui was very slow when navigating to the projects. That resolved itself later.

**Comment by hynek** [comment]
> [@hynek](https://github.com/hynek) also check what exactly the 404s are for. Due to the `METADATA` reading from wheels I had 404s on `.metadata` requests before caused by version parsing in b2.

I hope I've answered this question by accident; lmk know if not.

Also feel free to move this to an issue somewhere. I just wanted ppl to know of potential problems but that can be achieved by a link, too.

**Comment by hynek** [comment]
Another weirdness: on the next deployment I got a 404 on packages that worked before and only this one:
 https://pypi.vm.ag/root/pypi/+f/c45/8b6d084f9b935/pyyaml-6.0.3-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl

I _do_ share uv caches across builds using `--mount=type=cache,target=/root/.cache`, but this is extra weird.

**Comment by fschulze** [comment]
I think I know what is going on. The simple page results are cached by ``uv``, so it already knows the file URL and doesn't fetch the simple page again for some time. Since the remote data in devpi-server was wiped by the fresh import it doesn't yet know about the files. This is a problem for any fresh import. I need to think about a solution that allows this to be fixed without causing performance problems for every 404.

Could you check the logs to see if that is plausible? If the files were tried to be fetched without previously fetching the simple page (which you manually did by opening the project TTW) then my theory is correct.

**Comment by hynek** [comment]
yeah I think it's plausible. this is how a deployment looks like on the server:

<details>

```
2026-06-18T09:38:29.947384+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,946 INFO  [req557] GET /root/pypi/+f/470/8045e2d7a6c6b/aiohappyeyeballs-2.6.2-py3-none-any.whl
2026-06-18T09:38:29.951053+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,947 INFO  [req558] GET /root/pypi/+f/634/e385930fb6d2d/aiohttp-3.14.1-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
2026-06-18T09:38:29.955419+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,947 INFO  [req559] GET /root/pypi/+f/cbc/77da8c523d5ab/cryptography-49.0.0-cp311-abi3-manylinux_2_34_x86_64.whl
2026-06-18T09:38:29.965931+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,947 INFO  [req560] GET /root/pypi/+f/01d/9bbc4a2d76bf0/dnspython-2.8.0-py3-none-any.whl
2026-06-18T09:38:29.969906+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,948 INFO  [req561] GET /root/pypi/+f/939/5002973c827b3/lxml-6.1.1-cp314-cp314-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl
2026-06-18T09:38:29.970764+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,949 INFO  [req562] GET /root/pypi/+f/fde/2ab74a5a7df2b/prometheus_async-26.1.0-py3-none-any.whl
2026-06-18T09:38:29.984208+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,949 INFO  [req563] GET /root/pypi/+f/66a/dcc2aff09b3f1/pyjwt-2.13.0-py3-none-any.whl
2026-06-18T09:38:29.990200+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,951 INFO  [req564] GET /root/pypi/+f/c45/8b6d084f9b935/pyyaml-6.0.3-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl
2026-06-18T09:38:29.996172+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,951 INFO  [req565] GET /root/pypi/+f/053/243f8b92b9905/aiosignal-1.4.0-py3-none-any.whl
2026-06-18T09:38:30.011793+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,951 INFO  [req566] GET /root/pypi/+f/3a9/b5ddd403f79eb/sentry_sdk-2.63.0-py3-none-any.whl
2026-06-18T09:38:30.020211+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,955 INFO  [req567] GET /root/pypi/+f/afb/8db5439b81cf9/cffi-2.0.0-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
2026-06-18T09:38:30.036540+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,955 INFO  [req568] GET /root/pypi/+f/cba/69cb73723c3f3/frozenlist-1.8.0-cp314-cp314-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl
2026-06-18T09:38:30.050717+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,966 INFO  [req569] GET /root/vrmd/+simple/setuptools/
2026-06-18T09:38:30.057387+02:00 c-0a01 pypi[2567501]: 2026-06-18 09:38:29,969 ERROR [req557] [Rtx187] while handling https://pypi.vm.ag/root/pypi/+f/470/8045e2d7a6c6b/aiohappyeyeballs-2.6.2-py3-none-any.whl:
2026-06-18T09:38:30.057572+02:00 c-0a01 pypi[2567501]: no such file
```

</details>

caching huh 😅


---

**edit** another tell: this problem only popped up for a project that I haven't added cooldowns to yet. Locking with cooldowns presumably triggers views of the overview pages?

**Comment by hynek** [comment]
OK one more: https://pypi.vm.ag/root/pypi/hypothesis has famously A LOT of releases and the initial access to that page gave me several 504s and uv thought the project doesn't exist.

**Comment by fschulze** [comment]
@hynek are you relying on the search in ``devpi-web``? If not, then disabling it with ``--indexer-backend=null`` might help a lot.

I tested ``hypothesis`` and it handled it in way less than a second on a fresh install with debug output enabled, which logs a lot of info.

**Comment by hynek** [comment]
Due to the 500-on-second-metadata check[^second], all my nightly rebuilds failed, so I had to roll back to 6.20.2 at last.

You seem to know how fix that, so I'll leave that aside, but the 404 due to stale caches could become a real support headache for you and I would recommend to talk to the uv folks and ask them to re-check the simple index on 404 for a wheel from a cached URL?

[^second]: As a reminder: deleting the wheel fixes it for **one** run.

**Comment by fschulze** [comment]
I released 7.0.0b4 with fixes for these (and 6.20.3, which shared some of the problems).
