### ISSUE TITLE
Cannot import a dumpdir containing constrained indices

### ISSUE THREAD

**Issue by amoutaux** [devpi/devpi#1064]
Hello, 

I created a dumpdir using `devpi-export`. My devpi server currently runs with constrained index. The `devpi-export` command fails with:
```
Traceback (most recent call last):
  File "/usr/local/bin/devpi-import", line 8, in <module>
    sys.exit(import_())
  File "/usr/local/lib/python3.10/site-packages/devpi_server/importexport.py", line 154, in import_
    do_import(config.args.directory, xom)
  File "/usr/local/lib/python3.10/site-packages/devpi_server/importexport.py", line 111, in do_import
    importer.import_all(path)
  File "/usr/local/lib/python3.10/site-packages/devpi_server/importexport.py", line 482, in import_all
    stage = user.create_stage(index, type=indexconfig['type'])
  File "/usr/local/lib/python3.10/site-packages/devpi_server/model.py", line 430, in create_stage
    return self.parent.create_stage(self, index, type=type, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/devpi_server/keyfs.py", line 503, in create_stage
    self.model_cache[key] = super().create_stage(
  File "/usr/local/lib/python3.10/site-packages/devpi_server/model.py", line 173, in create_stage
    stage._modify(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/devpi_server/model.py", line 1044, in _modify
    self.customizer.validate_config(oldconfig, newconfig)
  File "/usr/local/lib/python3.10/site-packages/devpi_constrained/main.py", line 62, in validate_config
    raise self.InvalidIndexconfig(errors)
devpi_server.model.InvalidIndexconfig: ['A constrained index requires at least one base']
```

Extract of the `dataindex.json` for a `test/dev` index failing to be created:
```
    "test/dev": {
      "indexconfig": {
        "acl_upload": [
          "test"
        ],
        "mirror_whitelist": [
          "xgboost"
        ],
        "volatile": true,
        "mirror_whitelist_inheritance": "union",
        "description": "test",
        "acl_toxresult_upload": [":ANONYMOUS:"],
        "title": "test",
        "bases": [
          "test/upload",
          "root/pypi-wheels"
        ],
        "constraints": [
          "virtualenv<v20.24.6",
          "pytest<=8.1.2",
          "twine!=5.1.0"
        ],
        "type": "constrained"
      },
      "projects": {},
      "files": []
    }
```

If I am not mistaken, the issue lies in the `user.create_stage` being called before bases are set on the newly created indices:
https://github.com/devpi/devpi/blob/be69c6f747729566c9ae2f55cd14a7c41d215385/server/devpi_server/importexport.py#L462-L482

Thanks for this great product ❤️

**Comment by amoutaux** [comment]
Thanks for your prompt feedback. I raised https://github.com/fschulze/devpi-constrained/pull/1 so we can iterate on the `devpi-constrained` repository :).

**Comment by amoutaux** [comment]
Hi @fschulze , I just realized I targeted the wrong directory for the PR.. Here is the correct one: https://github.com/devpi/devpi-constrained/pull/8
