### ISSUE TITLE
InvalidRequirement exception when removing a package with a plus sign (+) in its name

### ISSUE THREAD

**Issue by sbstnh** [devpi/devpi#1069]
## Version

devpi-client 7.2.0
devpi-server 6.14.0
devpi-web 4.3.0

python 3.12.3
on Ubuntu 24.04 server (6.8.0-48-generic)

## Description

`InvalidRequirement` exception when trying to remove a package with a `+` sign in its name. Pushing and installing this package via poetry (+peotry dynamic versioning plugin) works flawlessly though. From a user perspective I would expect no issue here since the plus sign is valid when using semver.

## Example and traceback

```python
user@host:~$ devpi remove pack_age-0.1.2.post1+710f71f
Traceback (most recent call last):
  File "/home/user/.local/share/pipx/venvs/devpi-client/lib/python3.12/site-packages/packaging/requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/devpi-client/lib/python3.12/site-packages/packaging/_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/devpi-client/lib/python3.12/site-packages/packaging/_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/devpi-client/lib/python3.12/site-packages/packaging/_parser.py", line 124, in _parse_requirement_details
    marker = _parse_requirement_marker(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/devpi-client/lib/python3.12/site-packages/packaging/_parser.py", line 145, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "/home/user/.local/share/pipx/venvs/devpi-client/lib/python3.12/site-packages/packaging/_tokenizer.py", line 167, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    pack_age-0.1.2.post1+710f71f
                        ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/bin/devpi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/.local/share/pipx/venvs/devpi-client/lib/python3.12/site-packages/devpi/main.py", line 47, in main
    return method(hub, hub.args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/devpi-client/lib/python3.12/site-packages/devpi/list_remove.py", line 154, in main_remove
    req = parse_requirement(args.spec_or_url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/devpi-client/lib/python3.12/site-packages/devpi_common/metadata.py", line 223, in parse_requirement
    req = Requirement(s)
          ^^^^^^^^^^^^^^
  File "/home/user/.local/share/pipx/venvs/devpi-client/lib/python3.12/site-packages/packaging/requirements.py", line 38, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
    pack_age-0.1.2.post1+710f71f
```

**Comment by fschulze** [comment]
You most likely need to use ``pack_age==0.1.2.post1+710f71f``. It tries to parse the whole thing as the package name, which is invalid. Since you only want to remove the one version, you need to write it like a version requirement. If you only want to remove one package release, like a wheel, you need the full URL. Also see https://devpi.net/docs/devpi/devpi/stable/+d/userman/devpi_commands.html#remove (the description should include that like it does for https://devpi.net/docs/devpi/devpi/stable/+doc/userman/devpi_commands.html#test etc).
