### ISSUE TITLE
`devpi test <package>` fails with `devpi-lockdown` enabled

### ISSUE THREAD

**Issue by vlcinsky** [devpi/devpi#444]
This issue runs on the same configuration as described in issue #334.

Trying to use `devpi test` fails.

First, make sure what is our index and that we are logged in as user `one`:

``` bash
$ devpi use
Warning: insecure http host, trusted-host will be set for pip
current devpi index: http://pypi.local/root/pypi (logged in as one)
~/.pydistutils.cfg     : http://pypi.local/one/dev/+simple/
~/.pip/pip.conf        : http://one:one@pypi.local/root/pypi/+simple/
~/.buildout/default.cfg: http://pypi.local/one/dev/+simple/
always-set-cfg: no
```

Call the `devpi test`:

``` bash
$ devpi test devpi-client
received http://pypi.local/root/pypi/+f/0cc/4d03fb414144c/devpi-client-3.0.0.tar.gz
unpacking /tmp/devpi-test17/downloads/devpi-client-3.0.0.tar.gz to /tmp/devpi-test17/targz
Traceback (most recent call last):
  File "/opt/devpi/lib/python3.5/site-packages/devpi_common/archive.py", line 31, in Archive
    return ZipArchive(f)
  File "/opt/devpi/lib/python3.5/site-packages/devpi_common/archive.py", line 97, in __init__
    self._archive = zipfile.ZipFile(file)
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/devpi/lib/python3.5/site-packages/devpi_common/archive.py", line 35, in Archive
    return TarArchive(f)
  File "/opt/devpi/lib/python3.5/site-packages/devpi_common/archive.py", line 68, in __init__
    self._archive = tarfile.open(mode="r", fileobj=file)
  File "/usr/lib/python3.5/tarfile.py", line 1562, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/devpi", line 11, in <module>
    sys.exit(main())
  File "/opt/devpi/lib/python3.5/site-packages/devpi/main.py", line 32, in main
    return method(hub, hub.args)
  File "/opt/devpi/lib/python3.5/site-packages/devpi/test.py", line 220, in main
    toxrunargs = prepare_toxrun_args(devindex, versioninfo, sdist_links, wheel_links)
  File "/opt/devpi/lib/python3.5/site-packages/devpi/test.py", line 190, in prepare_toxrun_args
    sdist_pkg = dev_index.download_and_unpack(versioninfo, sdist_link)
  File "/opt/devpi/lib/python3.5/site-packages/devpi/test.py", line 62, in download_and_unpack
    pkg.unpack()
  File "/opt/devpi/lib/python3.5/site-packages/devpi/test.py", line 157, in unpack
    with Archive(self.path_archive) as archive:
  File "/opt/devpi/lib/python3.5/site-packages/devpi_common/archive.py", line 37, in Archive
    raise UnsupportedArchive()
devpi_common.archive.UnsupportedArchive
```

Hint: the problem could have similar cause as in issue #443. Another option could be, that the nginx configuration modifies or looses required header for content-type and this makes the result unusable.

**Comment by fschulze** [comment]
I looked into this and to fix this properly while also fixing #563 we have to stop using the ``--index`` option of tox. Large parts of that option are deprecated since 2015 anyway and the way we use it just passes along the index to ``pip``. We can do the same by using the ``PIP_INDEX_URL`` environment variable. I still have to investigate whether it will be passed on to pip, or if the environment variable filtering in tox interferes with that. There could be a few ``tox.ini`` configuration which would fail afterwards, because they use ``indexserver`` and rely on the overwrite currently done by ``devpi test`` which passes ``-i ALL=...``.
See https://tox.readthedocs.io/en/latest/config.html?highlight=indexserver#conf-indexserver and https://tox.readthedocs.io/en/latest/config.html?highlight=--index#cmdoption-tox-i

Another problem is that this will interfere with the current basic auth support. I think I will just output a warning about this for now, but as basic auth never really worked properly I will also deprecate support for it and for client certificates which were marked experimental and failed to deliver. The replacement will be an improved devpi-lockdown, the upcoming devpi-tokens and devpi-server >= 6.0.0.
