### ISSUE TITLE
Removing invalid package from devpi failed: 500 Internal Server Error

### ISSUE THREAD

**Issue by hoefling** [devpi/devpi#445]
This is probably not a devpi issue per se, rather a consequence of an error that happened somewhere in the past. Still, I would like to know if and how I could fix that. Recently, I decided to clean up some development versions of my package ``mypkg``:

```
$ devpi remove --index me/dev mypkg
About to remove the following releases and distributions
version: 1.3.0.dev8
  - http://localhost:4050/me/dev/+f/75d/3a3bd762ddce2/mypkg-1.3.0.dev8.tar.gz
  - http://localhost:4050/me/dev/+f/d2f/bffd9674ad9c3/mypkg-1.3.0.dev8-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/d8f/0ca649e36a2d8/mypkg-1.3.0.dev8.doc.zip
version: 1.3.0.dev12
  - http://localhost:4050/me/dev/+f/ee1/81f1fda67314c/mypkg-1.3.0.dev12.tar.gz
  - http://localhost:4050/me/dev/+f/095/2b383529926ba/mypkg-1.3.0.dev12-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/6bb/092cc9a345184/mypkg-1.3.0.dev12.doc.zip
version: 1.3.0.dev9
  - http://localhost:4050/me/dev/+f/399/95b3bff781502/mypkg-1.3.0.dev9.tar.gz
  - http://localhost:4050/me/dev/+f/5b2/464ca001fcc14/mypkg-1.3.0.dev9-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/e12/b7f1760474f81/mypkg-1.3.0.dev9.doc.zip
version: 1.3.0.dev1
  - http://localhost:4050/me/dev/+f/438/cca01f9687316/mypkg-1.3.0.dev1.tar.gz
  - http://localhost:4050/me/dev/+f/060/7ad42479ab57c/mypkg-1.3.0.dev1-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/ac7/3bc2b32a550c4/mypkg-1.3.0.dev1.doc.zip
version: 1.3.0.dev4
  - http://localhost:4050/me/dev/+f/41e/bdea535e5ceed/mypkg-1.3.0.dev4.tar.gz
  - http://localhost:4050/me/dev/+f/971/d29d059bcd230/mypkg-1.3.0.dev4-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/1a9/a71fa156c1cfd/mypkg-1.3.0.dev4.doc.zip
version: 1.3.0.dev13
  - http://localhost:4050/me/dev/+f/695/db8b572f96cd0/mypkg-1.3.0.dev13.tar.gz
  - http://localhost:4050/me/dev/+f/cf1/cd9b2e1d1fc74/mypkg-1.3.0.dev13-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/c54/93ccee5595b3a/mypkg-1.3.0.dev13.doc.zip
version: 1.3.0.dev3
  - http://localhost:4050/me/dev/+f/a35/757cc82c64c2a/mypkg-1.3.0.dev3.tar.gz
  - http://localhost:4050/me/dev/+f/eba/b22ad2ffe99d8/mypkg-1.3.0.dev3-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/42e/7821bc870db74/mypkg-1.3.0.dev3.doc.zip
version: 1.3.0.dev16
  - http://localhost:4050/me/dev/+f/a38/8bee0f1cf1077/mypkg-1.3.0.dev16.tar.gz
  - http://localhost:4050/me/dev/+f/635/fc980fa2e7a62/mypkg-1.3.0.dev16-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/8cd/b1479c4338dac/mypkg-1.3.0.dev16.doc.zip
version: 1.3.0.dev14
  - http://localhost:4050/me/dev/+f/bd6/c19c17182d200/mypkg-1.3.0.dev14.tar.gz
  - http://localhost:4050/me/dev/+f/313/534118ffd9797/mypkg-1.3.0.dev14-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/cff/6ed9c4a698930/mypkg-1.3.0.dev14.doc.zip
version: 1.3.0.dev17
  - http://localhost:4050/me/dev/+f/932/ee09ebc5000a2/mypkg-1.3.0.dev17.tar.gz
  - http://localhost:4050/me/dev/+f/49d/35097a4309ff2/mypkg-1.3.0.dev17-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/d55/2bbd948a80303/mypkg-1.3.0.dev17.doc.zip
version: m.y.p.k.g.-.0.-...9.-...1.-...d.e.v.4.9
  - http://localhost:4050/me/dev/+f/4bd/374a155d28d49/mypkg-m.y.p.k.g.-.0.-...9.-...1.-...d.e.v.4.9.tar.gz
version: 1.3.0.dev10
  - http://localhost:4050/me/dev/+f/e21/d5f47e9385d32/mypkg-1.3.0.dev10.tar.gz
  - http://localhost:4050/me/dev/+f/c4b/da41b4362855a/mypkg-1.3.0.dev10-py3-none-any.whl
  - http://localhost:4050/me/dev/+f/8b5/2d15382262ffa/mypkg-1.3.0.dev10.doc.zip
<long output skipped>
Are you sure (yes/no)? yes
deleting release 1.3.0.dev8 of mypkg
deleting release 1.3.0.dev12 of mypkg
deleting release 1.3.0.dev9 of mypkg
deleting release 1.3.0.dev1 of mypkg
deleting release 1.3.0.dev4 of mypkg
deleting release 1.3.0.dev13 of mypkg
deleting release 1.3.0.dev3 of mypkg
deleting release 1.3.0.dev16 of mypkg
deleting release 1.3.0.dev14 of mypkg
deleting release 1.3.0.dev17 of mypkg
deleting release m.y.p.k.g.-.0.-...9.-...1.-...d.e.v.4.9 of mypkg
WARN: devpi-client-3.0.0 got an unversioned reply, assuming API-VERSION 2 (as implemented by devpi-server-2.0)
DELETE http://localhost:4050/me/dev/mypkg/m.y.p.k.g.-.0.-...9.-...1.-...d.e.v.4.9
500 Internal Server Error: Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```
Server logs:
```
2017-07-26 23:43:05,587 INFO  [req92698] DELETE /me/dev/mypkg/m.y.p.k.g.-.0.-...9.-...1.-...d.e.v.4.9
2017-07-26 23:43:05,590 INFO  [req92698] [Wtx4281] deleted 'releasefile' link 
me/dev/+f/4bd/374a155d28d49/mypkg-m.y.p.k.g.-.0.-...9.-...1.-...d.e.v.4.9.tar.gz
2017-07-26 23:43:05,590 INFO  [req92698] [Wtx4281] set_metadata mypkg-m.y.p.k.g.-.0.-...9.-...1.-...d.e.v.4.9
2017-07-26 23:43:05,593 ERROR Exception when serving /me/dev/mypkg/m.y.p.k.g.-.0.-...9.-...1.-...d.e.v.4.9
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/usr/lib/python3.5/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/lib/python3.5/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/lib/python3.5/site-packages/devpi_server/views.py", line 146, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.5/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/lib/python3.5/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/lib/python3.5/site-packages/pyramid/view.py", line 730, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/lib/python3.5/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/lib/python3.5/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/lib/python3.5/site-packages/devpi_server/views.py", line 169, in request_log_handler
    response = handler(request)
  File "/usr/lib/python3.5/site-packages/devpi_server/views.py", line 204, in request_tx_handler
    response = handler(request)
  File "/usr/lib64/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/lib/python3.5/site-packages/devpi_server/keyfs.py", line 269, in transaction
    self.commit_transaction_in_thread()
  File "/usr/lib/python3.5/site-packages/devpi_server/keyfs.py", line 257, in commit_transaction_in_thread
    self._threadlocal.tx.commit()
  File "/usr/lib/python3.5/site-packages/devpi_server/keyfs.py", line 480, in commit
    commit_serial = self.conn.last_changelog_serial + 1
  File "/usr/lib/python3.5/site-packages/devpi_server/keyfs_sqlite_fs.py", line 142, in __exit__
    assert os.path.exists(path)
AssertionError
```
As you can see, there is a spoiled upload of ``mypkg`` with version ``m.y.p.k.g.-.0.-...9.-...1.-...d.e.v.4.9`` that causes an exception on a deletion attempt. I suppose this is a side effect of an error I did in a bash script when setting up an automatic build job on Jenkins long time ago: wrong substitution with ``sed`` resulted in a faulty version string that was used for an upload to devpi. What should I do to get rid of this upload?

**Comment by fschulze** [comment]
Try to create the file using ``touch``. It should be at your servers data root in ``+files/me/dev/+f/4bd/374a155d28d49/mypkg-m.y.p.k.g.-.0.-...9.-...1.-...d.e.v.4.9.tar.gz
version: 1.3.0.dev10``.

I consider this a bug though, on delete it shouldn't matter if the file exists.

**Comment by hoefling** [comment]
That did it, thanks again @fschulze! At least I can confirm the workaround with empty file creation now.
