### ISSUE TITLE
sqlite incompatibility on redhat 6.8, python 3.6.4

### ISSUE THREAD

**Issue by lhupfeldt** [devpi/devpi#510]
We are running devpi 4.4 on redhat 6.8 with python 3.6.4.

I had to patch keyfs_sqlite.py to get it working.

The issue seems to be sqlite version incompatibility:
<pre>
% devpi-server --start --host=xxx --serverdir=/xxx/devpi --replica-max-retries 50 --role master
2018-01-30 14:36:04,378 INFO  NOCTX Loading node info from /xxx/devpi/.nodeinfo
2018-01-30 14:36:04,389 INFO  NOCTX wrote nodeinfo to: /xxx/devpi/.nodeinfo
Traceback (most recent call last):
  File "/home/devpi/python3.6/bin/devpi-server", line 11, in <module>
    sys.exit(main())
  File "/home/devpi/python3.6/lib/python3.6/site-packages/devpi_server/main.py", line 56, in main
    return _main(pluginmanager, argv=argv)
  File "/home/devpi/python3.6/lib/python3.6/site-packages/devpi_server/main.py", line 94, in _main
    if not xom.is_replica() and xom.keyfs.get_current_serial() == -1:
  File "/home/devpi/python3.6/lib/python3.6/site-packages/devpi_common/types.py", line 39, in get
    x = self._property_cache[f] = f(self)
  File "/home/devpi/python3.6/lib/python3.6/site-packages/devpi_server/main.py", line 259, in keyfs
    cache_size=self.config.args.keyfs_cache_size)
  File "/home/devpi/python3.6/lib/python3.6/site-packages/devpi_server/keyfs.py", line 134, in __init__
    self._storage.perform_crash_recovery()
  File "/home/devpi/python3.6/lib/python3.6/site-packages/devpi_server/keyfs_sqlite_fs.py", line 75, in perform_crash_recovery
    with self.get_connection() as conn:
  File "/home/devpi/python3.6/lib/python3.6/site-packages/devpi_server/keyfs_sqlite.py", line 204, in get_connection
    sqlconn = self._get_sqlconn(uri)
  File "/home/devpi/python3.6/lib/python3.6/site-packages/devpi_server/keyfs_sqlite.py", line 162, in _get_sqlconn
    conn = self._get_sqlconn_uri_kw(uri)
  File "/home/devpi/python3.6/lib/python3.6/site-packages/devpi_server/keyfs_sqlite.py", line 146, in _get_sqlconn_uri_kw
    uri, timeout=60, isolation_level=None, uri=True)
sqlite3.OperationalError: unable to open database file
</pre>

My patch was this:

```python
    def _get_sqlconn(self, uri):
        # we will try different connection methods and overwrite _get_sqlconn
        # with the first successful one
        try:
            # the uri keyword is only supported from Python 3.4 onwards and
            # possibly other Python implementations
            conn = self._get_sqlconn_uri_kw(uri)
            # remember for next time
            self._get_sqlconn = self._get_sqlconn_uri_kw
            return conn
->      except sqlite3.OperationalError:
->          threadlog.warn("Can't open sqlite3 db with uri. sqlite incompatibility?")
        except TypeError as e:
```

The system installed sqlite version (which is up to date for redhat 6.8) is:
<pre>
(python3.6) devpi@xxx:/home/devpi % sqlite3 --version
3.8.11.1 2015-07-29 20:00:57 cf538e2783e468bbc25e7cb2a9ee64d3e0e80b2f
</pre>

After patching I still get the warning "Can't open sqlite3 with options in URI ... read/write conflicts between threads, causing slowdown ..."

It also seem that caching is not working correctly as the only packages I see in my index are the ones uploaded by me. I get frequent timeout errors when pip installing packes which are not in my index, not sure if these two issues are related to the sqlite issue.

Which sqlite version is required for full functionality? I cannot update the system installed sqlite, but could possibly create an alternate installation in /usr/local. Should I instead change to postgresql?

**Comment by fschulze** [comment]
That fix looks correct, I will add that. Thanks!

Check ``bases`` of your index to see if it inherits ``root/pypi``. The sqlite warning is only performance related, not functionality. I'd love to have it worded better, several people took it too seriously already.
