### ISSUE TITLE
devpi doesn't support PEP 508 environment markers

### ISSUE THREAD

**Issue by fortran-favors-the-old** [devpi/devpi#511]
Hello, and thanks so much for creating and maintaining devpi!

I've noticed that devpi doesn't appear to support [PEP 508 environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers).  **Would you please consider adding support for environment markers?**  Without such support, installing a package from devpi's `root/pypi` mirror index behaves differently from installing directly from PyPI.  I provide a detailed example below.

Suppose I want to install the [`futures`](https://github.com/agronholm/pythonfutures) package using pip.  As of `futures` 3.2.0, Python 3 is officially unsupported, so they've made this explicit in their [`setup.py`](https://github.com/agronholm/pythonfutures/blob/3.2.0/setup.py#L33) by specifying `python_requires='>=2.6, <3'`.

If pip is configured to use PyPI as the package index and I run `pip install -vvv -- 'futures>=3.1.1,<=3.2.0'`, this is what I see:

```
Collecting futures<=3.2.0,>=3.1.1
  1 location(s) to search for versions of futures:
  * https://pypi.python.org/simple/futures/
  Getting page https://pypi.python.org/simple/futures/
  Looking up "https://pypi.python.org/simple/futures/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/futures/ HTTP/1.1" 200 2834
  Updating cache with response from "https://pypi.python.org/simple/futures/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/futures/
    Found link https://pypi.python.org/packages/08/80/a9e000de5b7372a514add2ef614a953be8bc3d13c8d6205455739d0fb189/futures-0.2.python3.tar.gz#md5=b6f1d454aa2ba3c870a3743c154b95d5 (from https://pypi.python.org/simple/futures/), version: 0.2.python3
    Skipping link https://pypi.python.org/packages/09/9a/5cb5882312ae289aadab9dec2bd6557b25c45b79f3de5b400aafe547f3a5/futures-0.1.win32.exe#md5=3d4dbe19986aa9c654a2294cf6280c97 (from https://pypi.python.org/simple/futures/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/10/0e/bde74dc8717243adba113ef415b4c4517c532ce18ca5c476f8f147b9f74e/futures-2.1.1.tar.gz#md5=158422d8727f148c439408a8b423f9bb (from https://pypi.python.org/simple/futures/), version: 2.1.1
    Skipping link https://pypi.python.org/packages/10/1c/182c9e959ca708ce611a7bf6b0ab6022d4a0e7edad79e5145c220431b028/futures-3.0.0-py2-none-any.whl#md5=d64edfffae0bbda1f28ceef944c1d7cc (from https://pypi.python.org/simple/futures/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/17/47/1382bf17e7faa123464057df0afc69cca9c7eb14e930734ce8b5bdbfad7e/futures-2.0.tar.gz#md5=bcc58e035661b9be325b6d278005c0f2 (from https://pypi.python.org/simple/futures/), version: 2.0
    Found link https://pypi.python.org/packages/18/ab/85f2f673ac828bc3d1c1ceb92c82382cdcbf890046c77cd74edaa63cb7d7/futures-1.0.tar.gz#md5=0171acd9e2486915ccbe3d0e2e92ec3f (from https://pypi.python.org/simple/futures/), version: 1.0
    Found link https://pypi.python.org/packages/1c/98/bc0938f1c7c46b14dae9b25fc7edd32a7c26ef78b16a8b90835971f2143b/futures-2.1.3.tar.gz#md5=3de68835c8035dff0495cbe7f5c75beb (from https://pypi.python.org/simple/futures/), version: 2.1.3
    The package https://pypi.python.org/packages/1f/9e/7b2ff7e965fc654592269f2906ade1c7d705f1bf25b7d469fa153f7d19eb/futures-3.2.0.tar.gz#md5=d1b299a06b96ccb59f70324716dc0016 (from https://pypi.python.org/simple/futures/) (requires-python:>=2.6, <3) is incompatible with the pythonversion in use. Acceptable python versions are:>=2.6, <3
    Found link https://pypi.python.org/packages/25/83/113da7c7832a4efa80ec7fd5d25b2ea431d9a847cd78f1fa98ddd99d591a/futures-3.1.0.tar.gz#md5=ab78b3ed854a38b82af19f3d617d29eb (from https://pypi.python.org/simple/futures/), version: 3.1.0
    Skipping link https://pypi.python.org/packages/26/7d/a7e1130b63514cd7192f0ba0b53bdda7f96df88641ee0c97bfed8477f324/futures-3.0.3-py2-none-any.whl#md5=347b9df805d31b3edea63731ea79cb54 (from https://pypi.python.org/simple/futures/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl#md5=cfd62ab6c9852b04bb6048480fefaa75 (from https://pypi.python.org/simple/futures/) (requires-python:>=2.6, <3); it is not compatible with this Python
    Found link https://pypi.python.org/packages/2e/65/81cb1de73f001863f90981f4f5a0cea8da08bf7a9ed2a1d812e8f53fe822/futures-0.1.tar.gz#md5=14c2e3af0f90479792555e20061a4532 (from https://pypi.python.org/simple/futures/), version: 0.1
    Found link https://pypi.python.org/packages/32/e3/1de389e9e4372d106b1644b56cc0b94226a3ad637f96f45a8c3b55fc0709/futures-2.1.5-py2.py3-none-any.whl#md5=e6763f4016c0a6e31a0edc15072cc56e (from https://pypi.python.org/simple/futures/), version: 2.1.5
    Found link https://pypi.python.org/packages/36/0d/ff8097028893cc2ba0ad6c1a23f8aa5486728f2077f00989733978a4e289/futures-2.1.2.tar.gz#md5=a6fa247e3c5fe3d60d8e12f1b873cc88 (from https://pypi.python.org/simple/futures/), version: 2.1.2
    Found link https://pypi.python.org/packages/38/25/85ec21efa813e4158dcea8bc676d1f81510af0ca3e2ba32ec47247d4857d/futures-2.1.6.tar.gz#md5=cfab9ac3cd55d6c7ddd0546a9f22f453 (from https://pypi.python.org/simple/futures/), version: 2.1.6
    Found link https://pypi.python.org/packages/4b/19/93f2dd20a2e7eb72348c90b697ef7a0bd20168f973fc269f8986b8e49391/futures-2.1.tar.gz#md5=b1b9879b20e1ca45451124428ebd8157 (from https://pypi.python.org/simple/futures/), version: 2.1
    Found link https://pypi.python.org/packages/4c/dc/f9473006d4c9c52d4a4e977173fbcbfb1a8ef3a57e32e885edf994fd4a45/futures-3.0.3.tar.gz#md5=32171f72af7e80c266310794adc4db46 (from https://pypi.python.org/simple/futures/), version: 3.0.3
    Found link https://pypi.python.org/packages/55/db/97c1ca37edab586a1ae03d6892b6633d8eaa23b23ac40c7e5bbc55423c78/futures-3.0.5.tar.gz#md5=ced2c365e518242512d7a398b515ff95 (from https://pypi.python.org/simple/futures/), version: 3.0.5
    Found link https://pypi.python.org/packages/58/da/820c674b07041df44a4bc6c062c0da3e68a5172bf0ad01312634ea39c4f4/futures-0.2.tar.gz#md5=1a913df7f2e50c2d445cbc959c70b01e (from https://pypi.python.org/simple/futures/), version: 0.2
    Found link https://pypi.python.org/packages/59/a0/cf4cd997e1750f0c2d91c6ea5abea218251c43c3581bcc2f118b00baf5cf/futures-2.1.6-py2.py3-none-any.whl#md5=9327a3b0bd315594d755180045947b03 (from https://pypi.python.org/simple/futures/), version: 2.1.6
    Skipping link https://pypi.python.org/packages/5c/27/2f22e96c596b7cd83a3c1adceec4609eebd57ba3f8a061f993b4f84e592c/futures-3.0.1-py2-none-any.whl#md5=5abb7b2cdf2cc9f727b513c9bbaf415e (from https://pypi.python.org/simple/futures/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/6d/e6/52fa0ac964982c773087d967feb628408b9c3d278d931761afd863c176ee/futures-2.1.5.tar.gz#md5=2fc924890ccd30a5fe676fa9bbcf0ab8 (from https://pypi.python.org/simple/futures/), version: 2.1.5
    Skipping link https://pypi.python.org/packages/87/77/e02574de90ec2944113447106e3be417af2d4b3dd21a9a050c04b007cd29/futures-3.0.2-py2-none-any.whl#md5=56b6b9c77a9488de90f4b81978753870 (from https://pypi.python.org/simple/futures/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/8d/73/b5fff618482bc06c9711e7cdc0d5d7eb1904d35898f48f2d7f9696b08bef/futures-3.0.4.tar.gz#md5=27f0941502b3852ac78f3384e94f544e (from https://pypi.python.org/simple/futures/), version: 3.0.4
    Skipping link https://pypi.python.org/packages/9b/3a/da5dd42fb24e577d7cbb13b6f3a1bd466b7f11ff67facd670583d6bb6931/futures-3.0.4-py2-none-any.whl#md5=0b6343283c10a6e3b9eb0453739ee84d (from https://pypi.python.org/simple/futures/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/9c/3f/1d818ea03fb2956a2bdfa8f8a3b1319590f0f151a5584a8a3ae45085066c/futures-3.0.5-py2-none-any.whl#md5=968375970768ad7b7838cb07a0d60b44 (from https://pypi.python.org/simple/futures/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/a6/1c/72a18c8c7502ee1b38a604a5c5243aa8c2a64f4bba4e6631b1b8972235dd/futures-3.1.1-py2-none-any.whl#md5=61a88f749eb3655042f95d198f783ef3 (from https://pypi.python.org/simple/futures/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/a7/6a/a4386efd6fe91c85f97837c33eab5d3ec7ac29137f89930f15ad52865413/futures-0.2.win32.exe#md5=dc65adcd66ba6ecf0a89d8d6ec891de6 (from https://pypi.python.org/simple/futures/); unsupported archive format: .exe
    Skipping link https://pypi.python.org/packages/b1/52/b6024136771fed73f22bb2aae612683ad3f0654af16bc2462d648917cff2/futures-0.2.python3.win32.exe#md5=242c2437e402a03034823abc91b79d3c (from https://pypi.python.org/simple/futures/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/b2/2c/6b6a57379e47031c6f52e625e0e2b8f6702a8d1f61b6e0daee391e82c187/futures-3.0.1.tar.gz#md5=c872d96e128fb79371409f68f8c17f74 (from https://pypi.python.org/simple/futures/), version: 3.0.1
    Found link https://pypi.python.org/packages/c0/12/927b89a24dcb336e5af18a8fbf581581c36e9620ae963a693a2522b2d340/futures-2.2.0.tar.gz#md5=310e446de8609ddb59d0886e35edb534 (from https://pypi.python.org/simple/futures/), version: 2.2.0
    Found link https://pypi.python.org/packages/cc/26/b61e3a4eb50653e8a7339d84eeaa46d1e93b92951978873c220ae64d0733/futures-3.1.1.tar.gz#md5=77f261ab86cc78efa2c5fe7be27c3ec8 (from https://pypi.python.org/simple/futures/), version: 3.1.1
    Skipping link https://pypi.python.org/packages/d5/ea/a77d7379219f717333c7726bcaafa7839f11f475a3d3691ec9ed5b4add0e/futures-3.1.0-py2-none-any.whl#md5=a2e7fbede87d71aee50caaa44b8966b8 (from https://pypi.python.org/simple/futures/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/d7/1d/68874943aa37cf1c483fc61def813188473596043158faa6511c04a038b4/futures-2.2.0-py2.py3-none-any.whl#md5=12159c04b91abe5d26769f3ed4e01cc8 (from https://pypi.python.org/simple/futures/), version: 2.2.0
    Found link https://pypi.python.org/packages/ea/c9/35287369718fc05059e7a9d0d73c53745fe981010b4185b3858e7d46eff1/futures-3.0.0.tar.gz#md5=ed8cd52e316ad1ec1ed3fd1f1f622961 (from https://pypi.python.org/simple/futures/), version: 3.0.0
    Found link https://pypi.python.org/packages/f8/e7/fc0fcbeb9193ba2d4de00b065e7fd5aecd0679e93ce95a07322b2b1434f4/futures-3.0.2.tar.gz#md5=42aaf1e4de48d6e871d77dc1f9d96d5a (from https://pypi.python.org/simple/futures/), version: 3.0.2
    Found link https://pypi.python.org/packages/fd/6f/3ce6a5e9e0754a02ca3f0f6027c73bcc337dbd18517920eea2db0b369ae9/futures-2.1.4.tar.gz#md5=c6116d2d8c3c1a7c386ce196a2c98a4d (from https://pypi.python.org/simple/futures/), version: 2.1.4
  Using version 3.1.1 (newest of versions: 3.1.1)
  Looking up "https://pypi.python.org/packages/cc/26/b61e3a4eb50653e8a7339d84eeaa46d1e93b92951978873c220ae64d0733/futures-3.1.1.tar.gz" in the cache
  No cache entry available
  "GET /packages/cc/26/b61e3a4eb50653e8a7339d84eeaa46d1e93b92951978873c220ae64d0733/futures-3.1.1.tar.gz HTTP/1.1" 200 26471
  Downloading futures-3.1.1.tar.gz
  Downloading from URL https://pypi.python.org/packages/cc/26/b61e3a4eb50653e8a7339d84eeaa46d1e93b92951978873c220ae64d0733/futures-3.1.1.tar.gz#md5=77f261ab86cc78efa2c5fe7be27c3ec8 (from https://pypi.python.org/simple/futures/)
…
```

Note the two lines (one for `futures-3.2.0.tar.gz` and one for `futures-3.2.0-py2-none-any.whl`) that end with:

```
(requires-python:>=2.6, <3) is incompatible with the pythonversion in use. Acceptable python versions are:>=2.6, <3
(requires-python:>=2.6, <3); it is not compatible with this Python
```

Using the environment marker metadata PyPI is exposing, pip skips version 3.2.0 and instead downloads 3.1.1, which is the latest `futures` version not blacklisting Python 3.  This is the behavior I expect.

However, if I try the same thing using devpi's default `root/pypi` mirror index, this happens:

```
Collecting futures<=3.2.0,>=3.1.1
  1 location(s) to search for versions of futures:
  * http://localhost:3141/root/pypi/+simple/futures/
  Getting page http://localhost:3141/root/pypi/+simple/futures/
  Starting new HTTP connection (1): localhost
  "GET /root/pypi/+simple/futures/ HTTP/1.1" 200 5393
  Analyzing links from page http://localhost:3141/root/pypi/+simple/futures/
    Found link http://localhost:3141/root/pypi/+f/d1b/299a06b96ccb5/futures-3.2.0.tar.gz#md5=d1b299a06b96ccb59f70324716dc0016 (from http://localhost:3141/root/pypi/+simple/futures/), version: 3.2.0
    Skipping link http://localhost:3141/root/pypi/+f/cfd/62ab6c9852b04/futures-3.2.0-py2-none-any.whl#md5=cfd62ab6c9852b04bb6048480fefaa75 (from http://localhost:3141/root/pypi/+simple/futures/); it is not compatible with this Python
    Found link http://localhost:3141/root/pypi/+f/77f/261ab86cc78ef/futures-3.1.1.tar.gz#md5=77f261ab86cc78efa2c5fe7be27c3ec8 (from http://localhost:3141/root/pypi/+simple/futures/), version: 3.1.1
    Skipping link http://localhost:3141/root/pypi/+f/61a/88f749eb36550/futures-3.1.1-py2-none-any.whl#md5=61a88f749eb3655042f95d198f783ef3 (from http://localhost:3141/root/pypi/+simple/futures/); it is not compatible with this Python
    Found link http://localhost:3141/root/pypi/+f/ab7/8b3ed854a38b8/futures-3.1.0.tar.gz#md5=ab78b3ed854a38b82af19f3d617d29eb (from http://localhost:3141/root/pypi/+simple/futures/), version: 3.1.0
    Skipping link http://localhost:3141/root/pypi/+f/a2e/7fbede87d71ae/futures-3.1.0-py2-none-any.whl#md5=a2e7fbede87d71aee50caaa44b8966b8 (from http://localhost:3141/root/pypi/+simple/futures/); it is not compatible with this Python
    Found link http://localhost:3141/root/pypi/+f/ced/2c365e5182425/futures-3.0.5.tar.gz#md5=ced2c365e518242512d7a398b515ff95 (from http://localhost:3141/root/pypi/+simple/futures/), version: 3.0.5
    Skipping link http://localhost:3141/root/pypi/+f/968/375970768ad7b/futures-3.0.5-py2-none-any.whl#md5=968375970768ad7b7838cb07a0d60b44 (from http://localhost:3141/root/pypi/+simple/futures/); it is not compatible with this Python
    Found link http://localhost:3141/root/pypi/+f/27f/0941502b3852a/futures-3.0.4.tar.gz#md5=27f0941502b3852ac78f3384e94f544e (from http://localhost:3141/root/pypi/+simple/futures/), version: 3.0.4
    Skipping link http://localhost:3141/root/pypi/+f/0b6/343283c10a6e3/futures-3.0.4-py2-none-any.whl#md5=0b6343283c10a6e3b9eb0453739ee84d (from http://localhost:3141/root/pypi/+simple/futures/); it is not compatible with this Python
    Found link http://localhost:3141/root/pypi/+f/321/71f72af7e80c2/futures-3.0.3.tar.gz#md5=32171f72af7e80c266310794adc4db46 (from http://localhost:3141/root/pypi/+simple/futures/), version: 3.0.3
    Skipping link http://localhost:3141/root/pypi/+f/347/b9df805d31b3e/futures-3.0.3-py2-none-any.whl#md5=347b9df805d31b3edea63731ea79cb54 (from http://localhost:3141/root/pypi/+simple/futures/); it is not compatible with this Python
    Found link http://localhost:3141/root/pypi/+f/42a/af1e4de48d6e8/futures-3.0.2.tar.gz#md5=42aaf1e4de48d6e871d77dc1f9d96d5a (from http://localhost:3141/root/pypi/+simple/futures/), version: 3.0.2
    Skipping link http://localhost:3141/root/pypi/+f/56b/6b9c77a9488de/futures-3.0.2-py2-none-any.whl#md5=56b6b9c77a9488de90f4b81978753870 (from http://localhost:3141/root/pypi/+simple/futures/); it is not compatible with this Python
    Found link http://localhost:3141/root/pypi/+f/c87/2d96e128fb793/futures-3.0.1.tar.gz#md5=c872d96e128fb79371409f68f8c17f74 (from http://localhost:3141/root/pypi/+simple/futures/), version: 3.0.1
    Skipping link http://localhost:3141/root/pypi/+f/5ab/b7b2cdf2cc9f7/futures-3.0.1-py2-none-any.whl#md5=5abb7b2cdf2cc9f727b513c9bbaf415e (from http://localhost:3141/root/pypi/+simple/futures/); it is not compatible with this Python
    Found link http://localhost:3141/root/pypi/+f/ed8/cd52e316ad1ec/futures-3.0.0.tar.gz#md5=ed8cd52e316ad1ec1ed3fd1f1f622961 (from http://localhost:3141/root/pypi/+simple/futures/), version: 3.0.0
    Skipping link http://localhost:3141/root/pypi/+f/d64/edfffae0bbda1/futures-3.0.0-py2-none-any.whl#md5=d64edfffae0bbda1f28ceef944c1d7cc (from http://localhost:3141/root/pypi/+simple/futures/); it is not compatible with this Python
    Found link http://localhost:3141/root/pypi/+f/310/e446de8609ddb/futures-2.2.0.tar.gz#md5=310e446de8609ddb59d0886e35edb534 (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.2.0
    Found link http://localhost:3141/root/pypi/+f/121/59c04b91abe5d/futures-2.2.0-py2.py3-none-any.whl#md5=12159c04b91abe5d26769f3ed4e01cc8 (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.2.0
    Found link http://localhost:3141/root/pypi/+f/cfa/b9ac3cd55d6c7/futures-2.1.6.tar.gz#md5=cfab9ac3cd55d6c7ddd0546a9f22f453 (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.1.6
    Found link http://localhost:3141/root/pypi/+f/932/7a3b0bd315594/futures-2.1.6-py2.py3-none-any.whl#md5=9327a3b0bd315594d755180045947b03 (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.1.6
    Found link http://localhost:3141/root/pypi/+f/2fc/924890ccd30a5/futures-2.1.5.tar.gz#md5=2fc924890ccd30a5fe676fa9bbcf0ab8 (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.1.5
    Found link http://localhost:3141/root/pypi/+f/e67/63f4016c0a6e3/futures-2.1.5-py2.py3-none-any.whl#md5=e6763f4016c0a6e31a0edc15072cc56e (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.1.5
    Found link http://localhost:3141/root/pypi/+f/c61/16d2d8c3c1a7c/futures-2.1.4.tar.gz#md5=c6116d2d8c3c1a7c386ce196a2c98a4d (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.1.4
    Found link http://localhost:3141/root/pypi/+f/3de/68835c8035dff/futures-2.1.3.tar.gz#md5=3de68835c8035dff0495cbe7f5c75beb (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.1.3
    Found link http://localhost:3141/root/pypi/+f/a6f/a247e3c5fe3d6/futures-2.1.2.tar.gz#md5=a6fa247e3c5fe3d60d8e12f1b873cc88 (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.1.2
    Found link http://localhost:3141/root/pypi/+f/158/422d8727f148c/futures-2.1.1.tar.gz#md5=158422d8727f148c439408a8b423f9bb (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.1.1
    Found link http://localhost:3141/root/pypi/+f/b1b/9879b20e1ca45/futures-2.1.tar.gz#md5=b1b9879b20e1ca45451124428ebd8157 (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.1
    Found link http://localhost:3141/root/pypi/+f/bcc/58e035661b9be/futures-2.0.tar.gz#md5=bcc58e035661b9be325b6d278005c0f2 (from http://localhost:3141/root/pypi/+simple/futures/), version: 2.0
    Found link http://localhost:3141/root/pypi/+f/017/1acd9e2486915/futures-1.0.tar.gz#md5=0171acd9e2486915ccbe3d0e2e92ec3f (from http://localhost:3141/root/pypi/+simple/futures/), version: 1.0
    Skipping link http://localhost:3141/root/pypi/+f/dc6/5adcd66ba6ecf/futures-0.2.win32.exe#md5=dc65adcd66ba6ecf0a89d8d6ec891de6 (from http://localhost:3141/root/pypi/+simple/futures/); unsupported archive format: .exe
    Found link http://localhost:3141/root/pypi/+f/1a9/13df7f2e50c2d/futures-0.2.tar.gz#md5=1a913df7f2e50c2d445cbc959c70b01e (from http://localhost:3141/root/pypi/+simple/futures/), version: 0.2
    Skipping link http://localhost:3141/root/pypi/+f/3d4/dbe19986aa9c6/futures-0.1.win32.exe#md5=3d4dbe19986aa9c654a2294cf6280c97 (from http://localhost:3141/root/pypi/+simple/futures/); unsupported archive format: .exe
    Found link http://localhost:3141/root/pypi/+f/14c/2e3af0f904797/futures-0.1.tar.gz#md5=14c2e3af0f90479792555e20061a4532 (from http://localhost:3141/root/pypi/+simple/futures/), version: 0.1
    Skipping link http://localhost:3141/root/pypi/+f/242/c2437e402a030/futures-0.2.python3.win32.exe#md5=242c2437e402a03034823abc91b79d3c (from http://localhost:3141/root/pypi/+simple/futures/); unsupported archive format: .exe
    Found link http://localhost:3141/root/pypi/+f/b6f/1d454aa2ba3c8/futures-0.2.python3.tar.gz#md5=b6f1d454aa2ba3c870a3743c154b95d5 (from http://localhost:3141/root/pypi/+simple/futures/), version: 0.2.python3
  Using version 3.2.0 (newest of versions: 3.1.1, 3.2.0)
  "GET /root/pypi/+f/d1b/299a06b96ccb5/futures-3.2.0.tar.gz HTTP/1.1" 200 27320
  Downloading http://localhost:3141/root/pypi/+f/d1b/299a06b96ccb5/futures-3.2.0.tar.gz
  Downloading from URL http://localhost:3141/root/pypi/+f/d1b/299a06b96ccb5/futures-3.2.0.tar.gz#md5=d1b299a06b96ccb59f70324716dc0016 (from http://localhost:3141/root/pypi/+simple/futures/)
  Running setup.py (path:/private/var/folders/7m/9m_hfls153zfl_2h0mtkbx300005s9/T/pip-build-8a__3ax2/futures/setup.py) egg_info for package futures
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/futures.egg-info
    writing pip-egg-info/futures.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/futures.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/futures.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/futures.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/futures.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /private/var/folders/7m/9m_hfls153zfl_2h0mtkbx300005s9/T/pip-build-8a__3ax2/futures/setup.py:8: UserWarning: This backport is meant only for Python 2.
    Python 3 users do not need it, as the concurrent.futures package is available in the standard library.
      warn('This backport is meant only for Python 2.\n'
    warning: no files found matching 'CHANGES'
    writing manifest file 'pip-egg-info/futures.egg-info/SOURCES.txt'
  Source in /private/var/folders/7m/9m_hfls153zfl_2h0mtkbx300005s9/T/pip-build-8a__3ax2/futures has version 3.2.0, which satisfies requirement futures<=3.2.0,>=3.1.1 from http://localhost:3141/root/pypi/+f/d1b/299a06b96ccb5/futures-3.2.0.tar.gz#md5=d1b299a06b96ccb59f70324716dc0016
  Removing source in /private/var/folders/7m/9m_hfls153zfl_2h0mtkbx300005s9/T/pip-build-8a__3ax2/futures
Cleaning up...
futures requires Python '>=2.6, <3' but the running Python is 3.6.4
Exception information:
Traceback (most recent call last):
  File "/Users/fortran-favors-the-old/foo/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/fortran-favors-the-old/foo/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/Users/fortran-favors-the-old/foo/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/fortran-favors-the-old/foo/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/fortran-favors-the-old/foo/lib/python3.6/site-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/Users/fortran-favors-the-old/foo/lib/python3.6/site-packages/pip/utils/packaging.py", line 57, in check_dist_requires_python
    '.'.join(map(str, sys.version_info[:3])),)
pip.exceptions.UnsupportedPythonVersion: futures requires Python '>=2.6, <3' but the running Python is 3.6.4
```

You can see here that environment markers aren't exposed, so pip thinks it's okay to install version 3.2.0 .  It's not, and pip eventually errors out.

(As an aside, this isn't a contrived example.  I ran into this same issue in tensorflow/tensorboard#916 with Nexus, and noticed that this is also an issue with devpi.)

Here's some information about my environment:

OS: macOS 10.11.6
Python: 3.6.4 (Anaconda distribution)
Package versions:
```
devpi-common==3.2.1
devpi-server==4.4.0
devpi-web==3.2.2
pip==9.0.1
setuptools==38.4.0
wheel==0.30.0
```

Please let me know if you have questions, or if I can provide any additional information that may be helpful.

**Comment by fschulze** [comment]
Also see #494

**Comment by fschulze** [comment]
This requires #517

**Comment by NotSqrt** [comment]
That would be really very useful !

I see in the `simple` pages from pypi.org that they display a `data-requires-python` attribute to the links. For instance, in the [django page](https://pypi.org/simple/django/):
`<a href="https://files.pythonhosted.org/packages/b6/cf/8cbe9bd4bb83ce2dd277564b43435edb7b151a099458e63706d10ec9e4fa/Django-2.1.tar.gz#sha256=7f246078d5a546f63c28fc03ce71f4d7a23677ce42109219c24c9ffb28416137" data-requires-python=">=3.5">Django-2.1.tar.gz</a>`

With `pip==18.0 setuptools==40.0.0` and python 2.7, `pip install -i https://pypi.org/simple/ django` fetches `Django-1.11.15-py2.py3-none-any.whl`, but with devpi 4.6, pip fetches `Django-2.1.tar.gz`.

I've updated my mirror as explained in `devpi-server-4.5.0: update for pypi.org`.

**Comment by jaraco** [comment]
I'm seeing the same issue with CherryPy 18 on Python 2:

```
$ python2.7 -m rwt -i https://m.devpi.net/root/pypi/ 'cherrypy'
Looking in indexes: https://m.devpi.net/root/pypi/
Collecting cherrypy
  Using cached https://m.devpi.net/root/pypi/+f/705/cf8a8450339e1/CherryPy-18.0.0-py2.py3-none-any.whl
CherryPy requires Python '>=3.5' but the running Python is 2.7.15
```

**Comment by jaraco** [comment]
This issue is a major impediment to projects wishing to drop support for Python 2, something that's kicking off this year and will only increase over the next 2 years. I'd consider raising this issue to top priority.

**Comment by sergeykolosov** [comment]
If anyone's interested, I've got a work-in-progress branch:
https://github.com/sergeykolosov/devpi/commits/ticket_511

It's quick-and-dirty solution that does the trick for packages mirrored from PyPI, while support for uploaded packages isn't there yet.

**Comment by jaraco** [comment]
> solution that does the trick for packages mirrored from PyPI

That addresses the urgency of the issue - as it's the mirrored packages over which devpi clients have little control. If it's not _too_ dirty, maybe it could be considered for an interim solution.

**Comment by fschulze** [comment]
@sergeykolosov we might use your changes in ``common/devpi_common/vendor/_pip.py`` for now, as that won't require a major version bump. We are pretty far along with the rest of the changes already in a backward compatible way.

**Comment by fschulze** [comment]
This is now on master.
@sergeykolosov we used most of your changes on the parsing side, as we already did the database changes in a backward compatible way in which it is possible to downgrade devpi-server if needed.

**Comment by sergeykolosov** [comment]
@fschulze awesome, thanks!

**Comment by fschulze** [comment]
Released with server 4.7.0.

**Comment by fortran-favors-the-old** [comment]
Thanks! Looks good on my end.

**Comment by jaraco** [comment]
This is working great. Thanks!
