### ISSUE TITLE
AssertionError: no transaction entry at 10318 when trying to install packages

### ISSUE THREAD

**Issue by wridgers** [devpi/devpi#522]
I'm getting errors from devpi when trying to install packages.

```
Traceback (most recent call last):
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/views.py", line 143, in __call__
    return self.app(environ, start_response)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/view.py", line 755, in invoke_exception_view
    reraise_(*exc_info)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/views.py", line 166, in request_log_handler
    response = handler(request)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/views.py", line 201, in request_tx_handler
    response = handler(request)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/views.py", line 406, in simple_list_project
    result = stage.get_simplelinks(project, sorted_links=not requested_by_pip)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/model.py", line 481, in get_simplelinks
    "get_simplelinks_perstage", project=project):
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/model.py", line 542, in op_sro_check_mirror_whitelist
    res = getattr(stage, opname)(**kw)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/extpypi.py", line 288, in get_simplelinks_perstage
    is_fresh, links, cache_serial = self._load_cache_links(project)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/extpypi.py", line 258, in _load_cache_links
    cache = self.key_projsimplelinks(project).get()
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/keyfs.py", line 339, in get
    return self.keyfs.tx.get(self, readonly=readonly)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/keyfs.py", line 425, in get
    val = self.get_value_at(typedkey, self.at_serial)
  File "/opt/devpi/venv/local/lib/python2.7/site-packages/devpi_server/keyfs.py", line 383, in get_value_at
    assert tup, "no transaction entry at %s" %(last_serial)
AssertionError: no transaction entry at 10318
```

https://github.com/devpi/devpi/blob/master/server/devpi_server/keyfs.py#L383

In this case I was trying to install the `websocket-client` package. The 'fix' was:

```
devpi=# begin;
BEGIN
devpi=# delete from kv where key like '%websocket%';
DELETE 215
devpi=# delete from files where path like '%websocket%';
DELETE 11
devpi=# commit;
COMMIT
```

**Comment by fschulze** [comment]
The 'fix' most likely left your db in an undefined state. Did you do something like that before? The error indicates issues with your db. Is your db on a local filesystem, or is it a network filesystem? The db uses sqlite, which requires properly working file locking, which most (all?) network filesystems don't guarantee.

**Comment by wridgers** [comment]
Hi @fschulze. Thanks for the reply.

> Did you do something like that before?

Yes. A couple of times.

> Is your db on a local filesystem, or is it a network filesystem?

Local.

> The db uses sqlite, which requires properly working file locking, which most (all?) network filesystems don't guarantee.

Using Postgres here.

**Comment by fschulze** [comment]
Are you using devpi-postgresql 0.2.0? Previous versions had a race condition which could lead to inconsistent db state and or transaction issues. If it still works, I'd recommend an ``--export`` with devpi-server, delete the db and create a new one with the latest versions via ``--import``

**Comment by wridgers** [comment]
Looks like we're using `devpi-postgresql-0.1.0`. I will get this upgraded and see if that fixes the problem.

Will update with more information. Thanks!

**Comment by fschulze** [comment]
Any update on this?

**Comment by szrumi** [comment]
Despite us upgrading the plugin to devpi-postgresql-0.2.0 it has happened again.

Maybe it makes a difference whether a particular package has been deployed to DevPI using the previous version of the plugin? I'm guessing upgrading the plugin to the fixed version doesn't necessarily fix inconsistencies introduced by the earlier version?

We've exported the database and then reimported it as you suggested above. The export-import operation went smoothly and now we can install the same package without an error.

However this was only a few days ago so it's probably too early to tell whether it's fixed as it occurs sporadically.

**Comment by fschulze** [comment]
Did you have any more issues since the export/import?

**Comment by fschulze** [comment]
No more follow up.
