### ISSUE TITLE
reducing devpi space usage safely?

### ISSUE THREAD

**Issue by kgk** [devpi/devpi#542]
I am running devpi server 4.2 and have noticed that our root cache has grown to over 75GB.

Is there a safe way to remove (some of) the files cached in 
server/+files/root/pypi/  ?

I then plan to rebuild current versions of our projects to fetch a minimum set of packages.

Thanks

**Comment by therealprof** [comment]
I'm wondering as well. By accident some files are gone but I'm wondering how to update the index since `remove` does not seem to work:
```
$ devpi remove "datamodel>=0.1.11"
*redirected: http://localhost:3141/packages/staging/datamodel
About to remove the following releases and distributions
version: 0.1.11
  - http://localhost:3141/packages/staging/+f/73b/939bac009c6d9/datamodel-0.1.11-py2.py3-none-any.whl
  - http://localhost:3141/packages/staging/+f/75d/e5edb45daa8bc/datamodel-0.1.11.tar.gz
Are you sure (yes/no)? yes
deleting release 0.1.11 of datamodel
WARN: devpi-client-4.0.2 got an unversioned reply, assuming API-VERSION 2 (as implemented by devpi-server-2.0)
DELETE http://localhost:3141/packages/staging/datamodel/0.1.11
500 Internal Server Error: Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```

**Comment by fschulze** [comment]
@therealprof can you check the server logs when you do that and paste the exception here with some lines of context?

**Comment by therealprof** [comment]
@fschulze Sure:
```
2018-07-05 12:45:20,466 INFO  [req11] DELETE /packages/staging/datamodel/0.1.11
2018-07-05 12:45:20,471 INFO  [req11] [Wtx180] deleted 'releasefile' link packages/staging/+f/73b/939bac009c6d9/datamodel-0.1.11-py2.py3-none-any.whl
2018-07-05 12:45:20,471 INFO  [req11] [Wtx180] deleted 'releasefile' link packages/staging/+f/75d/e5edb45daa8bc/datamodel-0.1.11.tar.gz
2018-07-05 12:45:20,472 INFO  [req11] [Wtx180] set_metadata datamodel-0.1.11
2018-07-05 12:45:20,479 ERROR Exception when serving /packages/staging/datamodel/0.1.11
Traceback (most recent call last):
  File "/env/lib/python3.6/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/env/lib/python3.6/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/env/lib/python3.6/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/env/lib/python3.6/site-packages/devpi_server/views.py", line 143, in __call__
    return self.app(environ, start_response)
  File "/env/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/env/lib/python3.6/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/env/lib/python3.6/site-packages/pyramid/view.py", line 755, in invoke_exception_view
    reraise_(*exc_info)
  File "/env/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/env/lib/python3.6/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/env/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/env/lib/python3.6/site-packages/devpi_server/views.py", line 166, in request_log_handler
    response = handler(request)
  File "/env/lib/python3.6/site-packages/devpi_server/views.py", line 201, in request_tx_handler
    response = handler(request)
  File "/usr/local/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/env/lib/python3.6/site-packages/devpi_server/keyfs.py", line 270, in transaction
    self.commit_transaction_in_thread()
  File "/env/lib/python3.6/site-packages/devpi_server/keyfs.py", line 258, in commit_transaction_in_thread
    self._threadlocal.tx.commit()
  File "/env/lib/python3.6/site-packages/devpi_server/keyfs.py", line 481, in commit
    commit_serial = self.conn.last_changelog_serial + 1
  File "/env/lib/python3.6/site-packages/devpi_server/keyfs_sqlite_fs.py", line 142, in __exit__
    assert os.path.exists(path)
AssertionError
```

**Comment by fschulze** [comment]
@therealprof if you have a backup of the files in question, you can but them back in place. I think deletion should work even if the files are gone, so the assertion should be removed in the code and be replaced with a warning in the logs.

@kgk I looked at the code and currently it explicitly prohibits deletion in mirrors, but I don't see a reason why that shouldn't be allowed.

**Comment by fschulze** [comment]
@therealprof I just saw a similar problem in #445, there it was enough to just ``touch`` the path in question, because it only checks whether the file exists, so no actual backup with the correct content is necessary.

**Comment by therealprof** [comment]
@fschulze Tried that but it didn't work. My problem is I do not have the original file anymore (nor do I care about it) so my very first attempt was to fake it.

**Comment by fschulze** [comment]
https://mail.python.org/mm3/archives/list/devpi-dev@python.org/thread/VLFAGR4PS3TVFCU6EM4B5RB3NCH2GSVT/

**Comment by fschulze** [comment]
With server 4.7..0 deleting from a mirror is supported.
Deleting a package with missing files also works now.
With client 4.1.0 single release files can be removed by URL.

**Comment by fortran-favors-the-old** [comment]
Thanks @fschulze ! When you say that “with server 4.7.0 deleting from a mirror is supported”, does that mean it’s safe to manually delete files from `server/+files/root/pypi`?

**Comment by fschulze** [comment]
@fortran-favors-the-old No, via the web/rest interface is the officially supported way. Though deleting directly from the filesystem should be fine as well, if the file is requested again it should be downloaded from the source and put in place again without any changes in the database.

**Comment by dennisverspuij** [comment]
Hello, I'd also appreciate an easy way to clear the cache for a mirror, e.g. root/pypi, just by `rm -rf +files/root/pypi/*`. When I do that now and start devpi-server (v4.7.1) it fails to come up and logs this endlessly (despite previous comment saying: _deleting directly from the filesystem should be fine as well_):
```018-11-16 16:11:39,225 INFO  NOCTX wrote nodeinfo to:/path/to/.nodeinfo
Traceback (most recent call last):
  File "/opt/devpi/server/.venv/bin/devpi-server", line 11, in <module>
    sys.exit(main())
  File "/opt/devpi/server/.venv/local/lib/python3.6/site-packages/devpi_server/main.py", line 56, in main
    return _main(pluginmanager, argv=argv)
  File "/opt/devpi/server/.venv/local/lib/python3.6/site-packages/devpi_server/main.py", line 94, in _main
    if not xom.is_replica() and xom.keyfs.get_current_serial() == -1:
  File "/opt/devpi/server/.venv/local/lib/python3.6/site-packages/devpi_common/types.py", line 38, in get
    x = self._property_cache[f] = f(self)
  File "/opt/devpi/server/.venv/local/lib/python3.6/site-packages/devpi_server/main.py", line 260, in keyfs
    cache_size=self.config.args.keyfs_cache_size)
  File "/opt/devpi/server/.venv/local/lib/python3.6/site-packages/devpi_server/keyfs.py", line 134, in __init__
    self._storage.perform_crash_recovery()
  File "/opt/devpi/server/.venv/local/lib/python3.6/site-packages/devpi_server/keyfs_sqlite_fs.py", line 97, in perform_crash_recovery
    check_pending_renames(str(self.basedir), rel_renames)
  File "/opt/devpi/server/.venv/local/lib/python3.6/site-packages/devpi_server/keyfs_sqlite_fs.py", line 219, in check_pending_renames
    assert os.path.exists(path[:-4])
AssertionError
```
Having to use devpi client to iterate all official PyPI packages and then calling the client to remove them from a local mirror sounds odd to me, as well as very inefficient. After all imho a mirror is just a cache, if you want to remove something from it it should be removed from the source.

**Comment by fschulze** [comment]
@dennisverspuij there were uncommited changes and you deleted the temporary files which causes the above traceback. So the "should" part didn't pan out for all cases. It's likely that you can add a ``print`` to that line and touch the ``-tmp`` files manually to recover from this. The checksum check should cause a redownload. **But I have never tested that.** I'm not sure ``check_pending_renames`` can easily be changed to ignore the check for mirrors. That's why we added the official way through the REST API. There are plans for batch processing, but that is quite a way off for now.

**Comment by dennisverspuij** [comment]
@fschulze Hi Florian. I do not understand your reply, do you mean uncommitted changes to my root/pypi, and where would the tmp files reside, inside +files/root/pypi/? I restored all the files and restarted devpi server and it starts succesfully, but not logging anything about finalizing any transactions. Why would there be any?

**Comment by fschulze** [comment]
@dennisverspuij devpi places files in the destination directory with the ending ``-tmp``, then it commits metadata to sqlite, then it renames the files. As far as I can tell from the traceback you deleted just in the moment when the ``-tmp`` files where still there and the metadata was already in sqlite. That's why it's better to go through the API. If you still want to delete manually, use ``find`` and filter out files ending in ``-tmp``. Though again that is a "It **should** work fine".

**Comment by dennisverspuij** [comment]
@fschulze I just did `find +files/root/pypi -type f -name '*tmp'`, yields nothing, stopped devpi-server, emptied `find +files/root/pypi -type f -name '*tmp'`, start devpi-server, and I still get the errors I described.

**Comment by fschulze** [comment]
@dennisverspuij if the last change in the database includes a mirror, then ``perform_crash_recovery`` will call ``check_pending_renames`` to check and then you get the assertion. I can't think of a short term fix for that.

**Comment by dennisverspuij** [comment]
@fschulze Ok, I found the culprit, the statement `assert os.path.exists(path[:-4])` succeeds in the unmodified filesystem, because the already renamed file exists, but in that case I think the serial should incremented at that point to not keep redoing that last transaction every next restart.
