### ISSUE TITLE
devpi push to pypi fails with internal server error

### ISSUE THREAD

**Issue by hpk42** [devpi/devpi#545]
when i am on index hpk/dev and with devpi-client-4.0.2 and try to "devpi push muacrypt==0.8 pypi:pypi" it produces an internal server error.  the server logs the below. 

>2018-05-21 20:21:10,829 INFO  [req590457] [req609655] PUSH /hpk/dev
2018-05-21 20:21:10,830 DEBUG [req590457] [req609655] [Wtx284572] in-transaction 284572
2018-05-21 20:21:10,833 INFO  [req590457] [req609655] registering muacrypt-0.8.0 to https://upload.pypi.io/legacy/
2018-05-21 20:21:10,836 DEBUG Starting new HTTPS connection (1): upload.pypi.io
2018-05-21 20:21:10,862 DEBUG [req590457] [req609655] [Wtx284572] transaction rollback at 284572
2018-05-21 20:21:10,863 DEBUG [req590457] [req609655] [Wtx284572] closing transaction at 284572
2018-05-21 20:21:10,864 ERROR Exception when serving /hpk/dev
Traceback (most recent call last):
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/devpi_server/views.py", line 143, in __call__
    return self.app(environ, start_response)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/router.py", line 278, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/view.py", line 755, in invoke_exception_view
    reraise_(*exc_info)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/devpi_server/views.py", line 166, in request_log_handler
    response = handler(request)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/devpi_server/views.py", line 201, in request_tx_handler
    response = handler(request)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 124, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/devpi_server/views.py", line 632, in pushrelease
    r = session.post(posturl, data=metadata, auth=pypiauth)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/devpi/devpi4/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='upload.pypi.io', port=443): Max retries exceeded with url: /legacy/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f02a49b5e90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-05-21 20:21:16,178 DEBUG [req609653] [Rtx284572] FIN: waiting for tx-serial 284573
2018-05-21 20:21:16,180 DEBUG [req609653] [Rtx284572] closing transaction at 284572
2018-05-21 20:21:16,181 DEBUG [req609653] 202 30.016s serial=284572 length=0 type=text/html; charset=UTF-8

**Comment by hpk42** [comment]
twine also has this problem, filed an issue there https://github.com/pypa/twine/issues/371
looks like it's likely a pypi.org deployment problem or so.

**Comment by hpk42** [comment]
thanks, that fixed it ...

**Comment by fschulze** [comment]
I think devpi-client should show a proper error in this case.
