### ISSUE TITLE
Unable to set password when run in Windows

### ISSUE THREAD

**Issue by copperchin** [devpi/devpi#562]
Clean install.  Having just run:

`devpi-server --serverdir=server --init`

then running

`devpi-server --serverdir=server --passwd root`

 and getting:

```
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "f:\devpi\scripts\devpi-server.exe\__main__.py", line 9, in <module>
  File "f:\devpi\lib\site-packages\devpi_server\main.py", line 56, in main
    return _main(pluginmanager, argv=argv)
  File "f:\devpi\lib\site-packages\devpi_server\main.py", line 121, in _main
    return run_passwd(xom.model, config.args.passwd)
  File "f:\devpi\lib\site-packages\devpi_server\model.py", line 27, in run_passwd
    pwd = py.std.getpass.getpass("enter password for %s: " % user.name)
  File "c:\python27\Lib\getpass.py", line 95, in win_getpass
    msvcrt.putch(c)
TypeError: must be char, not unicode
```

Getting this on Windows 7 & 10,  with a clean install of python27 (AMD64)
with the following packages installed:
```
apipkg              1.5
argon2-cffi         18.1.0
asn1crypto          0.24.0
beautifulsoup4      4.6.0
bleach              2.1.3
certifi             2018.4.16
cffi                1.11.5
Chameleon           3.3
chardet             3.0.4
cmarkgfm            0.4.2
cryptography        2.2.2
defusedxml          0.5.0
devpi-common        3.2.3
devpi-server        4.5.0
devpi-web           3.3.0
docutils            0.14
enum34              1.1.6
execnet             1.5.0
future              0.16.0
html5lib            1.0.1
hupper              1.3
idna                2.7
ipaddress           1.0.22
itsdangerous        0.24
passlib             1.7.1
PasteDeploy         1.5.2
pip                 10.0.1
plaster             1.0
plaster-pastedeploy 0.5
pluggy              0.6.0
py                  1.5.4
pycparser           2.18
Pygments            2.2.0
pyOpenSSL           18.0.0
pyramid             1.9.2
pyramid-chameleon   0.3
readme-renderer     21.0
repoze.lru          0.7
requests            2.19.1
setuptools          39.1.0
six                 1.11.0
translationstring   1.3
urllib3             1.22
venusian            1.1.0
waitress            1.1.0
webencodings        0.5.1
WebOb               1.8.2
wheel               0.31.1
Whoosh              2.7.4
zope.deprecation    4.3.0
zope.interface      4.5.0
```

It looks like the error is coming from `py.std`, which as I understand is deprecated?
Is there a good reason to not replace
`py.std.getpass.getpass` with `getpass`?

**Comment by fschulze** [comment]
py.std is just a mapping into the python library where you don't have to import, but can just use attribute access. I'll look into removing it's use, but I doubt it's the source of the issue. My guess is that  it's coming from the message it tries to print ``"enter password for %s: " % user.name``. Unfortunately I don't have access to Python on a Windows machine to look into it. We only have AppVayor for testing.

**Comment by copperchin** [comment]
Ha!  Here's something interesting:

This works as expected:
```
import py
>>> py.std.getpass.getpass("enter password for %s: " % 'Monty')
enter password for Monty:
```
but uh-oh; %s doesn't convert to bytestring?
```
>>> py.std.getpass.getpass("enter password for %s: " % u'Monty')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "W:\Resrc\Utils\Python27\Lib\getpass.py", line 95, in win_getpass
    msvcrt.putch(c)
```
but then either of these _will_ work:
```
py.std.getpass.getpass("enter password for %s: " % str(u'Monty'))

py.std.getpass.getpass("enter password for {}: ".format(u'Monty'))
```
...but I have no idea how well that works on other systems or py3k

**Comment by fschulze** [comment]
Make a PR with one variant and check the test results, rewrite the commit with another variant if it fails.

**Comment by dalito** [comment]
The problem is that url is a unicode string and after string substitution the whole string is unicode, see debug output on Win 7, python 2.7.18:
```
(py27_dev) λ devpi login fb4
> c:\dev_src\_pyve\py27_dev\lib\site-packages\devpi\login.py(29)devpiclient_get_password()
-> return getpass.getpass("password for user %s at %s: " % (username, url))
(Pdb) url
u'http://pypi.xyz.de/'
(Pdb) username
'fb4'
(Pdb) "password for user %s at %s: " % (username, url)
u'password for user fb4 at http://pypi.xyz.de/: '
```

**Comment by fschulze** [comment]
I guess using ``return getpass.getpass(u"password for user %s at %s: " % (username, url))`` would work as well, note the added ``u`` before the message. Would be great if someone could test that, then I can add the fix.

**Comment by dalito** [comment]
I had the same idea initially and tried it: It does not work. If getpass gets a unicode string on Python 2 it raises this erorr.

`return getpass.getpass("password for user %s at %s: " % (username, str(url)))` works but I don't think it is a proper fix.

**Comment by fschulze** [comment]
I found this: https://bugs.python.org/issue1436203

So for Python 2 only username and url should be encoded as ``sys.stdout.encoding``.

**Comment by dalito** [comment]
Yes, encoding with `sys.stdout.encoding` fixes the problem. Do you want me to send a PR?

I tested with this code:
```
@hookimpl(trylast=True)
def devpiclient_get_password(url, username):
    if sys.version_info < (3,):
        # getpass.getpass() does not support Unicode prompts on Python 2
        username = username.encode(sys.stdout.encoding)
        url = url.encode(sys.stdout.encoding)
    return getpass.getpass("password for user %s at %s: " % (username, url))
```
