### ISSUE TITLE
devpi-server --serverdir in non-homedir seems broken

### ISSUE THREAD

**Issue by toejough** [devpi/devpi#591]
Possibly I'm missing something, but...

### Given
* python 3.6.5
* mac OSX 10.13.6
* devpi-server 4.7.1
* no plugins (at least that I installed, I can't speak for devpi)

### When
* `devpi-server --init --serverdir random-dir`
* `devpi-server --start --severdir random-dir`

### Then
```
2018-09-28 08:52:40,964 INFO  NOCTX Loading node info from /<userdir>/<projectdir>/random-dir/.nodeinfo
2018-09-28 08:52:40,965 INFO  NOCTX wrote nodeinfo to: /<userdir>/<projectdir>/random-dir/.nodeinfo
starting background devpi-server at http://localhost:3141
/<userdir>/<projectdir>/random-dir/.xproc/devpi-server$ /<userdir>/.pyenv/versions/must/bin/devpi-server --serverdir random-dir
process 'devpi-server' started pid=126
Traceback (most recent call last):
  File "/<userdir>/.pyenv/versions/must/bin/devpi-server", line 11, in <module>
    sys.exit(main())
  File "/<userdir>/.pyenv/versions/3.6.5/envs/must/lib/python3.6/site-packages/devpi_server/main.py", line 56, in main
    return _main(pluginmanager, argv=argv)
  File "/<userdir>/.pyenv/versions/3.6.5/envs/must/lib/python3.6/site-packages/devpi_server/main.py", line 105, in _main
    return bgserver.start(args, argv[1:])
  File "/<userdir>/.pyenv/versions/3.6.5/envs/must/lib/python3.6/site-packages/devpi_server/bgserver.py", line 78, in start
    self.xproc.ensure("devpi-server", prepare_devpiserver)
  File "/<userdir>/.pyenv/versions/3.6.5/envs/must/lib/python3.6/site-packages/devpi_server/vendor/xprocess.py", line 171, in ensure
    raise RuntimeError("Could not start process %s" % name)
RuntimeError: Could not start process devpi-server
```

The log file at `/<userdir>/<projectdir>/random-dir/.xproc/devpi-server/xprocess.log` contains one line: `fatal: The path '/<userdir>/<projectdir>/random-dir/.xproc/devpi-server/random-dir' contains no devpi-server data, use --init to initialize.`

Running the init command again prints `fatal: The path '/<userdir>/<projectdir>/random-dir' already contains devpi-server data.`

### Other
If I repeat the steps above, but with `~/random-dir` instead, everything works fine.

**Comment by fschulze** [comment]
When using ``--start`` the directory needs to be absolute, not relative. One of the many reasons I want to deprecate ``--start`` and eventually remove it.

**Comment by toejough** [comment]
wow, yep, that did it.

**Comment by dmugtasimov** [comment]
I am trying to use devpi with Docker and getting this:

```
sc_pypi | + [[ -f /.serverversion ]]
sc_pypi | + devpi-init
sc_pypi | INFO  NOCTX Loading node info from /var/lib/devpi/.nodeinfo
sc_pypi | INFO  NOCTX generated uuid: 3b62c539e4114cd18f02733689263db2
sc_pypi | INFO  NOCTX wrote nodeinfo to: /var/lib/devpi/.nodeinfo
sc_pypi | INFO  NOCTX DB: Creating schema
sc_pypi | INFO  [Wtx-1] setting password for user 'root'
sc_pypi | INFO  [Wtx-1] created user 'root' with email None
sc_pypi | INFO  [Wtx-1] created root user
sc_pypi | INFO  [Wtx-1] created root/pypi index
sc_pypi | INFO  [Wtx-1] fswriter0: committed: keys: '.config','root/.config'
sc_pypi | + devpi-server --start --host 0.0.0.0
sc_pypi | 2019-11-20 12:36:01,610 INFO  NOCTX Loading node info from /var/lib/devpi/.nodeinfo
sc_pypi | 2019-11-20 12:36:01,611 INFO  NOCTX wrote nodeinfo to: /var/lib/devpi/.nodeinfo
sc_pypi | starting background devpi-server at http://0.0.0.0:3141
sc_pypi | /var/lib/devpi/.xproc/devpi-server$ /usr/local/bin/devpi-server --host 0.0.0.0
sc_pypi | process 'devpi-server' started pid=76
sc_pypi | devpi-server process startup detected
sc_pypi | logfile is at /var/lib/devpi/.xproc/devpi-server/xprocess.log
sc_pypi | /usr/local/lib/python3.7/site-packages/devpi_server/bgserver.py:31: UserWarning: Use of --start, --stop, --status and --log is deprecated. You should use a process manager of your OS, for example: systemd for Linux, Windows Services, launchd for macOS or http://supervisord.org/
sc_pypi | Also see the devpi-gen-config option to create example configuration files for such services.
sc_pypi |   "Use of --start, --stop, --status and --log is deprecated. "
sc_pypi | fatal: The path '/var/lib/devpi' already contains devpi-server data.
```

It blames for absolute path as well.

Another question. I wish to have a simple way to use devpi with docker. How would I do it without bringing systemd or supervisord?
