### ISSUE TITLE
unable to run devpi test with --detox  option

### ISSUE THREAD

**Issue by henryborchers** [devpi/devpi#607]
When I try...

     devpi test --index https://devpi.library.illinois.edu/DS_Jenkins/dev_staging py3exiv2bind==0.1.3.dev0 -s whl  --detox

I get the following error.

    C:\Users\hborcher\AppData\Local\Temp\devpi-test5\targz\py3exiv2bind-0.1.3.dev0$ tox --installpkg C:\Users\hborcher\AppData\Local\Temp\devpi-test5\downloads\py3exiv2bind-0.1.3.dev0-cp36-cp36m-win_amd64.whl -i ALL=https://devpi.library.illinois.edu/DS_Jenkins/dev_staging/+simple/ --recreate --result-json C:\Users\hborcher\AppData\Local\Temp\devpi-test5\py3exiv2bind-0.1.3.dev0-cp36-cp36m-win_amd64.whl\toxreport.json -c C:\Users\hborcher\AppData\Local\Temp\devpi-test5\targz\py3exiv2bind-0.1.3.dev0\tox.ini

    Traceback (most recent call last):
      File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main "__main__", mod_spec)
      File "c:\program files\python36\lib\runpy.py", line 85, in _run_code 
        exec(code, run_globals)
      File "C:\Program Files\Python36\Scripts\devpi.exe\__main__.py", line 9, in <module>
      File "c:\program files\python36\lib\site-packages\devpi\main.py", line 36, in main 
        return method(hub, hub.args)
      File "c:\program files\python36\lib\site-packages\devpi\test.py", line 252, in main 
        ret = devindex.runtox(*toxargs, upload_tox_results=args.upload_tox_results)
      File "c:\program files\python36\lib\site-packages\devpi\test.py", line 99, in runtox
        toxrunner = self.get_tox_runner()
      File "c:\program files\python36\lib\site-packages\devpi\test.py", line 116, in get_tox_runner
        import detox.main
    ModuleNotFoundError: No module named 'detox.main'

**Comment by henryborchers** [comment]
So I’d have to uninstall devpi client and reinstall it at the same time I install detox?

**Comment by henryborchers** [comment]
I tried uninstalling devpi-client, tox, and detox and reinstalling them but still got the exact same error.

detox==0.18
devpi-client==4.1.0
devpi-common==3.3.1
tox==3.5.3

**Comment by fschulze** [comment]
The import location in detox has changed, see #608
