### ISSUE TITLE
devpi-server can't modify root/pypi index offline

### ISSUE THREAD

**Issue by lixianyang** [devpi/devpi#615]
## info
devpi-lockdown-1.0.1
devpi-server-4.8.0
devpi-theme-16-2.1.0
devpi-web-3.5.0
devpi-client-4.2.0
python:3.6.5
## what I do
devpi-server can't connect Internet
```shell
devpi index root/pypi volatile=True
```
## devpi client output
```
WARN: devpi-client-4.2.0 got an unversioned reply, assuming API-VERSION 2 (as implemented by devpi-server-2.0)
PATCH http://xx.xxx.xxx.cn/root/pypi
500 Internal Server Error: Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```
## devpi server log
```
2018-12-06 22:33:41,480 INFO  [req148] GET /root/pypi
2018-12-06 22:34:02,239 ERROR [req148] [Rtx1083] Error during httpget of https://pypi.org/simple/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f646786bf98>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f646786bf98>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/devpi_server/main.py", line 297, in httpget
    timeout=timeout or self.config.args.request_timeout)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f646786bf98>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
2018-12-06 22:34:02,243 WARNI [req148] [Rtx1083] upstream error (URL 'https://pypi.org/simple/' returned -1): using stale projects list
2018-12-06 22:34:02,263 INFO  [req149] PATCH /root/pypi
2018-12-06 22:34:02,273 ERROR Exception when serving /root/pypi
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 769, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/usr/local/lib/python3.6/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/local/lib/python3.6/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/views.py", line 146, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 768, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/views.py", line 170, in request_log_handler
    response = handler(request)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/views.py", line 206, in request_tx_handler
    response = handler(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.6/site-packages/pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/config/views.py", line 169, in __call__
    return view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/config/views.py", line 188, in attr_view
    return view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 325, in secured_view
    return view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.6/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/usr/local/lib/python3.6/site-packages/devpi_server/views.py", line 640, in index_modify
    ixconfig = stage.get()
AttributeError: 'PyPIStage' object has no attribute 'get'
```

**Comment by fschulze** [comment]
Can you access https://pypi.org/simple/ with curl or wget from the machine you have devpi-server installed?

**Comment by lixianyang** [comment]
No, the machine can't connect Internet

**Comment by lixianyang** [comment]
I use devpi-server in our private cloud. I just want to modify the index meta info, why it access the mirror_url ? Access the mirror_url to get something?

**Comment by fschulze** [comment]
If you only need private packages, then try the ``--offline`` option. You should also remove ``root/pypi`` from the ``bases`` setting of your index.

**Comment by lixianyang** [comment]
```
  --offline-mode        (experimental) prevents connections to any upstream
                        server (e.g. pypi) and only serves locally cached
                        files through the simple index used by pip. [False]
  --no-root-pypi        don't create root/pypi on server initialization.
                        [False]
```
this options may not helpful, I must use other devpi-server as mirror, devpi-server indexes as blow:
```
root/test
root/xxxx
root/pypi
root/mirror
```
devpi index root/xxxx:
```
  type=stage
  bases=root/mirror
  volatile=False
  acl_upload=root
  acl_toxresult_upload=:ANONYMOUS:
  mirror_whitelist=
  pypi_whitelist=
```
devpi index root/mirror:
```
  type=mirror
  bases=
  volatile=False
  acl_upload=
  mirror_url=http://pypi.xx.xxxxxxxx.cn/root/doubanio/+simple/
  pypi_whitelist=
```
http://pypi.xx.xxxxxxxx.cn/root/doubanio/+simple/ is another devpi-server which can connect Internet. Although I don't use root/pypi index, and the devpi-server works fine，but when I access devpi web page /root, the request response is slow(30+seconds), and in devpi-server log, It access https://pypi.org/simple/, and timeout.
I also can't remove root/pypi index:
```
devpi index --delete root/pypi
403 Forbidden: index root/pypi non-volatile, cannot delete
```
So, I must do:
```
devpi index root/pypi volatile=True
```
You know, it does't work as I mentioned above.

Thanks for your reply

**Comment by fschulze** [comment]
I managed to reproduce the error you get, will look into it.

**Comment by fschulze** [comment]
See #617

**Comment by fschulze** [comment]
@lixianyang did you try the fix? You can use the package from https://m.devpi.net/devpi-travis/fschulze_devpi_615-modify-mirror

**Comment by lixianyang** [comment]
Sorry for late!

It works, I close my wifi, change volatile=True and then delete the index, but devpi-server output some exception.

Command:
```
root@u:/workdir# devpi index pypi volatile=True
/root/pypi volatile=True
http://localhost:3141/root/pypi:
  type=mirror
  volatile=True
  mirror_url=https://pypi.org/simple/
  mirror_web_url_fmt=https://pypi.org/project/{name}/
  title=PyPI
```

devpi-server output:
```
2018-12-21 11:41:39,575 INFO  [req16] GET /root/pypi
2018-12-21 11:41:39,577 ERROR [req16] [Rtx2] Error during httpget of https://pypi.org/simple/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ef85cf1d0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ef85cf1d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/devpi_server/main.py", line 297, in httpget
    timeout=timeout or self.config.args.request_timeout)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ef85cf1d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-12-21 11:41:39,577 WARNI [req16] [Rtx2] upstream error (URL 'https://pypi.org/simple/' returned -1): using stale projects list
2018-12-21 11:41:39,580 INFO  [req17] PATCH /root/pypi
2018-12-21 11:41:39,582 INFO  [req17] [Wtx2] modified index root/pypi: {'type': 'mirror', 'volatile': True, 'mirror_url': 'https://pypi.org/simple/', 'title': 'PyPI', 'mirror_web_url_fmt': 'https://pypi.org/project/{name}/'}
2018-12-21 11:41:39,673 INFO  [req17] [Wtx2] fswriter3: committed: keys: 'root/.config'
2018-12-21 11:41:39,680 INFO  [req18] GET /root/pypi
2018-12-21 11:41:39,682 ERROR [req18] [Rtx3] Error during httpget of https://pypi.org/simple/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ef8525898>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ef8525898>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/devpi_server/main.py", line 297, in httpget
    timeout=timeout or self.config.args.request_timeout)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4ef8525898>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2018-12-21 11:41:39,682 WARNI [req18] [Rtx3] upstream error (URL 'https://pypi.org/simple/' returned -1): using stale projects list
```
