### ISSUE TITLE
devpi upload --only-docs check_manifest.Failure

### ISSUE THREAD

**Issue by dougscc** [devpi/devpi#645]
When attempting to upload docs to my devpi server with `devpi upload --only-docs` I get the following fail:

```bash
(venv) C:\Users\SomePerson\Projects\the-project>devpi upload --only-docs
using workdir C:\Users\SomePerson\AppData\Local\Temp\devpi9
Traceback (most recent call last):
  File "c:\users\someperson\projects\the-project\venv\lib\site-packages\check_manifest.py", line 149, in run
    stderr=subprocess.STDOUT, cwd=cwd)
  File "C:\Users\SomePerson\AppData\Local\Programs\Python\Python37\Lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\SomePerson\AppData\Local\Programs\Python\Python37\Lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SomePerson\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\SomePerson\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\SomePerson\Projects\the-project\venv\Scripts\devpi.exe\__main__.py", line 9, in <module>
  File "c:\users\someperson\projects\the-project\venv\lib\site-packages\devpi\main.py", line 36, in main
    return method(hub, hub.args)
  File "c:\users\someperson\projects\the-project\venv\lib\site-packages\devpi\upload.py", line 36, in main
    exported = checkout.export(uploadbase)
  File "c:\users\someperson\projects\the-project\venv\lib\site-packages\devpi\upload.py", line 304, in export
    files = check_manifest.get_vcs_files()
  File "c:\users\someperson\projects\the-project\venv\lib\site-packages\check_manifest.py", line 480, in get_vcs_files
    return normalize_names(vcs.get_versioned_files())
  File "c:\users\someperson\projects\the-project\venv\lib\site-packages\check_manifest.py", line 337, in get_versioned_files
    files = cls._git_ls_files()
  File "c:\users\someperson\projects\the-project\venv\lib\site-packages\check_manifest.py", line 346, in _git_ls_files
    output = run(['git', 'ls-files', '-z'], encoding=cls._encoding, cwd=cwd)
  File "c:\users\someperson\projects\the-project\venv\lib\site-packages\check_manifest.py", line 151, in run
    raise Failure("could not run %s: %s" % (command, e))
check_manifest.Failure: could not run ['git', 'ls-files', '-z']: [WinError 2] The system cannot find the file specified
```
The command is being run in a regular windows 10 `CMD` window in a virtual environment. I have successfully run this command in an almost identical layout. Is there a way to bypass the call to `git`?

**Comment by dougscc** [comment]
Never mind. Just saw `--no-vcs` switch. Thanks.
