### ISSUE TITLE
Setting up devpi in docker is broken

### ISSUE THREAD

**Issue by a-recknagel** [devpi/devpi#661]
Given a minimal setup defined by this dockerfile:

```
FROM python

RUN pip install devpi-web devpi-client
RUN devpi-server --start --init
```

I get the following error:

```
2019-05-10 10:26:06,876 INFO  NOCTX Loading node info from /root/.devpi/server/.nodeinfo
2019-05-10 10:26:06,876 INFO  NOCTX generated uuid: 8a586e40c4394f15b097681667e344b7
2019-05-10 10:26:06,877 INFO  NOCTX wrote nodeinfo to: /root/.devpi/server/.nodeinfo
2019-05-10 10:26:06,880 INFO  NOCTX DB: Creating schema
2019-05-10 10:26:06,969 INFO  [Wtx-1] setting password for user 'root'
2019-05-10 10:26:06,969 INFO  [Wtx-1] created user 'root' with email None
2019-05-10 10:26:06,969 INFO  [Wtx-1] created root user
2019-05-10 10:26:06,970 INFO  [Wtx-1] created root/pypi index
2019-05-10 10:26:06,975 INFO  [Wtx-1] fswriter0: committed: keys: '.config','root/.config'
starting background devpi-server at http://localhost:3141
/root/.devpi/server/.xproc/devpi-server$ /usr/local/bin/devpi-server
process 'devpi-server' started pid=290
Traceback (most recent call last):
  File "/usr/local/bin/devpi-server", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/devpi_server/main.py", line 67, in main
    return _main(pluginmanager, argv=argv)
  File "/usr/local/lib/python3.7/site-packages/devpi_server/main.py", line 122, in _main
    return bgserver.start(args, argv[1:])
  File "/usr/local/lib/python3.7/site-packages/devpi_server/bgserver.py", line 78, in start
    self.xproc.ensure("devpi-server", prepare_devpiserver)
  File "/usr/local/lib/python3.7/site-packages/devpi_server/vendor/xprocess.py", line 171, in ensure
    raise RuntimeError("Could not start process %s" % name)
RuntimeError: Could not start process devpi-server
```

I followed the [quickstart instructions](https://devpi.net/docs/devpi/devpi/latest/+doc/quickstart-releaseprocess.html), except for the `-U` flag for the pip install which is not necessary in a container where you're root.

**Comment by RonnyPfannschmidt** [comment]
you can pretty much google/github search for many working configurations

a docker environment is simply not the same as a classical deployment - you need different considerations for initial setup, data  storage and volume usage, as well as startup modes

also  note that you simply do not in any case start the service you want to run as a docker image, in a run command

you start the service via a container entry-point after the container was build

**Comment by fschulze** [comment]
In any server deployment you also shouldn't use the ``--start`` option (which is deprecated but not prominently enough yet). Instead you should use something like systemd to run devpi (we need to provide better docs for that). To try it, first start devpi manually without ``--start``. It should provide you with proper error output. Alternatively you can look at the log in ``/root/.devpi/server/.xproc``.

And generally it's a bad idea to run any kind of web service as root, regardless of whether it's docker or not.

**Comment by a-recknagel** [comment]
I was planning to run it with `docker run --net=host` to avoid network issues on the server, and would have liked to run it from a docker container because then I'd be able to debug it locally in an isolated environment. But if it's such a bad idea (from a user rights and storage perspective) to run it from docker I'll set it up differently.

**Comment by RonnyPfannschmidt** [comment]
@a-recknagel its not a bad idea to run it from docker, but you still need to know the platform details to do it good (just like you need to know the classical platform details to do it good on a normal deployment)

**Comment by a-recknagel** [comment]
fwiw, this is the log at `/root/.devpi/server/.xproc/devpi-server/xprocess.log` after running `devpi-server --start` after a successful `devpi-server --init`:

```
2019-05-13 07:39:40,097 INFO  NOCTX Loading node info from /root/.devpi/server/.nodeinfo
2019-05-13 07:39:40,098 INFO  NOCTX wrote nodeinfo to: /root/.devpi/server/.nodeinfo
2019-05-13 07:39:40,134 INFO  NOCTX Found plugin devpi-web-3.5.1 (/usr/local/lib/python3.7/site-packages).
2019-05-13 07:39:40,134 INFO  NOCTX Found plugin devpi-server-4.9.0 (/usr/local/lib/python3.7/site-packages).
2019-05-13 07:39:40,134 INFO  NOCTX Found plugin devpi-server-4.9.0 (/usr/local/lib/python3.7/site-packages).
2019-05-13 07:39:40,134 INFO  NOCTX Found plugin devpi-server-4.9.0 (/usr/local/lib/python3.7/site-packages).
2019-05-13 07:39:40,134 INFO  NOCTX Found plugin devpi-server-4.9.0 (/usr/local/lib/python3.7/site-packages).
2019-05-13 07:39:40,710 INFO  [NOTI] [Rtx0] triggering load of initial projectnames for root/pypi
2019-05-13 07:39:40,720 INFO  NOCTX devpi-server version: 4.9.0
2019-05-13 07:39:40,720 INFO  NOCTX serverdir: /root/.devpi/server
2019-05-13 07:39:40,721 INFO  NOCTX uuid: 92c3a3d284e44d648a8e50b26f913a23
2019-05-13 07:39:40,721 INFO  NOCTX serving at url: http://localhost:3141 (might be http://[localhost]:3141 for IPv6)
2019-05-13 07:39:40,721 INFO  NOCTX using 50 threads
2019-05-13 07:39:40,721 INFO  NOCTX bug tracker: https://github.com/devpi/devpi/issues
2019-05-13 07:39:40,721 INFO  NOCTX IRC: #devpi on irc.freenode.net
2019-05-13 07:39:40,721 INFO  NOCTX Hit Ctrl-C to quit.
Traceback (most recent call last):
  File "/usr/local/bin/devpi-server", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/devpi_server/main.py", line 67, in main
    return _main(pluginmanager, argv=argv)
  File "/usr/local/lib/python3.7/site-packages/devpi_server/main.py", line 143, in _main
    return xom.main()
  File "/usr/local/lib/python3.7/site-packages/devpi_server/main.py", line 260, in main
    return wsgi_run(xom, app)
  File "/usr/local/lib/python3.7/site-packages/devpi_server/main.py", line 172, in wsgi_run
    serve(app, host=host, port=port, threads=threads, max_request_body_size=max_body)
  File "/usr/local/lib/python3.7/site-packages/waitress/__init__.py", line 11, in serve
    server = _server(app, **kw)
  File "/usr/local/lib/python3.7/site-packages/waitress/server.py", line 84, in create_server
    sockinfo=sockinfo)
  File "/usr/local/lib/python3.7/site-packages/waitress/server.py", line 213, in __init__
    self.bind_server_socket()
  File "/usr/local/lib/python3.7/site-packages/waitress/server.py", line 344, in bind_server_socket
    self.bind(sockaddr)
  File "/usr/local/lib/python3.7/site-packages/waitress/wasyncore.py", line 369, in bind
    return self.socket.bind(addr)
OSError: [Errno 99] Cannot assign requested address
```
But the more I read into it, the more it seems that running devpi inside of docker will cause more issues  than it would solve.

**Comment by skyglobe** [comment]
For future reference this is a working Dockerfile for devpi that installs the server, the client and the web interface and runs as an unprivileged user:

```
FROM python:3.7

RUN pip install devpi-server devpi-client devpi-web && \
    mkdir -p /tmp/devpi_empty && \
    useradd -k /tmp/devpi_empty -m -d /data -s /bin/sh -N -g nogroup devpi && \
    rmdir /tmp/devpi_empty
USER devpi
WORKDIR /data
ADD --chown=devpi:nogroup config.yml /data/config.yml
RUN devpi-server --init --serverdir /data

VOLUME /data
EXPOSE 3141

CMD [ "devpi-server", "-c", "/data/config.yml"]
```

And this is the `config.yml` file I use:

```
---
devpi-server:
    host: 0.0.0.0
    port: 3141
    serverdir: /data
    restrict-modify: root

```

Build it with:

```
docker build -t devpi .
```

To run the container:

```
docker run -d devpi:latest -v /path/to/devpi/data:/data
```

**Comment by yunfan** [comment]
@skyglobe how to prevent the server auto accessing pypi.org? also is it possible to set another upstream server instead of pypi.org at the begining?

**Comment by fschulze** [comment]
@yunfan didn't you already ask about a different URL for upstream and said my answer at https://github.com/devpi/devpi/issues/433#issuecomment-582475198 solved it for you?

What do you mean with "prevent the server auto accessing pypi.org"?

**Comment by yunfan** [comment]
@fschulze yes, but in that case, it require to setup devpi server first and then use devpi-client to interact with it then set the new upstream url, i cant do this in dockerfile, so i ask here ,


the server launched by the dockerfile above will auto connect the upstream server pypi.org, and since i live in china, it has been blocked, so it will throw error periodly

**Comment by fschulze** [comment]
@yunfan I think what you want is the ``--no-root-pypi`` when running ``devpi-init``. That way ``root/pypi`` isn't created at all and you can create it yourself with the correct ``mirror_url``.

**Comment by tarrenj** [comment]
If anyone's looking for a _working_ example container, I couldn't find one either, so here's mine: https://github.com/tarrenj/devpi-container

**Comment by thomasf** [comment]
> If anyone's looking for a _working_ example container, I couldn't find one either, so here's mine: https://github.com/tarrenj/devpi-container

You only have to search for docker devpi on github to find dozens of them.
 
Here is mine, has lot's of environment variable based settings and is published to docker hub regulary:  https://hub.docker.com/r/thomasf/devpi

**Comment by JonasAlfredsson** [comment]
Well I suppose I am next in line in this. I couldn't get either of your images working with the latest devpi-server (the start + init command has changed again?) so I put together yet another [server and client image](https://github.com/JonasAlfredsson/docker-devpi) as well. 
Tested to be working with 6.4.0 as of today.
