### ISSUE TITLE
Memory Error for large packages

### ISSUE THREAD

**Issue by MGough** [devpi/devpi#663]
Every time pyTorch 1.1.0 is requested from Devpi it hangs for a while and then throws this MemoryError, it's a large package at 676.9 MB, once this error is thrown Devpi-server sometimes stops completely.

I'm running devpi-server-4.9.0.

```
2019-05-13 08:56:00,691 INFO  [req153] GET /root/pypi/+f/40c/644abef1767dc/torch-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
2019-05-13 08:56:00,801 INFO  [req153] [Wtx1128] reading remote: https://files.pythonhosted.org/packages/69/60/f685fb2cfb3088736bafbc9bdbb455327bdc8906b606da9c9a81bae1c81e/torch-1.1.0-cp36-cp36m-manylinux1_x86_64.whl, target root/pypi/+f/40c/644abef1767dc/torch-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
2019-05-13 08:56:32,358 ERROR Exception while serving /root/pypi/+f/40c/644abef1767dc/torch-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/waitress/channel.py", line 356, in service
    task.service()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/waitress/task.py", line 176, in service
    self.execute()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/waitress/task.py", line 469, in execute
    for chunk in app_iter:
  File "/home/ubuntu/.local/lib/python3.6/site-packages/devpi_server/views.py", line 1242, in iter_fetch_remote_file
    for part in entry.iter_cache_remote_file():
  File "/home/ubuntu/.local/lib/python3.6/site-packages/devpi_server/filestore.py", line 303, in iter_cache_remote_file
    content.write(data)
MemoryError
```

**Comment by MGough** [comment]
Despite checking if there was sufficient disk space on the server it seems when I try to download the package I also get the memory error. Looks like it's not a Devpi issue!

**Comment by MGough** [comment]
Confirmed that it was in fact a RAM issue, running on a small AWS instance with very little swap was not a good plan.
