### ISSUE TITLE
Question for pushing  to external pypi-style index

### ISSUE THREAD

**Issue by zhangsimingshannonai** [devpi/devpi#666]
Hi,I'm using devpi,and I met a error,here is the environment:
```
root@ip-172-55-22-212:~/.devpi/server# devpi use
current devpi index: http://localhost:3141/testuser/staging (logged in as testuser)
supported features: server-keyvalue-parsing
/root/.pip/pip.conf    : http://localhost:3141/root/pypi/+simple/
~/.pydistutils.cfg     : http://localhost:3141/root/pypi/+simple/
~/.buildout/default.cfg: no config file exists
always-set-cfg: no
root@ip-172-55-22-212:~/.devpi/server# devpi list -v
test-2.3.4.5
root@ip-172-55-22-212:~/.devpi/server# cat /root/.pypirc
[pypi]
repository: http://localhost:3141/testuser/staging
username: testuser
password: 666666
```
But something unexpected happen:
```
root@ip-172-55-22-212:~/.devpi/server# devpi push test-2.3.4.5 pypi:testrun
using pypirc /root/.pypirc
Traceback (most recent call last):
  File "/usr/local/bin/devpi", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/devpi/main.py", line 36, in main
    return method(hub, hub.args)
  File "/usr/local/lib/python2.7/dist-packages/devpi/push.py", line 59, in main
    pusher = parse_target(hub, args)
  File "/usr/local/lib/python2.7/dist-packages/devpi/push.py", line 42, in parse_target
    posturl, (user, password) = auth.get_url_auth(posturl)
  File "/usr/local/lib/python2.7/dist-packages/devpi/pypirc.py", line 39, in get_url_auth
    section = self.ini[secname]
  File "/usr/local/lib/python2.7/dist-packages/py/_vendored_packages/iniconfig.py", line 152, in __getitem__
    raise KeyError(name)
KeyError: 'testrun'
```
my Python version is 2.7.12 and I'm on Ubuntu 16.04 LTS,Did I miss something?
What should I do to solve this? Sincerely hope for your reply.

**Comment by fschulze** [comment]
The part after the colon of ``pypi:`` refers to a section in your ``~/.pypirc`` file which contains the username and password for pypi.org. See https://docs.python.org/2/distutils/packageindex.html#pypirc

The error message should be improved, please leave this ticket open as reminder for us.

**Comment by zhangsimingshannonai** [comment]
> The part after the colon of `pypi:` refers to a section in your `~/.pypirc` file which contains the username and password for pypi.org. See https://docs.python.org/2/distutils/packageindex.html#pypirc
> 
> The error message should be improved, please leave this ticket open as reminder for us.

Thanks for your reply,I figured it out with the method you said.
But there are still something wrong :
```
root@ip-172-55-22-212:/usr/local/test-2.3.4.5# cat /root/.pypirc 
[testrun]
repository: http://localhost:3141/testuser/staging
username: testuser
password: 666666
root@ip-172-55-22-212:/usr/local/test-2.3.4.5# devpi list -v
test-2.3.4.5
root@ip-172-55-22-212:/usr/local/test-2.3.4.5# devpi push test-2.3.4.5 pypi:testrun
using pypirc /root/.pypirc
Old style package specification is deprecated, use this form: your-pkg-name==your.version.specifier
PUSH http://localhost:3141/testuser/staging
502 Bad Gateway: {
  "type": "actionlog", 
  "result": [
    [
      500, 
      "register", 
      "test", 
      "2.3.4.5"
    ]
  ]
}
```
How can I fix it,I'm confused.
Now,I want get the answer,why should I push my package to external pypi-style index?
Or just tell me when should I do this? waiting for you answer,thanks a lot!

**Comment by fschulze** [comment]
For testing you should use ``repository:https://test.pypi.org/legacy/``.
Use ``repository:https://upload.pypi.org/legacy/`` to upload to actual pypi.org.
With the setting you have, you try to upload to your own repository.

Or do I misunderstand what you are trying to do?

**Comment by zhangsimingshannonai** [comment]
> For testing you should use `repository:https://test.pypi.org/legacy/`.
> Use `repository:https://upload.pypi.org/legacy/` to upload to actual pypi.org.
> With the setting you have, you try to upload to your own repository.
> 
> Or do I misunderstand what you are trying to do?

I just want to figure out ,why the document teach me to push my package to external pypi-style index? On what condition should I do this?
![image](https://user-images.githubusercontent.com/49146774/58254965-8a4b3480-7d9e-11e9-84c9-2e9e4c4ead72.png)

Waiting for your reply~

**Comment by fschulze** [comment]
Then try it with ``repository:https://test.pypi.org/legacy/``, it's meant for testing.

**Comment by zhangsimingshannonai** [comment]
> Then try it with `repository:https://test.pypi.org/legacy/`, it's meant for testing.

Thanks,But you still don't anwser my question....
```
I just want to figure out ,why the document teach me to push my package to external pypi-style index? On what condition should I do this?
```

**Comment by fschulze** [comment]
Ah, good point. The documentation assumes you know why you would want that.

It's meant for testing releases of public packages before doing a final release to pypi.org. The idea is that you can upload a package to devpi to test it thoroughly, maybe allow other people to install test releases easily (we often do that for devpi itself). Then when everything checks out the exact same package which was tested can be pushed to pypi.org as a public release.

So this ticket is now about two things, first a better error message, second expand the documentation.

Thanks for pointing this out!

**Comment by zhangsimingshannonai** [comment]
> ticket

Thank you for your patience，it help me a lot.

**Comment by zhangsimingshannonai** [comment]
> Ah, good point. The documentation assumes you know why you would want that.
> 
> It's meant for testing releases of public packages before doing a final release to pypi.org. The idea is that you can upload a package to devpi to test it thoroughly, maybe allow other people to install test releases easily (we often do that for devpi itself). Then when everything checks out the exact same package which was tested can be pushed to pypi.org as a public release.
> 
> So this ticket is now about two things, first a better error message, second expand the documentation.
> 
> Thanks for pointing this out!

Thank you for your patience，it help me a lot.
