### ISSUE TITLE
Question for "devpi upload"

### ISSUE THREAD

**Issue by zhangsimingshannonai** [devpi/devpi#667]
I'm using Ubuntu 16.04 and I install devpi-server and devpi-client by 
```
pip3 install -U devpi-server
pip3 install -U devpi-client
```
But when I do a upload,something error occured:
```
root@ip-172-31-31-120:/usr/local/test-2.3.4.5# ls
MANIFEST  PKG-INFO  setup.py  test.py
root@ip-172-31-31-120:/usr/local/test-2.3.4.5# devpi upload
using workdir /tmp/devpi4
Traceback (most recent call last):
  File "/usr/local/bin/devpi", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/devpi/main.py", line 36, in main
    return method(hub, hub.args)
  File "/usr/local/lib/python3.5/dist-packages/devpi/upload.py", line 36, in main
    exported = checkout.export(uploadbase)
  File "/usr/local/lib/python3.5/dist-packages/devpi/upload.py", line 302, in export
    return Exported(self.hub, self.setupdir, self.setupdir)
  File "/usr/local/lib/python3.5/dist-packages/devpi/upload.py", line 339, in __init__
    raise ValueError("could not find 'python' executable")
ValueError: could not find 'python' executable
```

Is this invovled with python's version ,It's success in python2 env.
How can I fix it? Waiting for you reply.

**Comment by fschulze** [comment]
This might be related to #395. The soon to be release devpi-client 5.0.0 should fix that. It should be available by next week.

**Comment by exhuma** [comment]
FWIW, I am on `devpi-client` v5.0.0 and also on Ubuntu 16.04 and don't see this problem.

So I assume it has been fixed and the issue can be closed?

**Comment by fschulze** [comment]
Seems to be fixed, please reopen with further details if this still happens.
