### ISSUE TITLE
devpi upload returns UnicodeDecodeError if 'æøå' in file name

### ISSUE THREAD

**Issue by jra-skov-dk** [devpi/devpi#682]
Hi.

I have some json config files with 'æøå' in the filename which are included using a MANIFEST.in file.

This give the following error:
```
C:\Data\Tools\Python\Packages\housesim>devpi upload
using workdir C:\Users\jra\AppData\Local\Temp\devpi51
not copying vcs repository metadata for .svn
pre-build: cleaning C:\Data\Tools\Python\Packages\housesim\dist
-->  C:\Users\jra\AppData\Local\Temp\devpi51\upload\housesim$ C:\python\python.EXE setup.py sdist --formats zip
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python\Scripts\devpi.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\devpi\main.py", line 36, in main
    return method(hub, hub.args)
  File "c:\python\lib\site-packages\devpi\upload.py", line 42, in main
    default_formats=setupcfg.get("formats")))
  File "c:\python\lib\site-packages\devpi\upload.py", line 406, in setup_build
    out = self.hub.popen_output(cmd, cwd=self.rootpath)
  File "c:\python\lib\site-packages\devpi\main.py", line 291, in popen_output
    return subprocess.check_output(args, cwd=str(cwd)).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 4321: invalid start byte
```

I have renamed my files but since I saw no real reason to why 'æøå' would not be allowed in file names I decided to create this issue.

If this is 'working as intended' you can just close it :)

**Comment by fschulze** [comment]
From what I can see there is some output on the console of the ``python.EXE setup.py sdist --formats zip`` command which breaks this. Could you run that command manually and provide the output of it? My guess is there is some message or warning related to your json files in the output.

The core issue here is getting the correct encoding for command output on various platforms and Python versions, which is hard to fix.

**Comment by jra-skov-dk** [comment]
Updated code output in issue with full output.

**Comment by fschulze** [comment]
My guess is that the output of commands on Windows is not encoded with utf-8. If someone has suggestions on how to get the correct encoding, please comment here.

**Comment by fschulze** [comment]
It seems like using ``sys.stdin.encoding`` would be the correct fix here.

**Comment by ovianao** [comment]
I am seeing something similar to this.

In my case, docutils puts out \x92 in the stdout/stderr pipes from this line (this line btw is 22 yrs old): https://github.com/docutils/docutils/blame/1e563c0cebbe89f333cb2fe43417e23027a45779/docutils/docutils/parsers/rst/states.py#L2420

I validated the above by piping stdout/stderr from the executed Sphinx command, to a file in Windows.

Ultimately, that special character causes a failure here:
https://github.com/devpi/devpi/blame/034aa0b21b4b1b00e1bdd6cba5927ef4dbd02347/client/devpi/main.py#L409

sys.getdefaultencoding() returns 'utf-8' here:
https://github.com/devpi/devpi/blame/034aa0b21b4b1b00e1bdd6cba5927ef4dbd02347/client/devpi/main.py#L406

Docutils' smartquotes module converts the single quotes, to an extended character here:
https://github.com/docutils/docutils/blob/1e563c0cebbe89f333cb2fe43417e23027a45779/docutils/docutils/utils/smartquotes.py#L676

I can pretty much reproduce the error this way.
It doesn't pin it on devpi, but it's clear that trying to decode a cp1251 character using utf-8 fails.

```

>>> from docutils.utils.smartquotes import educateQuotes
>>> text = educateQuotes("Unexpected possible title overline or transition.\nTreating it as ordinary text because it's so short.", "en")
>>> text.encode('cp1251')
b'Unexpected possible title overline or transition.\nTreating it as ordinary text because it\x92s so short.'
>>> text.encode('cp1251').decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 89: invalid start byte

```

I encountered this with devpi-client 7.0.2 and with docutils 0.20.1.
If I downgrade to devpi-client < 6.0.0, then it succeeds without error.

**Comment by jrast** [comment]
I just started to observe similar issues during a `devpi upload --with-docs` where the sphinx build fails due to encoding issues:

```
(venv) PS D:\Gitlab-Runner\builds\QyWNUETU\0\python\labware> devpi upload --with-docs --setupdir-only
using workdir C:\Temp\devpi-z5l6_hbt
not copying vcs repository metadata for .git
pre-build: cleaning dist
--> C:\Temp\devpi-z5l6_hbt$ D:\Gitlab-Runner\builds\QyWNUETU\0\python\labware\venv\Scripts\python.EXE -m build
built: dist\Labware-2024.7.0-py3-none-any.whl 77kb
built: dist\labware-2024.7.0.tar.gz 107kb
--> C:\Temp\devpi-z5l6_hbt$ D:\Gitlab-Runner\builds\QyWNUETU\0\python\labware\venv\Scripts\sphinx-build.EXE -E C:\Temp\devpi-z5l6_hbt\docs C:\Temp\devpi-z5l6_hbt\build
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Gitlab-Runner\builds\QyWNUETU\0\python\labware\venv\Scripts\devpi.exe\__main__.py", line 7, in <module>
  File "D:\Gitlab-Runner\builds\QyWNUETU\0\python\labware\venv\Lib\site-packages\devpi\main.py", line 46, in main
    return method(hub, hub.args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Gitlab-Runner\builds\QyWNUETU\0\python\labware\venv\Lib\site-packages\devpi\upload.py", line 53, in main
    p = exported.setup_build_docs()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Gitlab-Runner\builds\QyWNUETU\0\python\labware\venv\Lib\site-packages\devpi\upload.py", line 553, in setup_build_docs
    ret = self.hub.popen_output(cmd, cwd=self.rootpath)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Gitlab-Runner\builds\QyWNUETU\0\python\labware\venv\Lib\site-packages\devpi\main.py", line 411, in popen_output
    args, cwd=str(cwd), stderr=subprocess.STDOUT).decode(encoding)
                                                  ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 55: invalid continuation byte
```

By changing https://github.com/devpi/devpi/blob/main/client/devpi/main.py#L408

**from**

`encoding = sys.getdefaultencoding()`  --> This is `utf-8` in my case

**to**

`encoding = locale.getpreferredencoding()`  --> This is `cp1252` in my case

as proposed in the comment above, I got the build running. I run the build on a Windows 10 Machine from within PowerShell if this is of interest.

**Comment by jrast** [comment]
Seems like this issue can be closed?
