### ISSUE TITLE
Devpi-web  encountered an unexpected internal server error

### ISSUE THREAD

**Issue by helloocc** [devpi/devpi#687]
- When i search the web for requests，it shows error. Howerer, i can download the package by `pip download`. (The devpi is run with py2 now, and i have tried py3, it runs well. But i think it's better to fix the little bug)
- My env
```
$ pip2 freeze |grep devpi
devpi-client==5.0.0
devpi-common==3.4.0
devpi-server==5.0.0
devpi-web==3.5.2
```
- Search Error
![image](https://user-images.githubusercontent.com/4636271/61020180-5ae49b80-a3cf-11e9-8108-0c9ab6351c8b.png)

```
2019-07-11 11:25:09,246 ERROR Exception while serving /+search
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/waitress/channel.py", line 356, in service
    task.service()
  File "/usr/lib/python2.7/site-packages/waitress/task.py", line 176, in service
    self.execute()
  File "/usr/lib/python2.7/site-packages/waitress/task.py", line 447, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/lib/python2.7/site-packages/devpi_server/views.py", line 148, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/lib/python2.7/site-packages/devpi_server/views.py", line 172, in request_log_handler
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/devpi_server/views.py", line 208, in request_tx_handler
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/usr/lib/python2.7/site-packages/devpi_web/views.py", line 901, in __call__
    batch_links=self.batch_links,
  File "/usr/lib/python2.7/site-packages/pyramid/decorator.py", line 43, in __get__
    val = self.wrapped(inst)
  File "/usr/lib/python2.7/site-packages/devpi_web/views.py", line 740, in batch_links
    if not self.search_result or not self.search_result['items']:
  File "/usr/lib/python2.7/site-packages/pyramid/decorator.py", line 43, in __get__
    val = self.wrapped(inst)
  File "/usr/lib/python2.7/site-packages/devpi_web/views.py", line 735, in search_result
    self.params['query'], page=self.params['page'])
  File "/usr/lib/python2.7/site-packages/devpi_web/whoosh_index.py", line 474, in query_projects
    searcher = self.project_ix.searcher()
  File "/usr/lib/python2.7/site-packages/devpi_common/types.py", line 38, in get
    x = self._property_cache[f] = f(self)
  File "/usr/lib/python2.7/site-packages/devpi_web/whoosh_index.py", line 217, in project_ix
    return self.ix('project')
  File "/usr/lib/python2.7/site-packages/devpi_web/whoosh_index.py", line 198, in ix
    if not exists_in(self.index_path, indexname=name):
  File "/usr/lib/python2.7/site-packages/whoosh/index.py", line 136, in exists_in
    ix = open_dir(dirname, indexname=indexname)
  File "/usr/lib/python2.7/site-packages/whoosh/index.py", line 123, in open_dir
    return FileIndex(storage, schema=schema, indexname=indexname)
  File "/usr/lib/python2.7/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/usr/lib/python2.7/site-packages/whoosh/index.py", line 664, in read
    segments = stream.read_pickle()
  File "/usr/lib/python2.7/site-packages/whoosh/filedb/structfile.py", line 245, in read_pickle
    return load_pickle(self.file)
ValueError: unsupported pickle protocol: 4
```
- Details Error
![image](https://user-images.githubusercontent.com/4636271/61017411-ab56fb80-a3c5-11e9-9cce-f83f7f997b1e.png)
 ```
2019-07-11 10:18:40,113 ERROR Exception while serving /iaas/product/requests/2.22.0
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/waitress/channel.py", line 356, in service
    task.service()
  File "/usr/lib/python2.7/site-packages/waitress/task.py", line 176, in service
    self.execute()
  File "/usr/lib/python2.7/site-packages/waitress/task.py", line 447, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/lib/python2.7/site-packages/devpi_server/views.py", line 148, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/lib/python2.7/site-packages/devpi_server/views.py", line 172, in request_log_handler
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/devpi_server/views.py", line 208, in request_tx_handler
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 169, in   __call__
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 188, in attr_view
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "/usr/lib/python2.7/site-packages/devpi_web/views.py", line 574, in version_get
    content=get_description(stage, name, version),
  File "/usr/lib/python2.7/site-packages/devpi_web/description.py", line 11, in get_description
    stage, name, version).get_description()
  File "/usr/lib/python2.7/site-packages/devpi_web/description.py", line 41, in get_description
    self._render_description(desc))
  File "/usr/lib/python2.7/site-packages/devpi_web/description.py", line 82, in _render_description
    html = readme_renderer.markdown.render(desc, stream=warnings)
  File "/usr/lib/python2.7/site-packages/readme_renderer/markdown.py", line 63, in render
    highlighted = _highlight(rendered)
  File "/usr/lib/python2.7/site-packages/readme_renderer/markdown.py", line 108, in _highlight
    result = code_expr.sub(replacer, html)
  File "/usr/lib/python2.7/site-packages/readme_renderer/markdown.py", line 106, in replacer
    return '<pre>{}</pre>'.format(highlighted)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 26-28: ordinal not in range(128)
```

**Comment by fschulze** [comment]
The first error looks like you used Python 3 to run devpi-server and then switched to Python 2. That is not supported. Whoosh then can't read it's index anymore.

The second error looks like some encoding issue in your packages readme. Since this is ``requests`` I wonder why that happens. Did you modify the package before you uploaded it to your index?

**Comment by helloocc** [comment]
Yes, you are right. I init devpi and  just run with py2, it's all ok. Thanks!
But, I have a new problem...

- I have upgraded devpi from old version, and want to change the index, then encounter this error.
```
$ devpi index volatile=False
/iaas/product volatile=False
PATCH http://localhost/iaas/product
400 Bad Request: indexconfig got unexpected keyword arguments: pypi_whitelist=[]
```
- I notice that pypi_whitelist is removed in 5.0.0 changelog, but my index was created by 4.x version automaticlly. What can i do to change the index?
```
$ devpi index
http://localhost/iaas/product:
  type=stage
  bases=
  volatile=True
  acl_upload=iaas
  acl_toxresult_upload=:ANONYMOUS:
  mirror_whitelist=
  pypi_whitelist=
```

**Comment by fschulze** [comment]
Try ``devpi index pypi_whitelist-=``

**Comment by helloocc** [comment]
So kind fo you! I will close this issue.

**Comment by rcoup** [comment]
The `devpi index $INDEX key-=` is necessary if you uninstall a plugin that previously has config values (eg: devpi-slack). Worth adding in the docs somewhere?

**Comment by fschulze** [comment]
@rcoup Could you please make a separate ticket and link to the devpi-slack issue in it? This ticket is only kind of related and I don't want to reopen it because of that.
