### ISSUE TITLE
devpi will not run without ipv6

### ISSUE THREAD

**Issue by foxx** [devpi/devpi#727]
By default, devpi wants to bind to ipv6, and if the machine doesn't have IPv6 it will fail to start with an unhelpful error (I had to add a print into libs to figure out why it wasn't working).

```
# devpi-server
2019-10-11 16:13:57,046 INFO  NOCTX Loading node info from /root/.devpi/server/.nodeinfo
2019-10-11 16:13:57,047 INFO  NOCTX wrote nodeinfo to: /root/.devpi/server/.nodeinfo
2019-10-11 16:13:57,090 WARNI NOCTX No secret file provided, creating a new random secret. Login tokens issued before are invalidate. Use --secretfile option to provide a persistent secret.
2019-10-11 16:13:57,093 INFO  NOCTX Found plugin devpi-server-5.1.0 (None).
2019-10-11 16:13:57,095 INFO  NOCTX Found plugin devpi-server-5.1.0 (None).
2019-10-11 16:13:57,098 INFO  NOCTX Found plugin devpi-server-5.1.0 (None).
2019-10-11 16:13:57,100 INFO  NOCTX Found plugin devpi-server-5.1.0 (None).
2019-10-11 16:13:57,102 INFO  NOCTX Found plugin devpi-server-5.1.0 (None).
2019-10-11 16:13:57,104 INFO  NOCTX Found plugin devpi-server-5.1.0 (None).
2019-10-11 16:13:57,161 INFO  NOCTX devpi-server version: 5.1.0
2019-10-11 16:13:57,162 INFO  NOCTX serverdir: /root/.devpi/server
2019-10-11 16:13:57,162 INFO  NOCTX uuid: 087887ab9d924fdb9887d58c1659613c
2019-10-11 16:13:57,162 INFO  NOCTX serving at url: http://localhost:3141 (might be http://[localhost]:3141 for IPv6)
2019-10-11 16:13:57,162 INFO  NOCTX using 50 threads
2019-10-11 16:13:57,162 INFO  NOCTX bug tracker: https://github.com/devpi/devpi/issues
2019-10-11 16:13:57,162 INFO  NOCTX IRC: #devpi on irc.freenode.net
2019-10-11 16:13:57,162 INFO  NOCTX Hit Ctrl-C to quit.
('127.0.0.1', 3141)
('::1', 3141, 0, 0)
Traceback (most recent call last):
  File "/usr/local/bin/devpi-server", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/devpi_server/main.py", line 81, in main
    return _main(pluginmanager, argv=argv)
  File "/usr/local/lib/python3.5/dist-packages/devpi_server/main.py", line 167, in _main
    return xom.main()
  File "/usr/local/lib/python3.5/dist-packages/devpi_server/main.py", line 284, in main
    return wsgi_run(xom, app)
  File "/usr/local/lib/python3.5/dist-packages/devpi_server/main.py", line 196, in wsgi_run
    serve(app, host=host, port=port, threads=threads, max_request_body_size=max_body)
  File "/usr/local/lib/python3.5/dist-packages/waitress/__init__.py", line 11, in serve
    server = _server(app, **kw)
  File "/usr/local/lib/python3.5/dist-packages/waitress/server.py", line 85, in create_server
    sockinfo=sockinfo)
  File "/usr/local/lib/python3.5/dist-packages/waitress/server.py", line 229, in __init__
    self.bind_server_socket()
  File "/usr/local/lib/python3.5/dist-packages/waitress/server.py", line 360, in bind_server_socket
    self.bind(sockaddr)
  File "/usr/local/lib/python3.5/dist-packages/waitress/wasyncore.py", line 370, in bind
    return self.socket.bind(addr)
OSError: [Errno 99] Cannot assign requested address
```

**Comment by fschulze** [comment]
I use devpi on several machines without ipv6 and never got this error. Is ipv6 only partly enabled on your machine? I'm also not sure if this is a problem in how devpi uses waitress or in waitress itself.

**Comment by fschulze** [comment]
I can't reproduce this. Feel free to reopen with more info on how to reproduce this issue.

**Comment by chinochao** [comment]
I had this same issue and I was able to fix it by updating the systemd devpi.service file and adding --host 127.0.0.1 to the start and stop commands. For some reason binding to localhost was not working.

**Comment by Real-Gecko** [comment]
> I was having the same issue and I found the cause. It seemed the server first had IPv6 enabled and we disable it. However, the /etc/hosts file still has some entries for localhost pointing to IPv6 `::1 localhost` `::1 localhost6`
> 
> I commented those lines out and the service started.

You just saved my day!
