### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [devpi/devpi#750]
devpi's log:

```
/usr/local/lib/python3.6/site-packages/devpi_ldap/main.py:65: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  _config = yaml.load(f)
/usr/local/lib/python3.6/site-packages/devpi_ldap/main.py:65: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  _config = yaml.load(f)
2019-12-10 18:43:18,163 INFO  NOCTX Loading node info from /data/server/.nodeinfo
2019-12-10 18:43:18,232 INFO  NOCTX wrote nodeinfo to: /data/server/.nodeinfo
Traceback (most recent call last):
  File "/usr/local/bin/devpi-server", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/devpi_server/main.py", line 67, in main
    return _main(pluginmanager, argv=argv)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/main.py", line 112, in _main
    if not xom.is_replica() and xom.keyfs.get_current_serial() == -1:
  File "/usr/local/lib/python3.6/site-packages/devpi_common/types.py", line 38, in get
    x = self._property_cache[f] = f(self)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/main.py", line 280, in keyfs
    cache_size=self.config.args.keyfs_cache_size)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/keyfs.py", line 134, in __init__
    self._storage.perform_crash_recovery()
  File "/usr/local/lib/python3.6/site-packages/devpi_server/keyfs_sqlite_fs.py", line 94, in perform_crash_recovery
    if conn.last_changelog_serial == -1:
  File "/usr/local/lib/python3.6/site-packages/devpi_common/types.py", line 38, in get
    x = self._property_cache[f] = f(self)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/keyfs_sqlite.py", line 34, in last_changelog_serial
    return self.db_read_last_changelog_serial()
  File "/usr/local/lib/python3.6/site-packages/devpi_server/keyfs_sqlite.py", line 38, in db_read_last_changelog_serial
    res = self._sqlconn.execute(q).fetchone()[0]
sqlite3.DatabaseError: database disk image is malformed
```

And devpi is down, I can't use it.
It seems that some file in /data/server is bug
I want know the reason?

Currently, the only way to recover is use another serverdir with backup files

**Comment by fschulze** [comment]
In your server directory is a ``.sqlite`` file which seems to be corrupted. Generally SQLite tries very hard to avoid that, even a power outage shouldn't cause it. Either there is a hardware issue with the disk, something overwrote data in that file or you actually hit a bug in SQLite which caused this. Using the backup might be your only solution in this case, but I would double check your hardware first.

**Comment by ZhangSIming-blyq** [comment]
OK, I see.
I'm using s3fs for storaging packages in aws-s3, but this way seems has a certain risk.
Anyway thanks a lot.

**Comment by fschulze** [comment]
Network filesystems don't give the necessary guarantees required for database storage. We should put that prominently into the documentation.

**Comment by ZhangSIming-blyq** [comment]
Thanks again for your kind reply~
