### ISSUE TITLE
Strange pyrimad exception after `devpi test command` for one index and package under test

### ISSUE THREAD

**Issue by con-f-use** [devpi/devpi#798]
I don't know what to make of this:

Something seems to interfere with page rendering, after running `devpi test --index root/test qda_rest` which succeeded. I get this:

![image](https://user-images.githubusercontent.com/11145016/80920293-14519a80-8d6f-11ea-83fd-02a5e02619d2.png)

![image](https://user-images.githubusercontent.com/11145016/80920342-7ad6b880-8d6f-11ea-836c-5005cb75e1d6.png)

![image](https://user-images.githubusercontent.com/11145016/80920355-a0fc5880-8d6f-11ea-82c0-3b89ff63b0ec.png)

![image](https://user-images.githubusercontent.com/11145016/80920448-41eb1380-8d70-11ea-98ce-adeb1ff219f6.png)

on the index's page itself and on package page in question. Other indices or pages for other packages on the same index work fine. Consulting the logs gives me:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/usr/lib/python3.7/site-packages/pyramid/view.py", line 779, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/waitress/channel.py", line 356, in service
    task.service()
  File "/usr/lib/python3.7/site-packages/waitress/task.py", line 172, in service
    self.execute()
  File "/usr/lib/python3.7/site-packages/waitress/task.py", line 440, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/usr/lib/python3.7/site-packages/devpi_server/views.py", line 153, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/lib/python3.7/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/lib/python3.7/site-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/lib/python3.7/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/lib/python3.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/lib/python3.7/site-packages/devpi_server/views.py", line 177, in request_log_handler
    response = handler(request)
  File "/usr/lib/python3.7/site-packages/devpi_server/views.py", line 213, in request_tx_handler
    response = handler(request)
  File "/usr/lib/python3.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/lib/python3.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/lib/python3.7/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/lib/python3.7/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/usr/lib/python3.7/site-packages/pyramid/config/views.py", line 169, in __call__
    return view(context, request)
  File "/usr/lib/python3.7/site-packages/pyramid/config/views.py", line 188, in attr_view
    return view(context, request)
  File "/usr/lib/python3.7/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
    return view(context, request)
  File "/usr/lib/python3.7/site-packages/pyramid/viewderivers.py", line 460, in rendered_view
    request, result, view_inst, context
  File "/usr/lib/python3.7/site-packages/pyramid/renderers.py", line 451, in render_view
    return self.render_to_response(response, system, request=request)
  File "/usr/lib/python3.7/site-packages/pyramid/renderers.py", line 474, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/usr/lib/python3.7/site-packages/pyramid/renderers.py", line 470, in render
    result = renderer(value, system_values)
  File "/usr/lib/python3.7/site-packages/pyramid_chameleon/zpt.py", line 47, in __call__
    result = self.template(**system)
  File "/usr/lib/python3.7/site-packages/chameleon/template.py", line 140, in __call__
    return self.render(**kwargs)
  File "/usr/lib/python3.7/site-packages/chameleon/zpt/template.py", line 306, in render
    return super(PageTemplate, self).render(**_kw)
  File "/usr/lib/python3.7/site-packages/chameleon/template.py", line 209, in render
    raise_with_traceback(exc, tb)
  File "/usr/lib/python3.7/site-packages/chameleon/utils.py", line 75, in raise_with_traceback
    raise exc
  File "/usr/lib/python3.7/site-packages/chameleon/template.py", line 187, in render
    self._render(stream, econtext, rcontext)
  File "index_a2da5f463139d8febc7b024f6ff6cce9.py", line 1571, in render
  File "/usr/lib/python3.7/site-packages/chameleon/zpt/template.py", line 310, in include
    self._render(*args, **kwargs)
  File "layout_794cf1eeba053d71f9981451f8cd288c.py", line 776, in render
  File "index_a2da5f463139d8febc7b024f6ff6cce9.py", line 572, in __fill_content
  File "index_a2da5f463139d8febc7b024f6ff6cce9.py", line 572, in <genexpr>
KeyError: 'failed'

 - Expression: "content_class|'segment basic'"
 - Filename:   /devpi/devpi_semantic_ui/templates/layout.pt
 - Location:   (line 38: col 44)
 - Source:     ... i main container ${content_class|'segment basic'}">
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "load: layout.pt"
 - Filename:   /devpi/devpi_semantic_ui/templates/index.pt
 - Location:   (line 1: col 25)
 - Source:     <metal:layout use-macro="load: layout.pt">
                                        ^^^^^^^^^^^^^^^
 - Arguments:  view: <function index_get at 0x7f076d223050>
               renderer_name: templates/index.pt
               renderer_info: <RendererHelper - at 0x7f0747bc4550>
               context: <RootFactory - at 0x7f0753fe0750>
               request: <Request - at 0x7f073bc91190>
               req: <Request - at 0x7f073bc91190>
               get_csrf_token: <partial - at 0x7f076618b710>
               title: root/test index
               simple_index_url: http://10.17.65.203/root/test/+simple/
               permissions: <list - at 0x7f074778b5a0>
               bases: <list - at 0x7f074e11b5a0>
               packages: <list - at 0x7f076a06cbe0>
               whitelist: <list - at 0x7f0747516f00>
               index_name: root/test
               index_title: Test Index
               index_description: Everything is allowed here, YOLO!\n\nInherits from t...
               target_language: <NoneType - at 0x7f07700ec290>
               repeat: {...} (0)
               macroname: load: layout.pt
```

**Comment by fschulze** [comment]
Something in the toxresult data is missing. Could you provide the uploaded toxresult file?

**Comment by con-f-use** [comment]
I'll try to re-create it, had to delete it because the main page of an index is kinda nice to have :wink:

**Comment by con-f-use** [comment]
```
{
  "reportversion": "1",
  "toxversion": "3.23.0",
  "platform": "linux",
  "host": "localhost",
  "commands": [],
  "testenvs": {
    "py27": {
      "setup": [
        {
          "command": [
            "/home/jan/devel/cuda/qda_rest/.direnv/python-3.8.8/bin/python3",
            "-m",
            "virtualenv",
            "--no-download",
            "--python",
            "/nix/store/jiikg1lncfy4zbr1cqx9vq59c41v77x5-python-2.7.18-env/bin/python2.7",
            "py27"
          ],
          "output": "ValueError: source and destination is the same /nix/store/vsysfrikkciyzwl38w9zgpk6rfqxgb0y-python-2.7.18/lib/python2.7/os.py\n",
          "retcode": 1
        },
        {
          "command": [
            "setup virtualenv"
          ],
          "output": "InvocationError for command /home/jan/devel/cuda/qda_rest/.direnv/python-3.8.8/bin/python3 -m virtualenv --no-download --python /nix/store/jiikg1lncfy4zbr1cqx9vq59c41v77x5-python-2.7.18-env/bin/python2.7 py27 (exited with code 1)",
          "retcode": 1
        }
      ]
    },
    "py36": {
      "setup": [
        {
          "command": [
            "setup virtualenv"
          ],
          "output": "InterpreterNotFound: python3.6",
          "retcode": 1
        }
      ]
    }
  }
}
```

I was able to reproduce the problem, intentionally provoking errors in the tox run.

**Comment by fschulze** [comment]
This seems to be an error in ``devpi-semantic-ui``. I can't reproduce this with plain ``devpi-web``, but get the same error with the theme active. You should file a bug report there and link to this issue.

**Comment by con-f-use** [comment]
Unfortunately, `devpi-semantic-ui` seems unmaintained since 2017. The default devpi theme is very unattractive, maybe you could adopt (and adapt) semantic-ui into the main web plugin? It would give the whole project a more professional look. No offence, I think you and Holger are exceptionally professional behind the curtain.

**Comment by con-f-use** [comment]
These [changes](https://github.com/apihackers/devpi-semantic-ui/pull/11) fixed it for me.

https://github.com/apihackers/devpi-semantic-ui/pull/11
