### ISSUE TITLE
devpi upload fails due to check-manifest release 0.42

### ISSUE THREAD

**Issue by agentram** [devpi/devpi#805]
https://github.com/devpi/devpi/blob/7b2a40e87e9927a28eb554d0454130cd663e34f3/client/setup.py#L32

Since check-manifest [made release](https://github.com/mgedmin/check-manifest/releases) 0.42, the command `devpi upload --formats bdist_wheel` raises the error:

```
root@9dbb2544ee26:/build# devpi upload --formats bdist_wheel
Traceback (most recent call last):
  File "/opt/python3.6/bin/devpi", line 11, in <module>
    sys.exit(main())
  File "/opt/python3.6/lib/python3.6/site-packages/devpi/main.py", line 32, in main
    return method(hub, hub.args)
  File "/opt/python3.6/lib/python3.6/site-packages/devpi/upload.py", line 33, in main
    setupdir_only=setupcfg.get("setupdir-only"))
  File "/opt/python3.6/lib/python3.6/site-packages/devpi/upload.py", line 281, in __init__
    hasvcs = check_manifest.detect_vcs().metadata_name
TypeError: detect_vcs() missing 1 required positional argument: 'ui'

root@9dbb2544ee26:/# python --version
Python 3.6.1

root@9dbb2544ee26:/# pip list
Package        Version
-------------- ----------
appdirs        1.4.4
certifi        2020.4.5.1
chardet        3.0.4
check-manifest 0.42
devpi-client   5.2.0
devpi-common   3.5.0
distlib        0.3.0
filelock       3.0.12
idna           2.9
lazy           1.4
packaging      20.3
pep517         0.8.2
pip            20.1
pkginfo        1.5.0.1
pluggy         0.13.1
py             1.8.1
pyparsing      2.4.7
requests       2.23.0
setuptools     46.3.0
six            1.14.0
toml           0.10.1
tox            3.15.0
urllib3        1.25.9
virtualenv     20.0.20
wheel          0.34.2
```

It works well under check-manifest 0.41:

```
root@9dbb2544ee26:/build# pip install check-manifest==0.41
Collecting check-manifest==0.41
  Downloading check_manifest-0.41-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: toml in /usr/local/lib/python3.8/site-packages (from check-manifest==0.41) (0.10.1)
Requirement already satisfied: pep517 in /usr/local/lib/python3.8/site-packages (from check-manifest==0.41) (0.8.2)
Installing collected packages: check-manifest
  Attempting uninstall: check-manifest
    Found existing installation: check-manifest 0.42
    Uninstalling check-manifest-0.42:
      Successfully uninstalled check-manifest-0.42
Successfully installed check-manifest-0.41
root@9dbb2544ee26:/build# devpi upload --formats bdist_wheel
using workdir /tmp/devpi0
pre-build: cleaning /build/dist
-->  /build$ /opt/python3.6/bin/python3 setup.py bdist_wheel
built: /build/dist/pkg-0.1.19-py3-none-any.whl [BDIST_WHEEL] 1433.35kb
register pkg-0.1.19 to https://devpypi.example.net/INDEX/master/
file_upload of pkg-0.1.19-py3-none-any.whl to https://devpypi.example.net/INDEX/master/
```

**Comment by fschulze** [comment]
Should already be fixed by https://pypi.org/project/devpi-client/5.2.0/

**Comment by fschulze** [comment]
Ups, just saw you already have it in the list. Hmmm, need to check again

**Comment by fschulze** [comment]
I suspect the devpi-client used is not the one from your pip list. The lines in the traceback don't match. You get 281, but in devpi-client 5.2.0 it would be 288.

**Comment by agentram** [comment]
Yeah, I didn't notice it was an old version when I tried it the first time. Tested, version 5.2.0 fixes the error. Thank you.

**Comment by allanlewis** [comment]
Just mentioning some relevant commits for reference:
https://github.com/devpi/devpi/commit/db207b972e1a9e17b4d661665f7c357c47990c7a
https://github.com/devpi/devpi/commit/f40e0f51b610325d807367206cced90ed1fa005d
