### ISSUE TITLE
"Permission denied" error for workdir when running client with different users

### ISSUE THREAD

**Issue by The-Compiler** [devpi/devpi#808]
On Debian 10, with devpi-client 5.2.0, py 1.9.0 and Python 3.7.7, I'm getting this when trying to run e.g. `devpi upload` with different user accounts:

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/devpi/main.py", line 216, in _workdir
    return self.__workdir
AttributeError: 'Hub' object has no attribute '_Hub__workdir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/py/_error.py", line 66, in checked_call
    return func(*args, **kwargs)
PermissionError: [Errno 13] Permission denied: '17952' -> '/tmp/devpi4/.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/bin/devpi", line 10, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.7/site-packages/devpi/main.py", line 36, in main
    return method(hub, hub.args)
  File "/opt/venv/lib/python3.7/site-packages/devpi/upload.py", line 35, in main
    uploadbase = hub.getdir("upload")
  File "/opt/venv/lib/python3.7/site-packages/devpi/main.py", line 211, in getdir
    return self._workdir.mkdir(name)
  File "/opt/venv/lib/python3.7/site-packages/devpi/main.py", line 218, in _workdir
    self.__workdir = py.path.local.make_numbered_dir(prefix="devpi")
  File "/opt/venv/lib/python3.7/site-packages/py/_path/local.py", line 943, in make_numbered_dir
    create_lockfile(path)
  File "/opt/venv/lib/python3.7/site-packages/py/_path/local.py", line 866, in create_lockfile
    lockfile.mksymlinkto(str(mypid))
  File "/opt/venv/lib/python3.7/site-packages/py/_path/local.py", line 87, in mksymlinkto
    py.error.checked_call(os.symlink, str(value), self.strpath)
  File "/opt/venv/lib/python3.7/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.EACCES: [Permission denied]: symlink('17952', '/tmp/devpi4/.lock')
```

I think what's happening is that devpi tries to re-use the same temporary directory when a directory already exists from a different users.

Perhaps this is something that should be fixed in pylib's `make_numbered_dir`? On the other hand, pytest uses `pytest-of-{username}` as subdir name, so maybe devpi should do the same which would fix this issue?

**Comment by fschulze** [comment]
Same cause as for #807 I think. I will look at what pytest is doing.

**Comment by The-Compiler** [comment]
Indeed, that looks like the same thing. Sorry, I didn't notice that and only searched for parts of the stacktrace.

**Comment by fschulze** [comment]
I guess https://github.com/pytest-dev/pytest/issues/8414 is the same, as the code was initially the same.
