### ISSUE TITLE
long error stacks on bad network

### ISSUE THREAD

**Issue by gaborbernat** [devpi/devpi#809]
On a bad network I often get long stack traces that complain about I/O error and AttributeError:

```
2020-07-15 14:46:43,278 INFO  [req200] GET /bernat/bb/+f/f4d/a1763d3becf2e/wheel-0.33.6-py2.py3-none-any.whl
2020-07-15 14:46:48,231 ERROR Exception while serving /bernat/bb/+f/b27/c4dedae8c41aa/pip-20.1.1-py2.py3-none-any.whl
Traceback (most recent call last):
  File "/devpi/lib/python3.8/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/devpi/lib/python3.8/site-packages/pyramid/view.py", line 779, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/devpi/lib/python3.8/site-packages/devpi_server/keyfs.py", line 289, in transaction
    yield tx
  File "/devpi/lib/python3.8/site-packages/devpi_server/views.py", line 215, in request_tx_handler
    response = handler(request)
  File "/devpi/lib/python3.8/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/devpi/lib/python3.8/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/devpi/lib/python3.8/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/devpi/lib/python3.8/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/devpi/lib/python3.8/site-packages/pyramid/router.py", line 147, in handle_request
    response = _call_view(
  File "/devpi/lib/python3.8/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/devpi/lib/python3.8/site-packages/pyramid/config/views.py", line 169, in __call__
    return view(context, request)
  File "/devpi/lib/python3.8/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/devpi/lib/python3.8/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/devpi/lib/python3.8/site-packages/devpi_server/views.py", line 1191, in stage_pkgserv
    return self._pkgserv(entry)
  File "/devpi/lib/python3.8/site-packages/devpi_server/views.py", line 1159, in _pkgserv
    headers = next(app_iter)
  File "/devpi/lib/python3.8/site-packages/devpi_server/views.py", line 1478, in iter_fetch_remote_file
    keyfs.restart_as_write_transaction()
  File "/devpi/lib/python3.8/site-packages/devpi_server/keyfs.py", line 263, in restart_as_write_transaction
    tx.restart(write=True)
  File "/devpi/lib/python3.8/site-packages/devpi_server/keyfs.py", line 625, in restart
    newtx = self.__class__(self.keyfs, write=write)
  File "/devpi/lib/python3.8/site-packages/devpi_server/keyfs.py", line 409, in __init__
    self.conn = keyfs._storage.get_connection(write=write, closing=False)
  File "/devpi/lib/python3.8/site-packages/devpi_server/keyfs_sqlite.py", line 220, in get_connection
    sqlconn.execute("begin immediate")
sqlite3.OperationalError: disk I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/devpi/lib/python3.8/site-packages/devpi_server/views.py", line 178, in request_log_handler
    response = handler(request)
  File "/devpi/lib/python3.8/site-packages/devpi_server/views.py", line 215, in request_tx_handler
    response = handler(request)
  File "/Users/bgabor8/.pyenv/versions/3.8.3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/devpi/lib/python3.8/site-packages/devpi_server/keyfs.py", line 291, in transaction
    self.rollback_transaction_in_thread()
  File "/devpi/lib/python3.8/site-packages/devpi_server/keyfs.py", line 275, in rollback_transaction_in_thread
    self._threadlocal.tx.rollback()
  File "/devpi/lib/python3.8/site-packages/devpi_server/keyfs.py", line 615, in rollback
    self.conn.rollback()
  File "/devpi/lib/python3.8/site-packages/devpi_server/keyfs_sqlite_fs.py", line 49, in rollback
    BaseConnection.rollback(self)
  File "/devpi/lib/python3.8/site-packages/devpi_server/keyfs_sqlite.py", line 30, in rollback
    self._sqlconn.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/devpi_server/views.py", line 154, in __call__
    return self.app(environ, start_response)
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/devpi_server/views.py", line 195, in request_log_handler
    thread_pop_log(tag)
  File "/Users/bgabor8/.local/pipx/venvs/devpi/lib/python3.8/site-packages/devpi_server/log.py", line 103, in thread_pop_log
    if prefix and not threadlocal.taglogger._prefix.rstrip().endswith(prefix):
AttributeError: 'NoneType' object has no attribute '_prefix'
```

**Comment by fschulze** [comment]
Do you have the devpi-server data on a network drive? That is not supported (but not documented clearly), because almost no network file sharing protocol guaranties the necessary file locking for sqlite. If you need your data on another server, you should look into devpi-postgresql.

**Comment by fschulze** [comment]
Then please tell me more about the circumstances. In which operations does the bad network come into play? The log indicates the exception happened while serving a package from a private index. Are you trying to install from the same computer, or is the bad network in between pip and devpi-server? What is the output of pip in such cases?

**Comment by gaborbernat** [comment]
It's on a laptop. pip and devpi running on the same machine, through also local proxy server. The network between the private server and devpi is unstable (random packet drops), and then the above start happening. Things eventually succeed, however the above exceptions leave me to believe that devpi should handle this more gracefully and there's some bug within.

**Comment by fschulze** [comment]
I took another look at this and it is still not clear to me what is happening. The log needs more info starting from ``GET /bernat/bb/+f/b27/c4dedae8c41aa/pip-20.1.1-py2.py3-none-any.whl``. It would also be useful to get additional log output using ``--debug``.

Searching for ``sqlite3.OperationalError: disk I/O error`` showed that there might be a problem with the sqlite locking. It seems to happen when the journal file can't be opened. Most of the reasons pointed to either a network file system or a permission error, but neither seems applicable here.

What I still don't understand is where the bad networking gets involved. In what way is your private server accessed if everything else is on your laptop? Is ``bernat/bb`` a mirror index?

**Comment by gaborbernat** [comment]
It is a mirror index.

**Comment by fschulze** [comment]
Is anything done in parallel to the download in devpi-server? According to your log snippet it looks like the wheel package was installed while pip was downloading.

A longer log with ``--debug`` starting from the ``GET`` of the actual file where the traceback happens would be very helpful to figure out what is happening.

**Comment by gaborbernat** [comment]
Sadly this was last July, and since my network improved a bit, so the issue is not as pronounced. So can't provide more logs/information at the moment.

**Comment by fschulze** [comment]
This should be vastly improved with devpi-server 6.5.0.

**Comment by gaborbernat** [comment]
Cool :-)
