### ISSUE TITLE
devpi-web==4.0.5 ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by AndrewTsao** [devpi/devpi#814]
- [ x] Are you using the latest released version?
      If something is preventing you from trying with the newest version,
      we would like to know so we can make it easier.
- [x ] Provide the output of ``pip list`` from the virtual environment you are using.
```
apipkg==1.5
appdirs==1.4.4
argon2-cffi==20.1.0
attrs==19.3.0
beautifulsoup4==4.9.1
bleach==3.1.5
certifi==2020.6.20
cffi==1.14.0
Chameleon==3.8.1
chardet==3.0.4
check-manifest==0.42
cmarkgfm==0.4.2
colorama==0.4.3
defusedxml==0.6.0
devpi-client==5.2.0
devpi-common==3.5.0
devpi-server==5.5.0
devpi-web==4.0.5
distlib==0.3.1
docutils==0.16
execnet==1.7.1
filelock==3.0.12
hupper==1.10.2
idna==2.10
importlib-metadata==1.7.0
importlib-resources==3.0.
itsdangerous==1.1.0
lazy==1.4
packaging==20.4
passlib==1.7.2
PasteDeploy==2.1.0
pep517==0.8.2
pkginfo==1.5.0.1
plaster==1.0
plaster-pastedeploy==0.7
pluggy==0.13.1
py==1.9.0
pycparser==2.20
Pygments==2.6.1
pyparsing==2.4.7
pyramid==1.10.4
pyramid-chameleon==0.3
python-dateutil==2.8.1
readme-renderer==26.0
repoze.lru==0.7
requests==2.24.0
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
six==1.15.0
soupsieve==2.0.1
strictyaml==1.0.6
toml==0.10.1
tox==3.17.1
translationstring==1.4
urllib3==1.25.10
venusian==3.0.0
virtualenv==20.0.27
waitress==1.4.4
webencodings==0.5.1
WebOb==1.8.6
Whoosh==2.7.4
zipp==3.1.0
zope.deprecation==4.4.0
zope.interface==5.1.0
```
- [x ] Provide the Python and operating system versions under which the issue occurs.
   Windows 7
- [ ] If possible, provide a minimal example to reproduce the issue.
```
(.venv) D:\jindefund\devpi>.venv\Scripts\python -mdevpi_server --serverdir devpi-data --host 0.0.0.0 --port 8082
Traceback (most recent call last):
  File "c:\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\jindefund\devpi\.venv\lib\site-packages\devpi_server\__main__.py", line 4, in <module>
    devpi_server.main.main()
  File "D:\jindefund\devpi\.venv\lib\site-packages\devpi_server\main.py", line 79, in main
    pluginmanager = get_pluginmanager()
  File "D:\jindefund\devpi\.venv\lib\site-packages\devpi_server\config.py", line 38, in get_pluginmanager
    pm.load_setuptools_entrypoints("devpi_server")
  File "D:\jindefund\devpi\.venv\lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "D:\jindefund\devpi\.venv\lib\site-packages\importlib_metadata\__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "c:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\jindefund\devpi\.venv\lib\site-packages\devpi_web\main.py", line 6, in <module>
    from devpi_web.doczip import remove_docs
  File "D:\jindefund\devpi\.venv\lib\site-packages\devpi_web\doczip.py", line 12, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by fschulze** [comment]
Will be fixed in the next devpi-web release.

**Comment by fschulze** [comment]
Can you try it with the following development release?
https://m.devpi.net/fschulze/dev/devpi-web/4.0.6.dev0

**Comment by sethgilchrist** [comment]
I had this same problem on Win10 Pro build 19042 and the 4.0.6.dev0 release fixed the problem.

**Comment by jrast** [comment]
Is there a plan on when version 4.0.6 will be released?

**Comment by fschulze** [comment]
I hope to do a release in the next few work days. The reminder came just right, because I'm finally able to work on devpi again.

**Comment by fschulze** [comment]
I just release devpi-web 4.0.6.
