### ISSUE TITLE
Changing mirror_url doesn't seem to work

### ISSUE THREAD

**Issue by hrbonz** [devpi/devpi#817]
I'm trying to install a server from inside China and struggling to access (apparently) pythonhosted.org. Because of this, I changed the pypi index to use https://pypi.tuna.tsinghua.edu.cn/simple/ as it is recommended in several places. When trying to download certain public packages, the search using `/simple/` seems to be working but, oddly, devpi-server seems to still be trying to download packages using pythonhoted.org rather than the mirror. I then changed the mirror_url to https://pypi.mirrors.ustc.edu.cn/simple/ to see if I'd have better luck but then the output of devpi-server was all over the place between the two indexes and file downloads from pythonhosted.org.

I don't really know the codebase but there might be a corrupted state for this package somewhere (sqlite?) that forces an old download link somehow.
The current state of affairs is extremely frustrating

Here's what I did:
```
$ devpi login root
$ devpi index root/pypi
https://pypi.example.com/root/pypi:
  type=mirror                                          
  volatile=False                                          
  mirror_url=https://pypi.org/simple/                
  mirror_web_url_fmt=https://pypi.org/project/{name}/
  title=PyPI                       
$ devpi index root/pypi mirror_url="https://pypi.tuna.tsinghua.edu.cn/simple/"
/root/pypi mirror_url=https://pypi.tuna.tsinghua.edu.cn/simple/
https://pypi.example.com/root/pypi?no_projects=:
  type=mirror
  volatile=False
  mirror_url=https://pypi.tuna.tsinghua.edu.cn/simple/
  mirror_web_url_fmt=https://pypi.org/project/{name}/
  title=PyPI
$ mkvirtualenv --system-site-packages -p /usr/bin/python3 foobar
[FAILS]
$ devpi index root/pypi mirror_url="https://pypi.mirrors.ustc.edu.cn/simple/"
/root/pypi mirror_url=https://pypi.mirrors.ustc.edu.cn/simple/
https://pypi.example.com/root/pypi?no_projects=:
  type=mirror
  volatile=False
  mirror_url=https://pypi.mirrors.ustc.edu.cn/simple/
  mirror_web_url_fmt=https://pypi.org/project/{name}/
  title=PyPI
$ mkvirtualenv -v --system-site-packages -p /usr/bin/python3 foobar
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
Directory /home/hr/.virtualenvs/foobar/lib/python3.7 already exists
Symlinking Python bootstrap modules
  Ignoring built-in bootstrap module: posix
  Cannot import bootstrap module: nt
  Cannot import bootstrap module: UserDict
  Cannot import bootstrap module: copy_reg
  Cannot import bootstrap module: sre
  Ignoring built-in bootstrap module: zlib
  Cannot import bootstrap module: _abcoll
Directory /home/hr/.virtualenvs/foobar/lib/python3.7/site-packages already exists
Content /home/hr/.virtualenvs/foobar/lib/python3.7/site.py already in place
Content /home/hr/.virtualenvs/foobar/lib/python3.7/orig-prefix.txt already in place
Directory /home/hr/.virtualenvs/foobar/bin already exists
New python executable in /home/hr/.virtualenvs/foobar/bin/python3
Changed mode of /home/hr/.virtualenvs/foobar/bin/python3 to 0o755
Not overwriting existing python script /home/hr/.virtualenvs/foobar/bin/python (you must use /home/hr/.virtualenvs/foobar/bin/python3)
Testing executable with /home/hr/.virtualenvs/foobar/bin/python3 -c "import sys;out=sys.stdout;getattr(out, "buffer", out).write(sys.prefix.encode("utf-8"))"
Got sys.prefix result: '/home/hr/.virtualenvs/foobar'
Directory /home/hr/.virtualenvs/foobar/lib/python3.7/distutils already exists
Content /home/hr/.virtualenvs/foobar/lib/python3.7/distutils/__init__.py already in place
Content /home/hr/.virtualenvs/foobar/lib/python3.7/distutils/distutils.cfg already in place
Installing setuptools, pkg_resources, pip, wheel...
  Looking in indexes: https://pypi.example.com/gams/prod/+simple/
  Looking in links: /usr/lib/python3/dist-packages, /usr/share/python-wheels/
  Collecting setuptools
    Downloading https://pypi.example.com/root/pypi/+f/bb3/522bc8120a0ea/setuptools-50.0.3-py3-none-any.whl (784kB)
  Collecting pkg_resources
  Collecting pip
    Downloading https://pypi.example.com/root/pypi/+f/524/4e51494f5d1df/pip-20.2.2-py2.py3-none-any.whl (1.5MB)
  Collecting wheel
    Downloading https://pypi.example.com/root/pypi/+f/497/add53525d16c1/wheel-0.35.1-py2.py3-none-any.whl
  THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
      setuptools from https://pypi.example.com/root/pypi/+f/bb3/522bc8120a0ea/setuptools-50.0.3-py3-none-any.whl#sha256=bb3522bc8120a0eaeb209677c0a001df2c9b95054c4ea945710655a07a3bba9f:
          Expected sha256 bb3522bc8120a0eaeb209677c0a001df2c9b95054c4ea945710655a07a3bba9f
               Got        e0305498ebcee061ee36fdf1ebd68e0984f927858ad04171f177ef0818a1596c
  
  Complete output from command /home/hr/.virtualenvs/foobar/bin/python3 - setuptools pkg_resources pip wheel:
  Looking in indexes: https://pypi.example.com/gams/prod/+simple/
Looking in links: /usr/lib/python3/dist-packages, /usr/share/python-wheels/
Collecting setuptools
  Downloading https://pypi.example.com/root/pypi/+f/bb3/522bc8120a0ea/setuptools-50.0.3-py3-none-any.whl (784kB)
Collecting pkg_resources
Collecting pip
  Downloading https://pypi.example.com/root/pypi/+f/524/4e51494f5d1df/pip-20.2.2-py2.py3-none-any.whl (1.5MB)
Collecting wheel
  Downloading https://pypi.example.com/root/pypi/+f/497/add53525d16c1/wheel-0.35.1-py2.py3-none-any.whl
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    setuptools from https://pypi.example.com/root/pypi/+f/bb3/522bc8120a0ea/setuptools-50.0.3-py3-none-any.whl#sha256=bb3522bc8120a0eaeb209677c0a001df2c9b95054c4ea945710655a07a3bba9f:
        Expected sha256 bb3522bc8120a0eaeb209677c0a001df2c9b95054c4ea945710655a07a3bba9f
             Got        e0305498ebcee061ee36fdf1ebd68e0984f927858ad04171f177ef0818a1596c

----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 11, in <module>
    load_entry_point('virtualenv==15.1.0', 'console_scripts', 'virtualenv')()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 996, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 926, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 817, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/hr/.virtualenvs/foobar/bin/python3 - setuptools pkg_resources pip wheel failed with error code 1
```

Here's the log of devpi-server running with `--debug` for the second run of mkvirtualenv (after changing mirror_url twice):
```
2020-09-04 23:17:16,490 INFO  [req0] GET /abc/prod/+simple/setuptools/
2020-09-04 23:17:16,491 DEBUG [req0] [Rtx277] in-transaction 277
2020-09-04 23:17:16,505 DEBUG [req0] [Rtx277] reading index https://pypi.mirrors.ustc.edu.cn/simple/setuptools/
2020-09-04 23:17:16,512 DEBUG Starting new HTTPS connection (1): pypi.mirrors.ustc.edu.cn:443
2020-09-04 23:17:16,599 DEBUG https://pypi.mirrors.ustc.edu.cn:443 "GET /simple/setuptools/ HTTP/1.1" 302 142
2020-09-04 23:17:16,602 DEBUG Starting new HTTPS connection (1): mirrors.ustc.edu.cn:443
2020-09-04 23:17:16,686 DEBUG https://mirrors.ustc.edu.cn:443 "GET /pypi/web/simple/setuptools/ HTTP/1.1" 302 142
2020-09-04 23:17:16,688 DEBUG Starting new HTTPS connection (1): mirrors.tuna.tsinghua.edu.cn:443
2020-09-04 23:17:16,882 DEBUG https://mirrors.tuna.tsinghua.edu.cn:443 "GET /pypi/web/simple/setuptools/ HTTP/1.1" 200
 265774
2020-09-04 23:17:16,883 WARNI [req0] [Rtx277] serving cached links for https://mirrors.tuna.tsinghua.edu.cn/pypi/web/s
imple/setuptools/ because returned serial -1, cache_serial 8090912 is better!
2020-09-04 23:17:16,887 DEBUG [req0] [Rtx277] reading index https://pypi.mirrors.ustc.edu.cn/simple/setuptools/
2020-09-04 23:17:16,906 DEBUG https://pypi.mirrors.ustc.edu.cn:443 "GET /simple/setuptools/ HTTP/1.1" 302 142
2020-09-04 23:17:16,925 DEBUG https://mirrors.ustc.edu.cn:443 "GET /pypi/web/simple/setuptools/ HTTP/1.1" 302 142
2020-09-04 23:17:16,926 DEBUG Starting new HTTPS connection (2): mirrors.tuna.tsinghua.edu.cn:443
2020-09-04 23:17:18,099 DEBUG https://mirrors.tuna.tsinghua.edu.cn:443 "GET /pypi/web/simple/setuptools/ HTTP/1.1" 200
 265774
2020-09-04 23:17:18,099 WARNI [req0] [Rtx277] serving cached links for https://mirrors.tuna.tsinghua.edu.cn/pypi/web/s
imple/setuptools/ because returned serial -1, cache_serial 8090912 is better!
2020-09-04 23:17:18,107 DEBUG [req0] [Rtx277] closing transaction at 277
2020-09-04 23:17:18,108 DEBUG [req0] 200 OK 1.617s serial=277 length=229443 type=text/html; charset=UTF-8
2020-09-04 23:17:18,538 INFO  [req1] GET /root/pypi/+f/bb3/522bc8120a0ea/setuptools-50.0.3-py3-none-any.whl
2020-09-04 23:17:18,539 DEBUG [req1] [Rtx277] in-transaction 277
2020-09-04 23:17:18,540 DEBUG [req1] closing transaction at 277
2020-09-04 23:17:18,540 DEBUG [req1] restarting read transaction afresh as write transaction
2020-09-04 23:17:18,542 DEBUG Starting new HTTPS connection (1): files.pythonhosted.org:443
2020-09-04 23:17:30,568 DEBUG https://files.pythonhosted.org:443 "GET /packages/6d/ed/52e05469314a266f68d9f251a8c1ab7a
21a03327b1724056e3eea654bfd1/setuptools-50.0.3-py3-none-any.whl HTTP/1.1" 200 784827
2020-09-04 23:17:30,568 INFO  [req1] [Wtx277] reading remote: https://files.pythonhosted.org/packages/6d/ed/52e0546931
4a266f68d9f251a8c1ab7a21a03327b1724056e3eea654bfd1/setuptools-50.0.3-py3-none-any.whl, target root/pypi/+f/bb3/522bc81
20a0ea/setuptools-50.0.3-py3-none-any.whl
2020-09-04 23:17:30,568 DEBUG [req1] [Wtx277] nothing to commit, just closing tx
2020-09-04 23:17:30,568 DEBUG [req1] [Wtx277] closing transaction at 277
2020-09-04 23:17:30,569 DEBUG [req1] 200 OK 12.030s serial=None length=784827 type=a
2020-09-04 23:17:43,471 ERROR Exception while serving /root/pypi/+f/bb3/522bc8120a0ea/setuptools-50.0.3-py3-none-any.w
hl
Traceback (most recent call last):
  File "/var/lib/virtualenv/pypi3/lib/python3.5/site-packages/urllib3/response.py", line 436, in _error_catcher
    yield
  File "/var/lib/virtualenv/pypi3/lib/python3.5/site-packages/urllib3/response.py", line 518, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/virtualenv/pypi3/lib/python3.5/site-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/var/lib/virtualenv/pypi3/lib/python3.5/site-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/var/lib/virtualenv/pypi3/lib/python3.5/site-packages/waitress/task.py", line 463, in execute
    for chunk in app_iter:
  File "/var/lib/virtualenv/pypi3/lib/python3.5/site-packages/devpi_server/views.py", line 1480, in iter_fetch_remote_
file
    for part in iter_cache_remote_file(xom, entry):
  File "/var/lib/virtualenv/pypi3/lib/python3.5/site-packages/devpi_server/views.py", line 1351, in iter_cache_remote_
file
    data = r.raw.read(10240)
  File "/var/lib/virtualenv/pypi3/lib/python3.5/site-packages/urllib3/response.py", line 540, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/var/lib/virtualenv/pypi3/lib/python3.5/site-packages/urllib3/response.py", line 441, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
2020-09-04 23:17:43,873 INFO  [req2] GET /abc/prod/+simple/pkg-resources/
2020-09-04 23:17:43,873 DEBUG [req2] [Rtx277] in-transaction 277
2020-09-04 23:17:43,875 DEBUG [req2] [Rtx277] reading index https://pypi.mirrors.ustc.edu.cn/simple/pkg-resources/
2020-09-04 23:17:43,876 DEBUG Resetting dropped connection: pypi.mirrors.ustc.edu.cn
2020-09-04 23:17:43,961 DEBUG https://pypi.mirrors.ustc.edu.cn:443 "GET /simple/pkg-resources/ HTTP/1.1" 302 142
2020-09-04 23:17:43,963 DEBUG Resetting dropped connection: mirrors.ustc.edu.cn
2020-09-04 23:17:44,057 DEBUG https://mirrors.ustc.edu.cn:443 "GET /pypi/web/simple/pkg-resources/ HTTP/1.1" 302 142
2020-09-04 23:17:44,059 DEBUG Starting new HTTPS connection (3): mirrors.tuna.tsinghua.edu.cn:443
2020-09-04 23:17:44,197 DEBUG https://mirrors.tuna.tsinghua.edu.cn:443 "GET /pypi/web/simple/pkg-resources/ HTTP/1.1" 
404 169
2020-09-04 23:17:44,198 WARNI [req2] [Rtx277] serving stale links for 'pkg-resources', url 'https://pypi.mirrors.ustc.
edu.cn/simple/pkg-resources/' responded 404 Not Found
2020-09-04 23:17:44,199 DEBUG [req2] [Rtx277] reading index https://pypi.mirrors.ustc.edu.cn/simple/pkg-resources/
2020-09-04 23:17:44,219 DEBUG https://pypi.mirrors.ustc.edu.cn:443 "GET /simple/pkg-resources/ HTTP/1.1" 302 142
2020-09-04 23:17:44,240 DEBUG https://mirrors.ustc.edu.cn:443 "GET /pypi/web/simple/pkg-resources/ HTTP/1.1" 302 142
2020-09-04 23:17:44,242 DEBUG Starting new HTTPS connection (4): mirrors.tuna.tsinghua.edu.cn:443
2020-09-04 23:17:44,634 DEBUG https://mirrors.tuna.tsinghua.edu.cn:443 "GET /pypi/web/simple/pkg-resources/ HTTP/1.1" 
404 169
2020-09-04 23:17:44,635 WARNI [req2] [Rtx277] serving stale links for 'pkg-resources', url 'https://pypi.mirrors.ustc.
edu.cn/simple/pkg-resources/' responded 404 Not Found
2020-09-04 23:17:44,637 DEBUG [req2] [Rtx277] reading index https://pypi.mirrors.ustc.edu.cn/simple/pkg-resources/
2020-09-04 23:17:44,656 DEBUG https://pypi.mirrors.ustc.edu.cn:443 "GET /simple/pkg-resources/ HTTP/1.1" 302 142
2020-09-04 23:17:44,677 DEBUG https://mirrors.ustc.edu.cn:443 "GET /pypi/web/simple/pkg-resources/ HTTP/1.1" 302 142
2020-09-04 23:17:44,679 DEBUG Starting new HTTPS connection (5): mirrors.tuna.tsinghua.edu.cn:443
2020-09-04 23:17:44,854 DEBUG https://mirrors.tuna.tsinghua.edu.cn:443 "GET /pypi/web/simple/pkg-resources/ HTTP/1.1" 
404 169
2020-09-04 23:17:44,855 WARNI [req2] [Rtx277] serving stale links for 'pkg-resources', url 'https://pypi.mirrors.ustc.
edu.cn/simple/pkg-resources/' responded 404 Not Found
2020-09-04 23:17:44,857 DEBUG [req2] [Rtx277] closing transaction at 277
2020-09-04 23:17:44,857 DEBUG [req2] 200 OK 0.984s serial=277 length=147 type=text/html; charset=UTF-8
2020-09-04 23:17:45,085 INFO  [req3] GET /abc/prod/+simple/pip/
2020-09-04 23:17:45,086 DEBUG [req3] [Rtx277] in-transaction 277
2020-09-04 23:17:45,092 DEBUG [req3] [Rtx277] reading index https://pypi.mirrors.ustc.edu.cn/simple/pip/
2020-09-04 23:17:45,112 DEBUG https://pypi.mirrors.ustc.edu.cn:443 "GET /simple/pip/ HTTP/1.1" 302 142
2020-09-04 23:17:45,134 DEBUG https://mirrors.ustc.edu.cn:443 "GET /pypi/web/simple/pip/ HTTP/1.1" 302 142
2020-09-04 23:17:45,136 DEBUG Starting new HTTPS connection (6): mirrors.tuna.tsinghua.edu.cn:443
2020-09-04 23:17:45,279 DEBUG https://mirrors.tuna.tsinghua.edu.cn:443 "GET /pypi/web/simple/pip/ HTTP/1.1" 200 38839
2020-09-04 23:17:45,280 WARNI [req3] [Rtx277] serving cached links for https://mirrors.tuna.tsinghua.edu.cn/pypi/web/s
imple/pip/ because returned serial -1, cache_serial 7935788 is better!
2020-09-04 23:17:45,282 DEBUG [req3] [Rtx277] reading index https://pypi.mirrors.ustc.edu.cn/simple/pip/
2020-09-04 23:17:45,301 DEBUG https://pypi.mirrors.ustc.edu.cn:443 "GET /simple/pip/ HTTP/1.1" 302 142
2020-09-04 23:17:45,323 DEBUG https://mirrors.ustc.edu.cn:443 "GET /pypi/web/simple/pip/ HTTP/1.1" 302 142
2020-09-04 23:17:45,325 DEBUG Starting new HTTPS connection (7): mirrors.tuna.tsinghua.edu.cn:443
2020-09-04 23:17:45,472 DEBUG https://mirrors.tuna.tsinghua.edu.cn:443 "GET /pypi/web/simple/pip/ HTTP/1.1" 200 38839
2020-09-04 23:17:45,473 WARNI [req3] [Rtx277] serving cached links for https://mirrors.tuna.tsinghua.edu.cn/pypi/web/s
imple/pip/ because returned serial -1, cache_serial 7935788 is better!
2020-09-04 23:17:45,476 DEBUG [req3] [Rtx277] closing transaction at 277
2020-09-04 23:17:45,477 DEBUG [req3] 200 OK 0.391s serial=277 length=33701 type=text/html; charset=UTF-8
2020-09-04 23:17:45,739 INFO  [req4] GET /root/pypi/+f/524/4e51494f5d1df/pip-20.2.2-py2.py3-none-any.whl
2020-09-04 23:17:45,740 DEBUG [req4] [Rtx277] in-transaction 277
2020-09-04 23:17:45,743 DEBUG [req4] [Rtx277] closing transaction at 277
2020-09-04 23:17:45,743 DEBUG [req4] 200 OK 0.003s serial=277 length=1503623 type=None
2020-09-04 23:17:50,164 INFO  [req5] GET /abc/prod/+simple/wheel/
2020-09-04 23:17:50,165 DEBUG [req5] [Rtx277] in-transaction 277
2020-09-04 23:17:50,169 DEBUG [req5] [Rtx277] reading index https://pypi.mirrors.ustc.edu.cn/simple/wheel/
2020-09-04 23:17:50,171 DEBUG Resetting dropped connection: pypi.mirrors.ustc.edu.cn
2020-09-04 23:17:50,314 DEBUG https://pypi.mirrors.ustc.edu.cn:443 "GET /simple/wheel/ HTTP/1.1" 302 142
2020-09-04 23:17:50,316 DEBUG Resetting dropped connection: mirrors.ustc.edu.cn
2020-09-04 23:17:50,408 DEBUG https://mirrors.ustc.edu.cn:443 "GET /pypi/web/simple/wheel/ HTTP/1.1" 302 142
2020-09-04 23:17:50,411 DEBUG Starting new HTTPS connection (8): mirrors.tuna.tsinghua.edu.cn:443
2020-09-04 23:17:50,595 DEBUG https://mirrors.tuna.tsinghua.edu.cn:443 "GET /pypi/web/simple/wheel/ HTTP/1.1" 200 2612
8
2020-09-04 23:17:50,596 WARNI [req5] [Rtx277] serving cached links for https://mirrors.tuna.tsinghua.edu.cn/pypi/web/s
imple/wheel/ because returned serial -1, cache_serial 7962333 is better!
2020-09-04 23:17:50,598 DEBUG [req5] [Rtx277] reading index https://pypi.mirrors.ustc.edu.cn/simple/wheel/
2020-09-04 23:17:50,622 DEBUG https://pypi.mirrors.ustc.edu.cn:443 "GET /simple/wheel/ HTTP/1.1" 302 142
2020-09-04 23:17:50,642 DEBUG https://mirrors.ustc.edu.cn:443 "GET /pypi/web/simple/wheel/ HTTP/1.1" 302 142
2020-09-04 23:17:50,644 DEBUG Starting new HTTPS connection (9): mirrors.tuna.tsinghua.edu.cn:443
2020-09-04 23:17:50,816 DEBUG https://mirrors.tuna.tsinghua.edu.cn:443 "GET /pypi/web/simple/wheel/ HTTP/1.1" 200 2612
8
2020-09-04 23:17:50,817 WARNI [req5] [Rtx277] serving cached links for https://mirrors.tuna.tsinghua.edu.cn/pypi/web/s
imple/wheel/ because returned serial -1, cache_serial 7962333 is better!
2020-09-04 23:17:50,819 DEBUG [req5] [Rtx277] closing transaction at 277
2020-09-04 23:17:50,820 DEBUG [req5] 200 OK 0.656s serial=277 length=22673 type=text/html; charset=UTF-8
2020-09-04 23:17:56,144 INFO  [req6] GET /root/pypi/+f/497/add53525d16c1/wheel-0.35.1-py2.py3-none-any.whl
2020-09-04 23:17:56,145 DEBUG [req6] [Rtx277] in-transaction 277
2020-09-04 23:17:56,146 DEBUG [req6] [Rtx277] closing transaction at 277
2020-09-04 23:17:56,146 DEBUG [req6] 200 OK 0.002s serial=277 length=33174 type=None
```

Pip list from inside my venv (I build it with `mkvirtualenv --system-site-packages -p /usr/bin/python3 pypi`:
```
Package             Version
------------------- ---------
apipkg              1.5
appdirs             1.4.4
argon2-cffi         20.1.0
attrs               19.3.0
beautifulsoup4      4.9.1
bleach              3.1.5
certifi             2020.6.20
cffi                1.14.1
Chameleon           3.8.1
chardet             3.0.4
check-manifest      0.42
cmarkgfm            0.4.2
defusedxml          0.6.0
devpi-client        5.2.0
devpi-common        3.5.0
devpi-server        5.5.0
distlib             0.3.1
docutils            0.16
execnet             1.7.1
filelock            3.0.12
hupper              1.10.2
idna                2.10
importlib-metadata  1.7.0
importlib-resources 3.0.0
itsdangerous        1.1.0
lazy                1.4
packaging           20.4
passlib             1.7.2
PasteDeploy         2.1.0
pep517              0.8.2
pip                 20.2.2
pkginfo             1.5.0.1
plaster             1.0
plaster-pastedeploy 0.7
pluggy              0.13.1
py                  1.9.0
pycparser           2.20
pycurl              7.43.0
Pygments            2.6.1
pygobject           3.22.0
pyparsing           2.4.7
pyramid             1.10.4
pyramid-chameleon   0.3
python-apt          1.4.0b3
python-dateutil     2.8.1
readme-renderer     26.0
repoze.lru          0.7
requests            2.24.0
ruamel.yaml         0.16.10
ruamel.yaml.clib    0.2.0
setuptools          49.3.1
six                 1.15.0
soupsieve           2.0.1
strictyaml          1.0.7
toml                0.10.1
tox                 3.19.0
translationstring   1.4
unattended-upgrades 0.1
urllib3             1.25.10
venusian            3.0.0
virtualenv          20.0.31
waitress            1.4.4
webencodings        0.5.1
WebOb               1.8.6
wheel               0.34.2
Whoosh              2.7.4
zipp                1.2.0
zope.deprecation    4.4.0
zope.interface      5.1.0
```

Python, system and devpi versions:
```
# python -V
Python 3.5.3
# lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (n/a)
Release:        9.9
Codename:       n/a
# devpi-server --version
5.5.0
```

**Comment by hrbonz** [comment]
I've been runnning this devpi for a while, if I could just bust the pypi cache at this point, that would be useful as well. Lots of old packages sitting there that won't be installed anymore...

**Comment by fschulze** [comment]
The URLs are stored in the database and only updated when there are new releases for a package. I recommend removing the mirror index with ``devpi remove`` as the devpi root user and recreating it with the correct mirror URL (don't forget ``type=mirror`` upon creation). This will also remove all locally cached releases for that mirror. If you don't need to cache the files in devpi at all, then use ``mirror_use_external_urls=true`` as well, it will then directly use the URLs of the source for downloads. For an existing mirror this only works for new releases, existing ones will still use the locally cached files.

**Comment by hrbonz** [comment]
Understood, that's what I thought about the db, didn't have time this weekend to go around writing a small python utility to read the sqlite binary field which I suspect is holding this information as JSON(?).

Just want to make sure I got it right in terms of what needs to happen, after reading [the docs](https://devpi.net/docs/devpi/devpi/5.2/+d/userman/devpi_commands.html?highlight=remove#index) I believe you meant `devpi index --delete`:
```
$ devpi login root
[...]
$ devpi index root/pypi
https://pypi.example.com/root/pypi:
  type=mirror
  volatile=False
  mirror_url=https://pypi.mirrors.ustc.edu.cn/simple/
  mirror_web_url_fmt=https://pypi.org/project/{name}/
  title=PyPI
$ devpi index --delete root/pypi
$ devpi index -c root/pypi \
    type=mirror \
    title=PyPI \
    mirror_url="http://mirrors.aliyun.com/pypi/simple/"
```

I'm concerned that it will wipe the base of indexes using `root/pypi`

**Comment by hrbonz** [comment]
That didn't work...
```
$ devpi index --delete root/pypi
About to remove: <URL 'https://pypi.example.com/root/pypi'>
Are you sure (yes/no)? yes
DELETE https://pypi.example.com/root/pypi
403 Forbidden: index root/pypi non-volatile, cannot delete
```

And this seems to enter an infinite 302 redirection loop:
```
$ devpi remove --index root/pypi setuptools
```

**Comment by fschulze** [comment]
You first have to set ``volatile=True`` on ``root/pypi``. The dependencies on the index will remain in place. While the index is removed installs might fail until it is recreated.

I have to look into the 302, that command should work IMO.

**Comment by fschulze** [comment]
You should never access the sqlite db directly, but always go through the storage interface of devpi (context.stage, context.user etc). The db schema is internal.

**Comment by hrbonz** [comment]
Thanks for your help, setting up things with internet challenges is not fun.
I ended up creating a new index as a mirror and using that one as base before you answered.
