### ISSUE TITLE
New local install of devpi-server has PermissionError for devpi-server --version

### ISSUE THREAD

**Issue by chadhutchins182** [devpi/devpi#837]
I installed devpi-server with the simple instructions [listed](https://devpi.net/docs/devpi/devpi/stable/+doc/quickstart-server.html). This is using a local install of python3 and openssl.

When performing the `devpi-server --version` command I'm met with:

```
[devpi@py ~]$ devpi-server --version
Traceback (most recent call last):
  File "/users/devpi/python3/dist/bin/devpi-server", line 5, in <module>
    from devpi_server.main import main
  File "/users/devpi/python3/dist/lib/python3.9/site-packages/devpi_server/main.py", line 17, in <module>
    from .model import BaseStage
  File "/users/devpi/python3/dist/lib/python3.9/site-packages/devpi_server/model.py", line 19, in <module>
    from .auth import hash_password, verify_and_update_password_hash
  File "/users/devpi/python3/dist/lib/python3.9/site-packages/devpi_server/auth.py", line 8, in <module>
    from passlib.context import CryptContext
  File "/users/devpi/python3/dist/lib/python3.9/site-packages/passlib/context.py", line 16, in <module>
    from passlib.registry import get_crypt_handler, _validate_handler_name
  File "/users/devpi/python3/dist/lib/python3.9/site-packages/passlib/registry.py", line 12, in <module>
    from passlib.ifc import PasswordHash
  File "/users/devpi/python3/dist/lib/python3.9/site-packages/passlib/ifc.py", line 10, in <module>
    from passlib.utils.decor import deprecated_method
  File "/users/devpi/python3/dist/lib/python3.9/site-packages/passlib/utils/__init__.py", line 854, in <module>
    from crypt import crypt as _crypt
  File "/users/devpi/python3/dist/lib/python3.9/crypt.py", line 117, in <module>
    _add_method('MD5', '1', 8, 34)
  File "/users/devpi/python3/dist/lib/python3.9/crypt.py", line 94, in _add_method
    result = crypt('', salt)
  File "/users/devpi/python3/dist/lib/python3.9/crypt.py", line 82, in crypt
    return _crypt.crypt(word, salt)
PermissionError: [Errno 1] Operation not permitted
```

[piplist.txt](https://github.com/devpi/devpi/files/6079257/piplist.txt)

```
[devpi@py ~]$ python --version
Python 3.9.2
```
```
[devpi@py ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
```

I've also tried a clean venv to see if that changed anything, and same results.

**Comment by fschulze** [comment]
This is really weird. If you look at [``_add_method``](https://github.com/python/cpython/blob/66f77caca39ba39ebe1e4a95dba6d19b20d51951/Lib/crypt.py#L94) the ``crypt`` call is wrapped in a ``try`` block catching ``OSError`` and ``PermissionError`` is a subclass of ``OSError``. It seems like the ``errno`` is not ``EINVAL`` in your case. This doesn't look like a problem with devpi-server. It seems to be a problem with Python and/or your platform/installation.

**Comment by chadhutchins182** [comment]
Ended up figuring this out. It was FIPS mode enabled on this RHEL VM. Once FIPS mode was turned off the `devpi-server --version` worked correctly.
