### ISSUE TITLE
devpi-init: ModuleNotFoundError: No module named 'ruamel'

### ISSUE THREAD

**Issue by bhrutledge** [devpi/devpi#843]
I first encountered this in a [failed Twine integration test](https://github.com/pypa/twine/runs/2871005944?check_suite_focus=true), running via GitHub Actions on ubuntu-latest. I was able to reproduce it on macOS 11.3.1 with a minimal virtual environment:

```
% python3 -m virtualenv venv && source venv/bin/activate

% python3 --version && pip --version
Python 3.9.5
pip 21.1.2 from /private/tmp/venv-devpi/lib/python3.9/site-packages/pip (python 3.9)

% pip install --no-cache-dir devpi-server

% devpi-init
Traceback (most recent call last):
  File "/private/tmp/venv-devpi/bin/devpi-init", line 5, in <module>
    from devpi_server.init import init
  File "/private/tmp/venv-devpi/lib/python3.9/site-packages/devpi_server/init.py", line 1, in <module>
    from .config import MyArgumentParser
  File "/private/tmp/venv-devpi/lib/python3.9/site-packages/devpi_server/config.py", line 16, in <module>
    from .log import threadlog
  File "/private/tmp/venv-devpi/lib/python3.9/site-packages/devpi_server/log.py", line 1, in <module>
    from ruamel import yaml
ModuleNotFoundError: No module named 'ruamel'

% pip freeze
appdirs==1.4.4
argon2-cffi==20.1.0
attrs==21.2.0
certifi==2021.5.30
cffi==1.14.5
chardet==4.0.0
defusedxml==0.7.1
devpi-common==3.6.0
devpi-server==6.0.0
execnet==1.9.0
hupper==1.10.3
idna==2.10
itsdangerous==2.0.1
lazy==1.4
passlib==1.7.4
PasteDeploy==2.1.1
plaster==1.0
plaster-pastedeploy==0.7
pluggy==0.13.1
py==1.10.0
pycparser==2.20
pyramid==2.0
python-dateutil==2.8.1
repoze.lru==0.7
requests==2.25.1
six==1.16.0
strictyaml==1.4.4
translationstring==1.4
urllib3==1.26.5
venusian==3.0.0
waitress==2.0.0
WebOb==1.8.7
zope.deprecation==4.4.0
zope.interface==5.4.0
```

**Comment by bhrutledge** [comment]
Looks like this was fixed in https://github.com/devpi/devpi/commit/4d80c40fee27120c33a90adb49a1ca1e5ea73518  (currently unreleased).

**Comment by fschulze** [comment]
There is new problem with latest strictyaml. They vendored their ruamel.yaml dependency now, so we need to add in an explicit dependency or use strictyaml in log.py.

**Comment by bhrutledge** [comment]
It looks like there already is an explicit dependency, added after the release of v6.0.0:

https://github.com/devpi/devpi/blob/d46d0a35518b04bc674aa2b9cfa6d6e126248835/server/setup.py#L42

I can confirm that installing from `main` resolves this issue:

```
% pip install -e 'git+https://github.com/devpi/devpi.git#subdirectory=server&egg=devpi-server'

% pip freeze | grep yaml
ruamel.yaml==0.17.9
ruamel.yaml.clib==0.2.2
strictyaml==1.4.4

% devpi-init
INFO  NOCTX Loading node info from /Users/brian/.devpi/server/.nodeinfo
INFO  NOCTX generated uuid: e94e4d123c1643a7930481d2e5653e18
...
```

**Comment by gaborbernat** [comment]
This is breaking my CI for a few days now https://github.com/gaborbernat/devpi-process/runs/2868238687?check_suite_focus=true, can we do a release to fix this?
