### ISSUE TITLE
Devpi replica Warning: Errors during file downloads, 1 files queued for retry

### ISSUE THREAD

**Issue by yukpun** [devpi/devpi#858]
I've deployed devpi master, and devpi-replica on same server (for testing). They both runs in Docker containers
Everything was fine, but replica shows one error about downloading ona package. Because of this I have "fatal" status of replica. I'm attahing logs from replica. Tried to restart container - nothing changed. Tried to run devpi-fsck, result the same.
What could be done to resolve this?

```
2021-10-19 11:57:11,849 WARNI [NOTI] Waiting for file root/pypi/+f/880/a0c22692eaebb/torch-1.2.0-cp27-cp27mu-manylinux1_x86_64.whl in event serial 3639
2021-10-19 11:57:15,647 ERROR [FREP] There repeatedly has been an error during file download.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1383, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.80.0.26', port=3141): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/devpi_server/replica.py", line 530, in process_next_errored
    handler(is_from_mirror, serial, key, keyname, value, back_serial)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/replica.py", line 661, in handler
    conn, serial, typedkey, value, back_serial, self.session)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/replica.py", line 976, in __call__
    timeout=self.xom.config.args.request_timeout)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.80.0.26', port=3141): Read timed out. (read timeout=5)
2021-10-19 11:57:16,852 WARNI [NOTI] Waiting for file root/pypi/+f/880/a0c22692eaebb/torch-1.2.0-cp27-cp27mu-manylinux1_x86_64.whl in event serial 3639
2021-10-19 11:57:21,854 WARNI [NOTI] Waiting for file root/pypi/+f/880/a0c22692eaebb/torch-1.2.0-cp27-cp27mu-manylinux1_x86_64.whl in event serial 3639
2021-10-19 11:57:26,857 WARNI [NOTI] Waiting for file root/pypi/+f/880/a0c22692eaebb/torch-1.2.0-cp27-cp27mu-manylinux1_x86_64.whl in event serial 3639
2021-10-19 11:57:31,861 WARNI [NOTI] Waiting for file root/pypi/+f/880/a0c22692eaebb/torch-1.2.0-cp27-cp27mu-manylinux1_x86_64.whl in event serial 3639
2021-10-19 11:57:36,864 WARNI [NOTI] Waiting for file root/pypi/+f/880/a0c22692eaebb/torch-1.2.0-cp27-cp27mu-manylinux1_x86_64.whl in event serial 3639
2021-10-19 11:57:39,926 INFO  [REP] fetching http://10.80.0.26:3141/+changelog/7974-
```

**Comment by fschulze** [comment]
According to https://pypi.org/project/torch/1.2.0/#files the file has about 750MB. If your server has little RAM, it might be swapping which causes the timeout. You could put nginx in front of devpi-server and let it serve the files directly (see documentation and the ``devpi-gen-config`` script). You could also copy the file manually via rsync, but that won't prevent the problem from occuring again. If you don't need a copy of the pypi files, you can set the ``mirror_use_external_urls`` on ``root/pypi``. You can use ``devpi remove`` to remove individual releases or whole projects afterwards.

**Comment by fschulze** [comment]
This is a docker issue. Your data isn't persisted outside of the docker container. I can't help you with that, sorry.

**Comment by yukpun** [comment]
Data is persisted outside of the docker container. I mount external folder.
Question is only - is it possible to insert this command in startup command for devpi-server? Currently I'm using this command to start devpi server
`/usr/local/bin/devpi-server --host 0.0.0.0 --port 3141 --role master --serverdir /srv --secretfile /srv/.secret`
Or I should run another command `devpi index root/pypi mirror_use_external_urls=true` after devpi-server started each time?
