### ISSUE TITLE
Run devpi-server behind proxy

### ISSUE THREAD

**Issue by rettenbs** [devpi/devpi#864]
With devpi-server version 6.3.0 it is no longer possible to run the devpi-server behind a proxy. Aiohttp ignores the proxy environment variables unless `trust_env` is passed to the client session:
https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support

This was working before 6.3.0 without aiohttp.

**Comment by fschulze** [comment]
Did you test adding ``trust_env`` to https://github.com/devpi/devpi/blob/main/server/devpi_server/main.py#L346?
Since ``requests`` does it by default, I'm fine with adding that there if you can confirm it works.

**Comment by rettenbs** [comment]
As far as I can tell adding the flag solved the issue on our system. Can access packages of mirrors which failed without the flag.

**Comment by fschulze** [comment]
Could you try with the release from https://m.devpi.net/fschulze/dev/devpi-server/6.3.1

**Comment by rettenbs** [comment]
6.3.1 works for us. Thanks.

**Comment by jsivak** [comment]
Leaving this for future searchers:

I upgraded to the 6.4.0 release of devpi-server and was getting the following error:

```
2022-02-13 14:03:45,983 ERROR Exception while serving /+search
Traceback (most recent call last):
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/view.py", line 786, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/waitress/channel.py", line 397, in service
    task.service()
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/views.py", line 166, in __call__
    return self.app(environ, start_response)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/router.py", line 245, in invoke_request
    response = handle_request(request)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/views.py", line 190, in request_log_handler
    response = handler(request)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/views.py", line 226, in request_tx_handler
    response = handler(request)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/viewderivers.py", line 427, in rendered_view
    result = view(context, request)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/viewderivers.py", line 113, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_web/views.py", line 1015, in __call__
    result=self.result)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/pyramid/decorator.py", line 40, in __get__
    val = self.wrapped(inst)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_web/views.py", line 991, in result
    item['sub_hits'] = self.process_sub_hits(
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_web/views.py", line 945, in process_sub_hits
    metadata = self.get_versiondata(stage, data)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_web/views.py", line 909, in get_versiondata
    metadata = stage.get_versiondata(name, version)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/model.py", line 828, in get_versiondata
    for stage, res in self.op_sro_check_mirror_whitelist(
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/model.py", line 1008, in op_sro_check_mirror_whitelist
    res = getattr(stage, opname)(**kw)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/extpypi.py", line 643, in get_versiondata_perstage
    for sm in map(SimplelinkMeta, self.get_simplelinks_perstage(project)):
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/extpypi.py", line 572, in get_simplelinks_perstage
    self.xom.run_coroutine_threadsafe(
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/main.py", line 251, in run_coroutine_threadsafe
    raise exc
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/main.py", line 238, in _with_timeout
    return await asyncio.wait_for(asyncio.shield(coroutine), timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/extpypi.py", line 423, in _async_fetch_releaselinks
    (response, text) = await self.async_httpget(url, allow_redirects=True)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/extpypi.py", line 155, in async_httpget
    return await self.xom.async_httpget(
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/devpi_server/main.py", line 346, in async_httpget
    async with session.get(
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/aiohttp/client.py", line 505, in _request
    proxy, proxy_auth = get_env_proxy_for_url(url)
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/aiohttp/helpers.py", line 315, in get_env_proxy_for_url
    proxies_in_env = proxies_from_env()
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/aiohttp/helpers.py", line 250, in proxies_from_env
    netrc_obj = netrc_from_env()
  File "/srv/apps/devpi_ve/lib/python3.10/site-packages/aiohttp/helpers.py", line 230, in netrc_from_env
    if netrc_env or netrc_path.is_file():
  File "/usr/local/lib/python3.10/pathlib.py", line 1320, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/usr/local/lib/python3.10/pathlib.py", line 1095, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/root/.netrc'
```


My situation is that I'm running devpi-server via supervisord. Supervisord is running as root and the devpi-server app is running as user "supervisord", I had assumed that the "dropping of privileges" that supervisor does when starting devpi-server would behave like a "normal login" of the supervisord user and the sub-process that was running devpi-server would inherit environment settings, but this is not the case. 
In order to fix/address this issue, the environment needs to be specified to the supervisor config script for the devpi-server:

```
[program:devpi]
user=supervisord
directory=/srv/apps/devpi_ve
command=/srv/apps/devpi_ve/bin/devpi-server --host 127.0.0.1 --port 4040 --serverdir server --secretfile /srv/apps/devpi_ve/server/.secret
process_name=%(program_name)s ; process_name expr (default %(program_name)s)
numprocs=1                    ; number of processes copies to start (def 1)
stdout_logfile=/srv/apps/supervisor_ve/supervisor_app/log/devpi.log
redirect_stderr = true
stopsignal = QUIT
# aiohttp needs this setting; it looks for .netrc in the home directory of the user
environment=HOME="/home/supervisord",USER="supervisord"
```

The 'environment' line at the end is the critical part.

Here is a Stackoverflow post describing the problem and solution as well: [https://stackoverflow.com/questions/42234226/supervisord-refuses-to-run-command-as-user-always-runs-as-root](https://stackoverflow.com/questions/42234226/supervisord-refuses-to-run-command-as-user-always-runs-as-root)

Hope this saves some future folks any grief
