### ISSUE TITLE
AttributeError when importing from backup

### ISSUE THREAD

**Issue by agentram** [devpi/devpi#867]
Command:
```bash
devpi-import --serverdir test_restore /opt/devpi_backup/20211217/
```
Error:
```
ERROR [NOTI] calling <bound method EventSubscribers.on_changed_version_config of <devpi_server.model.EventSubscribers object at 0x7fe5ad028e10>> failed, serial=26
Traceback (most recent call last):
  File "/opt/python37/lib/python3.7/site-packages/devpi_server/keyfs.py", line 206, in _execute_hooks
    sub(ev)
  File "/opt/python37/lib/python3.7/site-packages/devpi_server/model.py", line 1687, in on_changed_version_config
    version=version, metadata=metadata)
  File "/opt/python37/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/python37/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/python37/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/opt/python37/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/opt/python37/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/python37/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/opt/python37/lib/python3.7/site-packages/devpi_web/main.py", line 331, in devpiserver_on_changed_versiondata
    index_project(stage, metadata['name'])
  File "/opt/python37/lib/python3.7/site-packages/devpi_web/main.py", line 300, in index_project
    ix = get_indexer(stage.xom)
  File "/opt/python37/lib/python3.7/site-packages/devpi_web/main.py", line 201, in get_indexer
    indexer = get_indexer_from_config(xom.config)
  File "/opt/python37/lib/python3.7/site-packages/devpi_web/main.py", line 181, in get_indexer_from_config
    if isinstance(config.args.indexer_backend, dict):
AttributeError: 'Namespace' object has no attribute 'indexer_backend'
INFO  NOCTX FIN: waiting for event-serial 26
wait_for_events: importing finished; latest_serial = 26
```
Python version:
```
Python 3.7.1
```
Libs version:
```
aiohttp==3.8.1
aiosignal==1.2.0
apipkg==1.5
appdirs==1.4.4
argon2-cffi==20.1.0
async-timeout==4.0.1
asynctest==0.13.0
attrs==21.2.0
beautifulsoup4==4.9.3
bleach==3.3.0
build==0.4.0
certifi==2021.5.30
cffi==1.14.5
Chameleon==3.9.1
chardet==4.0.0
charset-normalizer==2.0.9
check-manifest==0.46
cmarkgfm==0.5.3
defusedxml==0.7.1
devpi-client==5.2.3
devpi-common==3.6.0
devpi-server==6.3.1
devpi-web==4.0.8
distlib==0.3.2
docutils==0.17.1
execnet==1.8.1
filelock==3.0.12
frozenlist==1.2.0
hupper==1.10.3
idna==2.10
importlib-metadata==4.5.0
itsdangerous==2.0.1
lazy==1.4
multidict==5.2.0
packaging==20.9
passlib==1.7.4
PasteDeploy==2.1.1
pep517==0.10.0
pkginfo==1.7.0
plaster==1.0
plaster-pastedeploy==0.7
pluggy==0.13.1
py==1.10.0
pycparser==2.20
Pygments==2.9.0
pyparsing==2.4.7
pyramid==2.0
pyramid-chameleon==0.3
python-dateutil==2.8.1
readme-renderer==29.0
repoze.lru==0.7
requests==2.25.1
ruamel.yaml==0.17.4
ruamel.yaml.clib==0.2.2
six==1.16.0
soupsieve==2.2.1
strictyaml==1.4.2
toml==0.10.2
tox==3.23.1
translationstring==1.4
typing-extensions==3.10.0.0
urllib3==1.26.5
venusian==3.0.0
virtualenv==20.4.7
waitress==2.0.0
webencodings==0.5.1
WebOb==1.8.7
Whoosh==2.7.4
yarl==1.7.2
zipp==3.4.1
zope.deprecation==4.4.0
zope.interface==5.4.0
```

**Comment by fschulze** [comment]
Thanks for reporting. As a workaround use ``--no-events``.
