### ISSUE TITLE
duplicate key value violates unique constraint "changelog_pkey"

### ISSUE THREAD

**Issue by rbracewell** [devpi/devpi#868]
Running a single standalone instance and multiple request nodes against a postgres backend.
Versions currently deployed

- devpi-postgresql-2.0.0
- devpi-server-6.3.0
- devpi-web-4.0.8

I can see the traffic hitting the request-only nodes but I am seeing numerous exceptions being thrown
```
Dec 22 14:34:14 ip-<REDACTED> devpi-server: 2021-12-22 14:34:14,489 - waitress - ERROR - Exception while serving /root/pypi/+f/34f/7a5eca1326aff/gevent-1.1.0.tar.gz
Dec 22 14:34:14 ip-<REDACTED> devpi-server: Traceback (most recent call last):
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/pg8000/legacy.py", line 253, in execute
Dec 22 14:34:14 ip-<REDACTED> devpi-server: statement, vals=vals, oids=self._input_oids, stream=stream
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/pg8000/core.py", line 649, in execute_unnamed
Dec 22 14:34:14 ip-<REDACTED> devpi-server: self.handle_messages(context)
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/pg8000/core.py", line 767, in handle_messages
Dec 22 14:34:14 ip-<REDACTED> devpi-server: raise self.error
Dec 22 14:34:14 ip-<REDACTED> devpi-server: pg8000.exceptions.DatabaseError: {'S': 'ERROR', 'V': 'ERROR', 'C': '23505', 'M': 'duplicate key value violates unique constraint "changelog_pkey"', 'D': 'Key (serial)=(85) already exists.', 's': 'public', 't': 'changelog', 'n': 'changelog_pkey', 'F': 'nbtinsert.c', 'L': '656', 'R': '_bt_check_unique'}
Dec 22 14:34:14 ip-<REDACTED> devpi-server: During handling of the above exception, another exception occurred:
Dec 22 14:34:14 ip-<REDACTED> devpi-server: Traceback (most recent call last):
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/waitress/channel.py", line 397, in service
Dec 22 14:34:14 ip-<REDACTED> devpi-server: task.service()
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/waitress/task.py", line 168, in service
Dec 22 14:34:14 ip-<REDACTED> devpi-server: self.execute()
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/waitress/task.py", line 456, in execute
Dec 22 14:34:14 ip-<REDACTED> devpi-server: for chunk in app_iter:
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/devpi_server/views.py", line 1609, in iter_fetch_remote_file
Dec 22 14:34:14 ip-<REDACTED> devpi-server: for part in iter_cache_remote_file(xom, entry):
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/devpi_server/views.py", line 1518, in iter_cache_remote_file
Dec 22 14:34:14 ip-<REDACTED> devpi-server: set_content()
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
Dec 22 14:34:14 ip-<REDACTED> devpi-server: next(self.gen)
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/devpi_server/keyfs.py", line 399, in transaction
Dec 22 14:34:14 ip-<REDACTED> devpi-server: self.commit_transaction_in_thread()
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/devpi_server/keyfs.py", line 387, in commit_transaction_in_thread
Dec 22 14:34:14 ip-<REDACTED> devpi-server: self._threadlocal.tx.commit()
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/devpi_server/keyfs.py", line 721, in commit
Dec 22 14:34:14 ip-<REDACTED> devpi-server: commit_serial = self.conn.last_changelog_serial + 1
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/devpi_postgresql/main.py", line 313, in __exit__
Dec 22 14:34:14 ip-<REDACTED> devpi-server: self.conn.write_changelog_entry(self.storage.next_serial, entry)
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/devpi_postgresql/main.py", line 78, in write_changelog_entry
Dec 22 14:34:14 ip-<REDACTED> devpi-server: (serial, pg8000.Binary(data)))
Dec 22 14:34:14 ip-<REDACTED> devpi-server: File "/usr/local/lib/python3.7/site-packages/pg8000/legacy.py", line 279, in execute
Dec 22 14:34:14 ip-<REDACTED> devpi-server: raise cls(msg)
Dec 22 14:34:14 ip-<REDACTED> devpi-server: pg8000.dbapi.IntegrityError: {'S': 'ERROR', 'V': 'ERROR', 'C': '23505', 'M': 'duplicate key value violates unique constraint "changelog_pkey"', 'D': 'Key (serial)=(85) already exists.', 's': 'public', 't': 'changelog', 'n': 'changelog_pkey', 'F': 'nbtinsert.c', 'L': '656', 'R': '_bt_check_unique'}
```

**Comment by rbracewell** [comment]
If I revert to a single standalone node and a single request node this error disappears. Additionally, when running multiple request nodes it is not possible to upload packages. An error per above the original post is generated.

Does devpi not support multiple request nodes?

**Comment by fschulze** [comment]
It sounds like you already use the ``--requests-only`` option. There are several sources of possible conflicts if data is requested in parallel which were only discovered after the option was added.

Currently the only guaranteed way to avoid conflicts is using replicas. If you need more than that, I consider that enterprise use and you can contact mail@pyfidelity.com to negotiate a contract to work on that.

**Comment by fschulze** [comment]
This should be improved with devpi-server 6.5.0 and devpi-postgresql 3.0.0.

**Comment by rbracewell** [comment]
Can you expand a little further?

**Comment by fschulze** [comment]
With the new releases writes to the database are done at the very end of a request and the new serial is now also determined at the end. Both these changes greatly reduce the probability of conflicts, but don't remove them completely.

**Comment by fschulze** [comment]
No follow-up for several months. If this is still an issue, feel free to re-open.
