### ISSUE TITLE
devpi-import fails with a stacktrace

### ISSUE THREAD

**Issue by rbracewell** [devpi/devpi#883]
Running the following versions
devpi-postgresql-3.0.0
devpi-server-6.5.0
devpi-web-4.0.8

When running devpi-import it fails with below
Traceback (most recent call last):
  File "/usr/local/bin/devpi-import", line 8, in <module>
    sys.exit(import_())
  File "/usr/local/lib/python3.7/site-packages/devpi_server/importexport.py", line 154, in import_
    do_import(config.args.directory, xom)
  File "/usr/local/lib/python3.7/site-packages/devpi_server/importexport.py", line 111, in do_import
    importer.import_all(path)
  File "/usr/local/lib/python3.7/site-packages/devpi_server/importexport.py", line 521, in import_all
    self.import_filedesc(stage, filedesc, versions)
  File "/usr/local/lib/python3.7/site-packages/devpi_server/importexport.py", line 564, in import_filedesc
    last_modified=mapping["last_modified"])
  File "/usr/local/lib/python3.7/site-packages/devpi_server/model.py", line 1299, in store_releasefile
    last_modified=last_modified)
  File "/usr/local/lib/python3.7/site-packages/devpi_server/model.py", line 1510, in create_linked_entry
    file_entry = self._create_file_entry(basename, content_or_file)
  File "/usr/local/lib/python3.7/site-packages/devpi_server/model.py", line 1566, in _create_file_entry
    dir_hash_spec=ref_hash_spec)
 File "/usr/local/lib/python3.7/site-packages/devpi_server/filestore.py", line 147, in store
    content_or_file, hash_spec=hash_spec)
  File "/usr/local/lib/python3.7/site-packages/devpi_server/filestore.py", line 255, in file_set_content
    self.tx.conn.io_file_set(self._storepath, content_or_file)
  File "/usr/local/lib/python3.7/site-packages/devpi_postgresql/main.py", line 318, in io_file_set
    shutil.copyfileobj(content_or_file, f)
  File "/usr/lib64/python3.7/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "/usr/lib64/python3.7/tempfile.py", line 766, in write
    rv = file.write(s)
OSError: [Errno 28] No space left on device

The dataset being imported is approximately 13GB in size. The postgresql database has 70GB of free space and the host running the devpi-import reports below for the filesystem
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.7G     0  7.7G   0% /dev
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           7.7G  480K  7.7G   1% /run
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/nvme0n1p1  8.0G  3.1G  5.0G  39% /
127.0.0.1:/     8.0E   53G  8.0E   1% /mnt/devpi
tmpfs           1.6G     0  1.6G   0% /run/user/0

I previously ran the same import from devpi-server-6.4.0 with devpi-postgresql-2.0.0 and had no issues. The only thing changed was the upgrade to newer package versions.

I will rerun the import against devpi-server-6.4.0 with devpi-postgresql-2.0.0 to confirm if the import succeeds without issue.

**Comment by fschulze** [comment]
Check which filesystem provides your ``TMP``, it is used to store files before sending them to postgresql. If that is too small, try overriding it with another location for devpi-server.

**Comment by rbracewell** [comment]
Allocating more space resolved the issue
