### ISSUE TITLE
`OSError` when installing dependency (wrapt==1.14.1)

### ISSUE THREAD

**Issue by vandersonmota** [devpi/devpi#901]
# Problem
After setting up a local devpi-server for testing:
```
> devpi-init
> devpi-server
```
Then running: 
`pip install -i http://localhost:3141/root/pypi/+simple/ wrapt==1.14.1`
I get:
```
Looking in indexes: http://localhost:3141/root/pypi/+simple/
Collecting wrapt==1.14.1
ERROR: Could not install packages due to an OSError: HTTPConnectionPool(host='localhost', port=3141): Max retries exceeded with url: /root/pypi/%2Bf/40e/7bc81c9e2b273/wrapt-1.14.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (Caused by ResponseError('too many 500 error responses'))
```

After inspecting devpi-server logs, this is the traceback:
```
Traceback (most recent call last):
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/view.py", line 786, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/devpi_server/middleware.py", line 21, in __call__
    return self.app(environ, start_response)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/router.py", line 245, in invoke_request
    response = handle_request(request)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/devpi_server/views.py", line 168, in request_log_handler
    response = handler(request)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/devpi_server/views.py", line 204, in request_tx_handler
    response = handler(request)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/config/views.py", line 151, in __call__
    return view(context, request)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/viewderivers.py", line 392, in viewresult_to_response
    result = view(context, request)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/pyramid/viewderivers.py", line 113, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/devpi_server/views.py", line 1303, in stage_pkgserv
    return self._pkgserv(entry, entry.url)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/devpi_server/views.py", line 1262, in _pkgserv
    headers = next(app_iter)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/devpi_server/views.py", line 1641, in iter_fetch_remote_file
    yield from iter_cache_remote_file(xom, entry, url)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/devpi_server/views.py", line 1476, in iter_cache_remote_file
    f = entry.tx.conn.io_file_new_open(entry._storepath)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/devpi_server/keyfs_sqlite_fs.py", line 103, in io_file_new_open
    f = get_write_file_ensure_dir(DirtyFile(path).tmppath)
  File "/home/vandersonmota/.pyenv/versions/3.9.9/lib/python3.9/site-packages/devpi_server/fileutil.py", line 301, in get_write_file_ensure_dir
    return open(path, "w+b")
OSError: [Errno 36] File name too long: '/home/vandersonmota/.devpi/server/+files/root/pypi/+f/40e/7bc81c9e2b273/wrapt-1.14.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl-6a3732542513ba3a3529168b8e283d6f68fd2d5e0cf9424b06bb456736604f1f-tmp'
```

I get the following error when inspecing
## Runtime info
```
→ devpi-server --version
6.5.1
```
Python 3.9.9
Linux Mint 20.2 Cinnamon Kernel 5.13.0-51-generic
pip version: 22.1.2

Thanks for your project.

**Comment by fschulze** [comment]
That is weird. As far as I know the Linux filename limit is 255 characters and the full path limit 4096. Here the filename has 177 characters. It is not trivial to fix this in ``devpi-server``.

Can you check the output of ``getconf -a | grep -i name_max``? See https://www.linuxshelltips.com/find-limit-file-name-length-linux/

**Comment by gst** [comment]
hmm, the full path is 249 bytes long..

```bash
$ python -c "print(len('/home/vandersonmota/.devpi/server/+files/root/pypi/+f/40e/7bc81c9e2b273/wrapt-1.14.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl-6a3732542513ba3a3529168b8e283d6f68fd2d5e0cf9424b06bb456736604f1f-tmp'))"
249
```

@vandersonmota 

what gives `getconf -a | grep -i _max` (we'll get all such "max" sizes)  ?

**Comment by vandersonmota** [comment]
```
LINK_MAX                           65000
_POSIX_LINK_MAX                    65000
_POSIX_MAX_CANON                   255
_POSIX_MAX_INPUT                   255
NAME_MAX                           255
_POSIX_NAME_MAX                    255
PATH_MAX                           4096
_POSIX_PATH_MAX                    4096
SOCK_MAXBUF                        
ARG_MAX                            2097152
ATEXIT_MAX                         2147483647
CHAR_MAX                           127
CHILD_MAX                          124822
INT_MAX                            2147483647
IOV_MAX                            1024
LOGNAME_MAX                        256
MB_LEN_MAX                         16
NGROUPS_MAX                        65536
OPEN_MAX                           1024
PASS_MAX                           8192
PTHREAD_KEYS_MAX                   1024
PTHREAD_THREADS_MAX                
SCHAR_MAX                          127
SHRT_MAX                           32767
SSIZE_MAX                          32767
TTY_NAME_MAX                       32
TZNAME_MAX                         
UCHAR_MAX                          255
UINT_MAX                           4294967295
UIO_MAXIOV                         1024
ULONG_MAX                          18446744073709551615
USHRT_MAX                          65535
_POSIX_ARG_MAX                     2097152
_POSIX_CHILD_MAX                   124822
_POSIX_NGROUPS_MAX                 65536
_POSIX_OPEN_MAX                    1024
_POSIX_SSIZE_MAX                   32767
_POSIX_STREAM_MAX                  16
TIMER_MAX                          
_POSIX_TZNAME_MAX                  
_T_IOV_MAX                         
BC_BASE_MAX                        99
BC_DIM_MAX                         2048
BC_SCALE_MAX                       99
BC_STRING_MAX                      1000
CHARCLASS_NAME_MAX                 2048
COLL_WEIGHTS_MAX                   255
EQUIV_CLASS_MAX                    
EXPR_NEST_MAX                      32
LINE_MAX                           2048
POSIX2_BC_BASE_MAX                 99
POSIX2_BC_DIM_MAX                  2048
POSIX2_BC_SCALE_MAX                99
POSIX2_BC_STRING_MAX               1000
POSIX2_COLL_WEIGHTS_MAX            255
POSIX2_EXPR_NEST_MAX               32
_POSIX2_LINE_MAX                   2048
POSIX2_LINE_MAX                    2048
POSIX2_RE_DUP_MAX                  32767
RE_DUP_MAX                         32767
SYMLOOP_MAX                        
STREAM_MAX                         16
AIO_LISTIO_MAX                     
AIO_MAX                            
AIO_PRIO_DELTA_MAX                 20
DELAYTIMER_MAX                     2147483647
HOST_NAME_MAX                      64
LOGIN_NAME_MAX                     256
MQ_OPEN_MAX                        
MQ_PRIO_MAX                        32768
RTSIG_MAX                          32
SEM_NSEMS_MAX                      
SEM_VALUE_MAX                      2147483647
SIGQUEUE_MAX                       124822
POSIX_REC_MAX_XFER_SIZE            
SYMLINK_MAX                        
```

**Comment by gst** [comment]
strange. have basically all the same _max than you but 2 unrelated.

what is your filesystem on your /home actually ?

**Comment by vandersonmota** [comment]
```→ df -Th /home
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/nvme0n1p5 ext4  661G  168G  460G  27% /
``` 

It is ext4

**Comment by gst** [comment]
to be sure:

```
getconf NAME_MAX /home/vandersonmota/.devpi
```

?

**Comment by gst** [comment]
yep:

```bash
09:01 $ python -c "print(len('wrapt-1.14.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl-6a3732542513ba3a3529168b8e283d6f68fd2d5e0cf9424b06bb456736604f1f-tmp'))"
177
```

**Comment by magowiz** [comment]
I found that is related to the fact the partition used is an encrypted one: https://askubuntu.com/questions/728465/how-can-i-increase-ubuntus-143-byte-file-name-limit-for-encrypted-directories

I "solved" (mainly worked around) the issue, moving the data folder outside my home directory that is crypted.

**Comment by fschulze** [comment]
There are problems with long paths during testing on Windows as well. I will look into a solution for that for the next major version which will rework the storage backend and require an export/import, as this can't be solved in a backward compatible way.
