### ISSUE TITLE
hello ,  I created an api integration and this error appears when I send the request

### ISSUE THREAD

**Issue by ibs-tac** [devpi/devpi#917]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/odoo/addons/web/controllers/main.py", line 1396, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/addons/web/controllers/main.py", line 1384, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/base_einvoice/models/account_move.py", line 139, in action_submit
    res = requests.post(url, data=payload, headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by fschulze** [comment]
With just the traceback I have no idea what you are doing and what the problem could be. Judging from ``base_einvoice`` this looks like some form of commercial integration, if that is the case, please contact mail@pyfidelity.com with a description of what you want to accomplish for a quote on paid support.

**Comment by fschulze** [comment]
No follow-up for several months. If this is still an issue, feel free to re-open.
