### ISSUE TITLE
[test] workdir cleanup fails: PermissionError: Access is denied

### ISSUE THREAD

**Issue by henryborchers** [devpi/devpi#919]
devpi-client 6.0.1

Same issue as #913 but with "devpi test"

`c:\Jenkins\workspace\jects_uiucprescon.getalmarc2_dev@8> devpi test --index dev_staging uiucprescon.getmarc2==0.1.2.dev0 -s tar.gz  -e py39 -v `
...
```
write json report at: C:\Users\ContainerAdministrator\AppData\Local\Temp\devpi-test-x2tn_6p0\targz\toxreport.json
posting tox result data to https://devpi.library.illinois.edu/DS_Jenkins/dev_staging/+f/be7/1ba941aa80dd6/uiucprescon.getmarc2-0.1.2.dev0.tar.gz
successfully posted tox result data
Traceback (most recent call last):
  File "C:\Python310\lib\shutil.py", line 619, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\devpi-test-x2tn_6p0\\targz\\uiucprescon.getmarc2-0.1.2.dev0\\.tox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\devpi.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\devpi\main.py", line 41, in main
    return method(hub, hub.args)
  File "C:\Python310\lib\site-packages\devpi\test.py", line 237, in main
    with hub.workdir(prefix="devpi-test-") as tmpdir:
  File "C:\Python310\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\Python310\lib\site-packages\devpi\main.py", line 244, in workdir
    rmtree(workdir.strpath, onerror=remove_readonly)
  File "C:\Python310\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python310\lib\shutil.py", line 621, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python310\lib\site-packages\devpi\main.py", line 235, in remove_readonly
    func(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\devpi-test-x2tn_6p0\\targz\\uiucprescon.getmarc2-0.1.2.dev0\\.tox'
```

**Comment by fschulze** [comment]
This seems to be different. The code is already in place, see:
```
  File "C:\Python310\lib\site-packages\devpi\main.py", line 244, in workdir
    rmtree(workdir.strpath, onerror=remove_readonly)
```

It is more likely that the tests leave a process running as the error message indicates. Maybe the shutdown of that process just takes too long before the workdir removal is attempted.

**Comment by henryborchers** [comment]
hmm.... I think you're right that it might be different. 

I'm getting this error on all of my projects on Windows (Linux and MacOs doesn't seem to have an issue) when running on devpi client when upgraded to 6.0. Downgrading to version 5 of the client fixes this issue.

**Comment by fschulze** [comment]
That is a good hint. In 6.x tox is called as a process, not used as a Python module. Maybe that subprocess is still lingering. I have to look into that.

**Comment by henryborchers** [comment]
It wouldn't be the first time that I've had subprocess issues with file permissions that only are a problem with Windows.
