### ISSUE TITLE
ConnectionResetError(104, 'Connection reset by peer')) during uploading torch

### ISSUE THREAD

**Issue by whikwon** [devpi/devpi#921]
Thank you for sharing a good project.

I found that the ConnectionResetError occurs when uploading a specific torch version.  
Until now, problem occurs only in the package downloaded from url, not from the pip server.

Environment:
- devpi-server 6.6.1
- Ubuntu 18.04
- Python 3.8.13

Output: 
```
~ » devpi upload torch-1.10.0+cu111-cp37-cp37m-linux_x86_64.whl                                                                                                                                                                    mpadmin@mpadmin
Traceback (most recent call last):
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/http/client.py", line 1050, in _send_output
    self.send(chunk)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/http/client.py", line 972, in send
    self.sock.sendall(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/http/client.py", line 1050, in _send_output
    self.send(chunk)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/http/client.py", line 972, in send
    self.sock.sendall(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mpadmin/anaconda3/envs/devpi/bin/devpi", line 8, in <module>
    sys.exit(main())
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/devpi/main.py", line 41, in main
    return method(hub, hub.args)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/devpi/upload.py", line 27, in main
    return main_fromfiles(hub, args)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/devpi/upload.py", line 80, in main_fromfiles
    uploader.do_upload_paths(paths)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/devpi/upload.py", line 112, in do_upload_paths
    self.upload_release_file(archivepath, pkginfo)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/devpi/upload.py", line 183, in upload_release_file
    self.post("file_upload", path, meta=meta)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/devpi/upload.py", line 159, in post
    r = hub.http.post(self.pypisubmit, dic, files=files,
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/mpadmin/anaconda3/envs/devpi/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

Reproduce:
```
wget https://download.pytorch.org/whl/cu111/torch-1.10.0%2Bcu111-cp37-cp37m-linux_x86_64.whl
devpi upload torch-1.10.0%2Bcu111-cp37-cp37m-linux_x86_64.whl
```

**Comment by fschulze** [comment]
I get ``Request Entity Too Large`` error instead when testing locally. The file in question is just shy of 2GB. The default maximum request body size in ``waitress`` which is the WSGI server devpi-server uses is 1GB. All releases at https://pypi.org/project/torch/1.10.0/#files are smaller than 1GB. You can use the ``--max-request-body-size`` of devpi-server to change the limit. If you have a proxy like nginx in front of devpi-server, it has to be adjusted as well. It is also possible that something else in between your machine and devpi-server causes the disconnect for some reason, either due to the file size or because of a timeout.

**Comment by whikwon** [comment]
@fschulze Thanks for the response. Actually, I found the `--max-request-body-size` option in devpi-server. Issue resolved.
