### ISSUE TITLE
devpi install no results in offline mode

### ISSUE THREAD

**Issue by minusf** [devpi/devpi#925]
```
devpi-client        6.0.2
devpi-common        3.7.0
devpi-server        6.7.0

macos 12.6 python 3.9.14
```

In certain cases, (and i havent been able to determine the trigger) `devpi install` and/or `pip` with `PIP_INDEX_URL` keeps failing in offline mode:

```
project % devpi use
Warning: insecure http host, trusted-host will be set for pip
current devpi index: http://127.0.0.1:3141/user/local (logged in as user)
supported features: server-keyvalue-parsing
venv for install/set commands: /project/venv
only setting venv pip cfg, no global configuration changed
/project/venv/pip.conf: no config file exists
always-set-cfg: no

project % devpi install django --venv ./venv
-->  project$ venv/bin/pip --version
-->  project$ venv/bin/pip install -U django  [PIP_INDEX_URL=URL('http://user:****@127.0.0.1:3141/user/local/+simple/'),PIP_PRE='1',PIP_USE_WHEEL='1']
Looking in indexes: http://user:****@127.0.0.1:3141/user/local/+simple/, http://127.0.0.1:3141/user/local
ERROR: Could not find a version that satisfies the requirement django (from versions: none)
ERROR: No matching distribution found for django
command failed

project % venv/pip install django
% vpip install django
Looking in indexes: http://127.0.0.1:3141/user/local, http://127.0.0.1:3141/user/local
ERROR: Could not find a version that satisfies the requirement django (from versions: none)
ERROR: No matching distribution found for django
```

(there are multiple django versions in the devpi)

Log from devpi-server running in non-deamon mode:

```
2022-10-03 23:30:03,794 INFO  [req100] GET /user/local/django/
2022-10-03 23:30:03,810 ERROR Exception while serving /userd/local/django/
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/opt/homebrew/lib/python3.9/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/opt/homebrew/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 861, in getaddrinfo
    return await self.run_in_executor(
  File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/waitress/channel.py", line 397, in service
    task.service()
  File "/opt/homebrew/lib/python3.9/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/opt/homebrew/lib/python3.9/site-packages/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/middleware.py", line 21, in __call__
    return self.app(environ, start_response)
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/router.py", line 245, in invoke_request
    response = handle_request(request)
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/views.py", line 190, in request_log_handler
    response = handler(request)
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/views.py", line 226, in request_tx_handler                            [11/7883]
    response = handler(request)
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/viewderivers.py", line 392, in viewresult_to_response
    result = view(context, request)
  File "/opt/homebrew/lib/python3.9/site-packages/pyramid/viewderivers.py", line 113, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/views.py", line 1247, in installer_simple_project
    return self.simple_list_project()
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/views.py", line 574, in simple_list_project
    stage.get_simplelinks(
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/model.py", line 895, in get_simplelinks
    for stage, res in self.op_sro_check_mirror_whitelist(
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/model.py", line 1065, in op_sro_check_mirror_whitelist
    res = getattr(stage, opname)(**kw)
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/mirror.py", line 686, in get_simplelinks_perstage
    self.xom.run_coroutine_threadsafe(
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/main.py", line 261, in run_coroutine_threadsafe
    raise exc
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/main.py", line 248, in _with_timeout
    return await asyncio.wait_for(asyncio.shield(coroutine), timeout)
  File "/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/mirror.py", line 499, in _async_fetch_releaselinks
    (response, text) = await self.async_httpget(
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/mirror.py", line 210, in async_httpget
    return await self.xom.async_httpget(
  File "/opt/homebrew/lib/python3.9/site-packages/devpi_server/main.py", line 376, in async_httpget
    async with session.get(
  File "/opt/homebrew/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/opt/homebrew/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/opt/homebrew/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/homebrew/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host pypi.org:443 ssl:default [nodename nor servname provided, or not known]
```

**Comment by minusf** [comment]
it seems that this was simply an issue of some of the files not being available locally. i will close this now, but there is an actual issue that shows up here and there where devpi does not return results even when the files are available.  i will try to report it when it happens again.

**Comment by fschulze** [comment]
I think the problem is, that ``aiohttp.client_exceptions.ClientConnectorError`` isn't caught when accessing ``pypi.org`` and because of that no links are returned instead of serving stale links from the local db. I will look into it.

**Comment by fschulze** [comment]
No follow-up for several months. If this is still an issue, feel free to re-open.

**Comment by minusf** [comment]
thank you for looking into it.  i will keep an eye on it.  unfortunately devpi is something i just install and forget about as it has no brew package and i dont pick up on updates...

but now i'll move my private venvs from python 3.9 to 3.11 so it's a good opportunity to update devpi.
