### ISSUE TITLE
500 error when listing versions while disconnected from upstream

### ISSUE THREAD

**Issue by offbyone** [devpi/devpi#944]
I noticed an exception from devpi earlier today when I was disconnected from the network. I attempted to run `devpi list hatchling` to see which versions of hatching I _could_ install, and got 500 errors from the server. Those were coming from `mirror.py` in `get_simplelinks_perstage(project)`:

```
2023-01-05 09:03:36,002 INFO  [req1] GET /root/pypi/hatchling
2023-01-05 09:03:36,023 ERROR Exception while serving /root/pypi/hatchling
Traceback (most recent call last):
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/middleware.py", line 21, in __call__
    return self.app(environ, start_response)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/router.py", line 245, in invoke_request
    response = handle_request(request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/views.py", line 190, in request_log_handler
    response = handler(request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/views.py", line 226, in request_tx_handler
    response = handler(request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_web/views.py", line 108, in request_trailing_slash_redirect_handler
    return handler(request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/config/views.py", line 151, in __call__
    return view(context, request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/viewderivers.py", line 392, in viewresult_to_response
    result = view(context, request)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/pyramid/viewderivers.py", line 113, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/views.py", line 1258, in project_get
    versions = context.list_versions(perstage=perstage)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/view_auth.py", line 127, in list_versions
    res = self.stage.list_versions(project)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/model.py", line 814, in list_versions
    for stage, res in self.op_sro_check_mirror_whitelist(
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/model.py", line 1065, in op_sro_check_mirror_whitelist
    res = getattr(stage, opname)(**kw)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/mirror.py", line 746, in list_versions_perstage
    return set(x.version for x in self.get_simplelinks_perstage(project))
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/mirror.py", line 686, in get_simplelinks_perstage
    self.xom.run_coroutine_threadsafe(
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/main.py", line 261, in run_coroutine_threadsafe
    raise exc
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/main.py", line 248, in _with_timeout
    return await asyncio.wait_for(asyncio.shield(coroutine), timeout)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/mirror.py", line 499, in _async_fetch_releaselinks
    (response, text) = await self.async_httpget(
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/mirror.py", line 210, in async_httpget
    return await self.xom.async_httpget(
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/devpi_server/main.py", line 376, in async_httpget
    async with session.get(
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/offby1/.local/pipx/venvs/devpi-server/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host pypi.org:443 ssl:default [nodename nor servname provided, or not known]
```

```
# macOS Ventura, Python 3.10 for devpi-server

> pip list
Package                       Version
----------------------------- ------------------------------
alabaster                     0.7.12
attrs                         22.1.0
Babel                         2.10.3
beautifulsoup4                4.11.1
black                         22.6.0
bleach                        5.0.1
build                         0.8.0
certifi                       2022.6.15
charset-normalizer            2.1.1
click                         8.1.3
click-default-group           1.2.2
commonmark                    0.9.1
distlib                       0.3.6
doc2dash                      2.4.1
docutils                      0.19
filelock                      3.8.0
flake8                        5.0.4
idna                          3.3
imagesize                     1.4.1
importlib-metadata            4.12.0
incremental                   21.3.0
iniconfig                     1.1.1
Jinja2                        3.1.2
keyring                       23.8.2
MarkupSafe                    2.1.1
mccabe                        0.7.0
mypy                          0.971
mypy-extensions               0.4.3
packaging                     21.3
pathspec                      0.9.0
pep517                        0.13.0
pip                           22.2.2
pip-tools                     6.8.0
pkginfo                       1.8.3
platformdirs                  2.5.2
pluggy                        1.0.0
py                            1.11.0
pycodestyle                   2.9.1
pyflakes                      2.5.0
Pygments                      2.13.0
PyHamcrest                    2.0.5.dev16+g40e15f9.d20230105
pyparsing                     3.0.9
pytest                        7.1.2
pytest-mypy                   0.9.1
pytz                          2022.2.1
readme-renderer               37.0
requests                      2.28.1
requests-toolbelt             0.9.1
rfc3986                       2.0.0
rich                          12.5.1
setuptools                    58.1.0
six                           1.16.0
snowballstemmer               2.2.0
soupsieve                     2.3.2.post1
Sphinx                        5.1.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
toml                          0.10.2
tomli                         2.0.1
towncrier                     21.9.0
tox                           3.25.1
tox-asdf                      0.1.0
twine                         4.0.1
typing_extensions             4.3.0
urllib3                       1.26.12
virtualenv                    20.16.3
webencodings                  0.5.1
wheel                         0.37.1
zipp                          3.8.1
```

**Comment by fschulze** [comment]
You didn't include the devpi-server version used, but it looks like it isn't 6.8.0 which should fix this case but will most likely cause the same error you got in #945.

**Comment by offbyone** [comment]
Yeah, sorry, I forgot to include that part:

```
> ~/.local/bin/devpi-server --version
6.7.0
```

That is the version that started me on this path.

**Comment by fschulze** [comment]
Forgot to mention, that there are further fixes in 6.9.0.

**Comment by fschulze** [comment]
No follow-up for several months. If this is still an issue, feel free to re-open.
