### ISSUE TITLE
TypeError when listing versions while offline

### ISSUE THREAD

**Issue by offbyone** [devpi/devpi#945]
While attempting to make a reproduction case for #944 while running devpi-server from source, I encountered a different, but presumably related error in the same part of the code. I ran `devpi list numpy` while running `devpi-server --debug --port 3141 --serverdir /Users/offby1/Library/Caches/net.devpi` from my clone of the devpi git repo, and got this on the server side: `TypeError: cannot unpack non-iterable FatalResponse object`

That is coming from here:

```
Traceback (most recent call last):
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/view.py", line 786, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/waitress/task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/Users/offby1/projects/devpi/server/devpi_server/middleware.py", line 21, in __call__
    return self.app(environ, start_response)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/router.py", line 245, in invoke_request
    response = handle_request(request)
  File "/Users/offby1/projects/devpi/server/devpi_server/views.py", line 189, in request_log_handler
    response = handler(request)
  File "/Users/offby1/projects/devpi/server/devpi_server/views.py", line 225, in request_tx_handler
    response = handler(request)
  File "/Users/offby1/projects/devpi/web/devpi_web/views.py", line 114, in request_trailing_slash_redirect_handler
    return handler(request)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/util.py", line 733, in reraise
    raise value
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/router.py", line 143, in handle_request
    response = _call_view(
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/config/views.py", line 151, in __call__
    return view(context, request)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/config/views.py", line 170, in attr_view
    return view(context, request)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/config/views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/viewderivers.py", line 392, in viewresult_to_response
    result = view(context, request)
  File "/Users/offby1/projects/devpi/.direnv/python-3.10.7/lib/python3.10/site-packages/pyramid/viewderivers.py", line 113, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/Users/offby1/projects/devpi/server/devpi_server/views.py", line 1263, in project_get
    versions = context.list_versions(perstage=perstage)
  File "/Users/offby1/projects/devpi/server/devpi_server/view_auth.py", line 130, in list_versions
    res = self.stage.list_versions(project)
  File "/Users/offby1/projects/devpi/server/devpi_server/model.py", line 830, in list_versions
    for stage, res in self.op_sro_check_mirror_whitelist(
  File "/Users/offby1/projects/devpi/server/devpi_server/model.py", line 1081, in op_sro_check_mirror_whitelist
    res = getattr(stage, opname)(**kw)
  File "/Users/offby1/projects/devpi/server/devpi_server/mirror.py", line 768, in list_versions_perstage
    return set(x.version for x in self.get_simplelinks_perstage(project))
  File "/Users/offby1/projects/devpi/server/devpi_server/mirror.py", line 707, in get_simplelinks_perstage
    self.xom.run_coroutine_threadsafe(
  File "/Users/offby1/projects/devpi/server/devpi_server/main.py", line 264, in run_coroutine_threadsafe
    raise exc
  File "/Users/offby1/projects/devpi/server/devpi_server/main.py", line 251, in _with_timeout
    return await asyncio.wait_for(asyncio.shield(coroutine), timeout)
  File "/Users/offby1/.asdf/installs/python/3.10.7/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/Users/offby1/projects/devpi/server/devpi_server/mirror.py", line 520, in _async_fetch_releaselinks
    (response, text) = await self.async_httpget(
TypeError: cannot unpack non-iterable FatalResponse object
```

I'm not sure how much of my cache you'd need in order to reproduce it, although I could guess that an empty cache might work?

**Comment by fschulze** [comment]
Looks like my fix for 6.8.0 wasn't complete. I wonder why this wasn't caught by the tests. I will look into it.

**Comment by offbyone** [comment]
Which fix? I'm happy to at least have a look at the code in question.

**Comment by fschulze** [comment]
https://github.com/devpi/devpi/commit/1e709220ac17783ae6b134c3075b0ba0f99e320e

**Comment by fschulze** [comment]
The FatalResponse class needs to be adapted for the use in async_httpget
