### ISSUE TITLE
Errors on "latest/+doc" access

### ISSUE THREAD

**Issue by jrast** [devpi/devpi#953]
I'm currently running into issues with serving documentation under the "latest" enpoint. The behavior is quite strange: Every second request fails, meaning once I get the error and if I reload the page in the browser the documentation is served as expected.

- Operating System (of the devpi-server): Windows Server 2016
- Python Version 3.10.5
- Packages:
  - devpi-client         6.0.2
  - devpi-common         3.7.1
  - devpi-server         6.8.0 
  - devpi-web            4.2.0
  - Complete Package List see below

Exception in the Logfile:

```
2023-02-14 15:31:14,612 INFO  [req95] GET /hamilton/stable/hampro/latest/+doc/usage/index.html
2023-02-14 15:31:14,643 ERROR Exception while serving /hamilton/stable/hampro/latest/+doc/usage/index.html
Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\pyramid\tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "D:\Python310\lib\site-packages\pyramid\view.py", line 786, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\waitress\channel.py", line 428, in service
    task.service()
  File "D:\Python310\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "D:\Python310\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "D:\Python310\lib\site-packages\devpi_server\middleware.py", line 21, in __call__
    return self.app(environ, start_response)
  File "D:\Python310\lib\site-packages\pyramid\router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "D:\Python310\lib\site-packages\pyramid\router.py", line 276, in default_execution_policy
    return router.invoke_request(request)
  File "D:\Python310\lib\site-packages\pyramid\router.py", line 245, in invoke_request
    response = handle_request(request)
  File "D:\Python310\lib\site-packages\devpi_server\views.py", line 189, in request_log_handler
    response = handler(request)
  File "D:\Python310\lib\site-packages\devpi_server\views.py", line 225, in request_tx_handler
    response = handler(request)
  File "D:\Python310\lib\site-packages\devpi_web\views.py", line 112, in request_trailing_slash_redirect_handler
    return handler(request)
  File "D:\Python310\lib\site-packages\pyramid\tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "D:\Python310\lib\site-packages\pyramid\tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "D:\Python310\lib\site-packages\pyramid\util.py", line 733, in reraise
    raise value
  File "D:\Python310\lib\site-packages\pyramid\tweens.py", line 41, in excview_tween
    response = handler(request)
  File "D:\Python310\lib\site-packages\pyramid\router.py", line 143, in handle_request
    response = _call_view(
  File "D:\Python310\lib\site-packages\pyramid\view.py", line 674, in _call_view
    response = view_callable(context, request)
  File "D:\Python310\lib\site-packages\pyramid\config\views.py", line 170, in attr_view
    return view(context, request)
  File "D:\Python310\lib\site-packages\pyramid\config\views.py", line 196, in predicate_wrapper
    return view(context, request)
  File "D:\Python310\lib\site-packages\pyramid\viewderivers.py", line 392, in viewresult_to_response
    result = view(context, request)
  File "D:\Python310\lib\site-packages\devpi_web\views.py", line 178, in doc_serve
    doc_info = get_doc_info(context, request, check_content=False)
  File "D:\Python310\lib\site-packages\devpi_web\views.py", line 127, in get_doc_info
    versions = context.versions
AttributeError: 'RootFactory' object has no attribute 'versions'
2023-02-14 15:31:15,081 INFO  [req96] GET /hamilton/stable/hampro/latest/+doc/usage/index.html
```

Installed Packages
```
Package              Version
-------------------- -----------
aiohttp              3.8.1
aiosignal            1.2.0
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
async-timeout        4.0.2
attrs                21.4.0
beautifulsoup4       4.11.1
bleach               5.0.0
build                0.10.0
certifi              2022.5.18.1
cffi                 1.15.0
Chameleon            3.10.1
charset-normalizer   2.0.12
check-manifest       0.49
cmarkgfm             0.8.0
colorama             0.4.6
defusedxml           0.7.1
devpi-client         6.0.2
devpi-common         3.7.1
devpi-server         6.8.0
devpi-web            4.2.0
docutils             0.18.1
frozenlist           1.3.0
hupper               1.10.3
idna                 3.3
itsdangerous         2.1.2
lazy                 1.4
multidict            6.0.2
packaging            21.3
passlib              1.7.4
PasteDeploy          2.1.1
pep517               0.13.0
pip                  23.0
pkginfo              1.9.6
plaster              1.0
plaster-pastedeploy  0.7
platformdirs         2.5.2
pluggy               1.0.0
py                   1.11.0
pycparser            2.21
Pygments             2.12.0
pyparsing            3.0.9
pyproject_hooks      1.0.0
pyramid              2.0
pyramid-chameleon    0.3
python-dateutil      2.8.2
readme-renderer      35.0
repoze.lru           0.7
requests             2.28.0
ruamel.yaml          0.17.21
ruamel.yaml.clib     0.2.6
setuptools           58.1.0
six                  1.16.0
soupsieve            2.3.2.post1
strictyaml           1.6.1
tomli                2.0.1
translationstring    1.4
urllib3              1.26.9
venusian             3.0.0
waitress             2.1.2
webencodings         0.5.1
WebOb                1.8.7
Whoosh               2.7.4
yarl                 1.7.2
zope.deprecation     4.4.0
zope.interface       5.4.0
````

**Comment by fschulze** [comment]
The problem is, that ``ContextWrapper`` is applied after ``get_doc_info`` is called. The fix is simple, but I need to add some tests, which is a bit of work.
