### ISSUE TITLE
devpi use does not store basic auth anymore (devpi-client 6.x regression)

### ISSUE THREAD

**Issue by vytas7** [devpi/devpi#965]
Hello!
I saw that Basic authentication was unfortunately deprecated, but it judging by the code it should still work, right?

Our problem is that `devpi use` does not seem to store Basic authentication credentials anymore. Moreover, it errors out with `401 Unauthorized` at the end although most of the steps seem to work.

Our workflow basically starts with
```
devpi use https://username:password@devpi.example.com/some/index
```

This works as expected with `devpi-client` 5.x.

However, `devpi-client` 6.x errors out on `hub.validate_index_access()` in `use.py`::`main(...)`. By the time this method is invoked, it seems that no credentials are stored. The first `http_api` call seems to use the auth correctly.

No credentials are stored in `~/.devpi/client/current.json` either. They are stored with `devpi-client` 6.x.

**Comment by fschulze** [comment]
Which versions did you try? devpi-client 6.0.4 has some changes which either broke this or fixed it compared to previous 6.x versions.

I strongly recommend looking into [devpi-lockdown](https://pypi.org/project/devpi-lockdown/) and [devpi-tokens](https://pypi.org/project/devpi-tokens/) instead of using basic auth.

**Comment by fschulze** [comment]
Since 6.x credentials are stored in ``~/.devpi/client/auth.json``.

**Comment by vytas7** [comment]
I tried debugging Git main a bit, and 6.0.4 from PyPi.
I'll try earlier 6.0.x and report. IIRC most of the things actually work, it is that validation of index that doesn't inherit credentials and fails.

**Comment by vytas7** [comment]
Hi again, I tried 6.0.0, 6.0.1, 6.0.2, and 6.0.3, all exhibit the same problem as 6.0.4 / `main`.
5.2.3 works as expected.

Devpi-lockdown might work for us, but it looked a bit suboptimal when we checked it last. Currently, we use Devpi internally without any basic auth or lockdown (but still have users to upload of course), and we have another location in Nginx with TLS cert and basic auth, and IP lock to a list of addresses used by our CI provider. We upload packages to the CI index from external CI (BitBucket Pipelines... :grimacing:).

**Comment by vytas7** [comment]
So, to summarize, what is happening (on `main` with a couple of cosmetic debug lines and changing `http_api()` to raise):

```
devpi use https://username:password@devpi.example.com/ci/ci
```

```
<...>
http_api(method='get', url=URL('https://devpi.example.com/ci/ci/+api'), auth is set: True
<...>
http_api(method='get', url=URL('https://devpi.screen9.com/ci/ci?no_projects='), auth is set: False
Traceback (most recent call last):
  File "/home/vytas/.virtualenvs/devpi/bin/devpi", line 8, in <module>
    sys.exit(main())
  File "/home/vytas/progs/devpi/client/devpi/main.py", line 46, in main
    return method(hub, hub.args)
  File "/home/vytas/progs/devpi/client/devpi/use.py", line 541, in main
    hub.validate_index_access()
  File "/home/vytas/progs/devpi/client/devpi/main.py", line 331, in validate_index_access
    reply = self.http_api(
  File "/home/vytas/progs/devpi/client/devpi/main.py", line 208, in http_api
    raise RuntimeError(f'{r.status_code=} {r.reason=}')
RuntimeError: r.status_code=401 r.reason='Unauthorized'
```

debugging changes:
```diff
--- a/client/devpi/main.py
+++ b/client/devpi/main.py
@@ -150,6 +150,7 @@ class Hub:
         If type is specified and the json result type does not match,
         bail out fatally (unless fatal = False)
         """
+        print(f'http_api({method=}, {url=}, auth is set: {auth is not notset}')
         assert kvdict is None or isinstance(kvdict, (dict, list))
         if isinstance(url, URL):
             url = url.url
@@ -204,6 +205,7 @@ class Hub:
             return reply
         # feedback reply info to user, possibly bailing out
         if r.status_code >= 400:
+            raise RuntimeError(f'{r.status_code=} {r.reason=}')
             if fatal:
                 out = self.fatal
             elif quiet:

```

**Comment by fschulze** [comment]
You should add another debug output before https://github.com/devpi/devpi/blob/d4ab0f5e12bb50fa1177436d2ee39fa5e4d79c9a/client/devpi/main.py#L170-L171, as the call for checking the index access intentionally has no auth set and should do the lookup on https://github.com/devpi/devpi/blob/d4ab0f5e12bb50fa1177436d2ee39fa5e4d79c9a/client/devpi/main.py#L166-L167

For your use-case you would use ``devpi-tokens`` for your CI provider. You can even limit the token permissions to only allow uploads of specific packages. You could get rid of the certificate and basic auth and use ``devpi-lockdown`` only for the nginx facing your CI. You would keep the IP limiting setup there. Whether ``devpi-lockdown`` is in use is solely determined by the nginx config. So for your internal access you would use an nginx config which doesn't enable ``devpi-lockdown``.

**Comment by vytas7** [comment]
Hi again,
`devpi-lockdown` + `devpi-tokens` sounds promising, but there is very little documentation, and/or probably we are still misunderstanding some concepts. With basic auth as it is now, we configure `pip` to use `https://username:password@devpi.example.com/some/index/+simple/` via `pip.conf` or otherwise to install packages, run `tox`, etc. How does one configure `pip` to authenticate with `devpi-lockdown` or to pass the appropriate token and how?

**Comment by fschulze** [comment]
I should add examples to the readme of devpi-tokens.

1. ``devpi token-create -o citoken -a pkg_read,toxresult_upload,upload`` with optionally ``-i`` and ``-p`` to further limit to an index and/or a project. This creates a token for the current user that is limited to upload and install. With only ``pkg_read`` the token is read-only and only allows installs.
2. then use ``https://:token@devpi.example.com/some/index`` where ``token`` is the content of the created ``citoken`` file. The leading ``:`` makes sure the token is treated as a password in pip output (if the empty user name before the colon doesn't work for some reason, use ``__token__`` or the original user name used to create the token). It is best to set the ``PIP_INDEX_URL`` environment variable instead of the ``-i/--index-url`` option, as pip will hide the password in output and it is much less likely to show up in log output.

With ``token-derive`` you can take an existing token and limit it further. This is used automatically when ``token-login`` is in use to create a one time token for each release when using ``devpi upload``. It could also be useful to create a new token with a shorter expiration (about the time the CI run takes plus some margin) at the start of the CI run, which is then used for pip etc. If it unintentionally shows up in log output, it is less useful, as it will most likely already be expired.

**Comment by vytas7** [comment]
Thanks, that helps, we'll look into that!
In the short term we could keep pinning `devpi-client` to 5, but of course it would be nice to resolve the bug as well.

It seems that maybe there's a misunderstanding in the port `:443` creeping in somehow resulting in a different key in the url-lookup?
I've now added more debug:
```
The password is stored unencrypted!
http_api(method='get', url=URL('https://devpi.example.com/ci/ci/+api'), auth is set: True
Use of basic authentication is deprecated, take a look at devpi-lockdown instead. If that doesn't work for you, let us know by filing an issue with details of your usecase.
_get_basic_auth_dict(): self._basic_auth={'https://devpi.example.com:443/': ['pipelines', '***']}
<...>
supported features: server-keyvalue-parsing
http_api(method='get', url=URL('https://devpi.example.com/ci/ci?no_projects='), auth is set: False
_get_basic_auth_dict(): self._basic_auth={'https://devpi.example.com:443/': ('pipelines', '***)}
current.get_basic_auth(url='https://devpi.example.com/ci/ci?no_projects=') ==> None
<...>
RuntimeError: r.status_code=401 r.reason='Unauthorized'
```

**Comment by fschulze** [comment]
@vytas7 since you are using basic auth, you must have a proxy in front of devpi-server. If that is nginx, compare your config with the current example created with a current version of the ``devpi-gen-config`` script. There have been some fixes related to ``$scheme`` which might have an effect. Also see [#840](https://github.com/devpi/devpi/issues/840#issuecomment-1236690464) But I have a feeling this is not the cause of your issues with devpi-client 6.x.

**Comment by henryborchers** [comment]
@fschulze the thing that I don't understand is why is this only happening when running devpi test with python 3.11 only

**Comment by henryborchers** [comment]
I don't think my issue is the same. so I created a new ticket #978

**Comment by fschulze** [comment]
@henryborchers there recently were some urllib/urlparse changes/security fixes which I think could cause that and were introduced first in 3.11 and only just a few days ago backported to older Python versions, so this might show up with those as well soon.

**Comment by fschulze** [comment]
By now I'm pretty sure this is a quoting problem. Could you all try to use ``urllib.parse.quote`` on your password and try the result instead of your real password? I suspect that there are characters in your password which cause this.

For the basic auth, my guess is that the passing of the URL to pip via the environment variable doesn't quote the password correctly.

For Python 3.11, the changes in urlsplit most likely trip over the unquoted password.

**Comment by vytas7** [comment]
@fschulze thanks, I'll check the Nginx config. 3.11 is unrelated to our problems since we're mostly on 3.8.

**Comment by fschulze** [comment]
Could you try:

https://m.devpi.net/fschulze/dev/devpi-client/6.0.5.dev0
https://m.devpi.net/fschulze/dev/+f/8e0/51c0ad3c869d5/devpi_client-6.0.5.dev0-py2.py3-none-any.whl

**Comment by vytas7** [comment]
Hi again @fschulze, I have tried the above package but it didn't help either.
I have however given it now an hour or so in PDB and I believe I understand what is going on :cold_sweat: 
I'll open a PR.
