### ISSUE TITLE
I found that using devpi cannot upgrade the pip version to 23.1.2

### ISSUE THREAD

**Issue by zhenzi0322** [devpi/devpi#972]
What is this problem, or do I need to set additional parameters for devpi

**Comment by fschulze** [comment]
Can you provide more details, do you get an error message?

**Comment by zhenzi0322** [comment]
> Can you provide more details, do you get an error message?

```
pip install pip==23.1.2 -i https://pypi.long920.cn/root/pypi/+simple
```

**Comment by zhenzi0322** [comment]
I don't know why there is no version with pip=23.1.2

**Comment by fschulze** [comment]
Can you open https://pypi.long920.cn/root/pypi/+simple/pip in a browser in click the ``refresh`` button? Also check the ``devpi-server`` logs when you do that and report the output here. Are you aware that https://pypi.long920.cn/root/pypi/+simple/pip is public?

**Comment by zhenzi0322** [comment]
log
```
devpi_server.model.UpstreamError: serial mismatch on GET URL('https://pypi.tuna.tsinghua.edu.cn/simple/pip/'), cache_serial 16906393 is newer than returned serial -1
2023-05-26 01:10:00,071 INFO  [req275] GET /root/pypi/+simple/pip/
2023-05-26 01:10:00,648 WARNI [req275] [Rtx1477] serving stale links, because of exception Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/devpi_server/mirror.py", line 707, in get_simplelinks_perstage
    self.xom.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.9/site-packages/devpi_server/main.py", line 264, in run_coroutine_threadsafe
    raise exc
  File "/usr/local/lib/python3.9/site-packages/devpi_server/main.py", line 251, in _with_timeout
    return await asyncio.wait_for(asyncio.shield(coroutine), timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/devpi_server/mirror.py", line 552, in _async_fetch_releaselinks
    raise self.UpstreamError(
devpi_server.model.UpstreamError: serial mismatch on GET URL('https://pypi.tuna.tsinghua.edu.cn/simple/pip/'), cache_serial 16906393 is newer than returned serial -1
````

**Comment by fschulze** [comment]
Did you change the ``mirror_url``? If data was already fetched and the ``mirror_url`` is changed to a different server that does not have the same internal serial numbers as ``pypi.org`` does, then you get this error. Also see the issue I just created: https://github.com/devpi/devpi/issues/973

**Comment by zhenzi0322** [comment]
OK. Processed
