### ISSUE TITLE
AttributeError: type object 'PersistentCurrent' has no attribute 'auth'

### ISSUE THREAD

**Issue by domdfcoding** [devpi/devpi#992]
I have installed `devpi-client` on my local machine to upload packages to a devpi server on a server on the same network. However, when I tell `devpi-client` the server address it raises an exception:

```console
$ devpi use http://192.168.1.218:3141/root/staging
Warning: insecure http host, trusted-host will be set for pip
Traceback (most recent call last):
  File "/home/domdf/server_config/devpi/venv/bin/devpi", line 8, in <module>
    sys.exit(main())
  File "/home/domdf/server_config/devpi/venv/lib/python3.8/site-packages/devpi/main.py", line 46, in main
    return method(hub, hub.args)
  File "/home/domdf/server_config/devpi/venv/lib/python3.8/site-packages/devpi/use.py", line 503, in main
    current.configure_fromurl(hub, url, client_cert=args.client_cert)
  File "/home/domdf/server_config/devpi/venv/lib/python3.8/site-packages/devpi/use.py", line 319, in configure_fromurl
    self._configure_from_server_api(r.result, url)
  File "/home/domdf/server_config/devpi/venv/lib/python3.8/site-packages/devpi/use.py", line 351, in _configure_from_server_api
    self.reconfigure(data)
  File "/home/domdf/server_config/devpi/venv/lib/python3.8/site-packages/devpi/use.py", line 451, in reconfigure
    prop = getattr(self.__class__, key)
AttributeError: type object 'PersistentCurrent' has no attribute 'auth'
```

If I downgrade to `devpi-client` 5.3.2 it works fine:

```console
Warning: insecure http host, trusted-host will be set for pip
current devpi index: http://192.168.1.218:3141/root/staging (not logged in)
supported features: server-keyvalue-parsing
venv for install/set commands: /home/domdf/server_config/devpi/venv
only setting venv pip cfg, no global configuration changed
/home/domdf/server_config/devpi/venv/pip.conf: no config file exists
always-set-cfg: no
```

And after that I can log in fine with `devpi login`

## Versions

* Python 3.8 (server is Python 3.9)
* Ubuntu 20.04 (server is docker atop Ubuntu 22.04)
* The server has `devpi-server` 6.3.1

## `pip list` output

```
Package            Version
------------------ ---------
build              0.10.0
certifi            2023.7.22
charset-normalizer 3.2.0
check-manifest     0.49
devpi-client       6.0.5
devpi-common       3.7.2
distlib            0.3.7
filelock           3.12.2
idna               3.4
iniconfig          2.0.0
lazy               1.5
packaging          21.3
pep517             0.13.0
pip                23.2.1
pkginfo            1.9.6
platformdirs       3.10.0
pluggy             1.2.0
py                 1.11.0
pyparsing          3.1.1
pyproject_hooks    1.0.0
requests           2.31.0
setuptools         68.0.0
six                1.16.0
tomli              2.0.1
tox                3.28.0
urllib3            2.0.4
virtualenv         20.24.3
wheel              0.41.2
```

**Comment by fschulze** [comment]
Did you have ``devpi-client`` installed before? Maybe an even older version at some point in the past?

Could you try upgrading to 6.x and try again after it worked with 5.2.3?

If that still fails, downgrade to 5.2.3 once more, ``devpi logout`` and then upgrade to 6.x and try yet again.

**Comment by domdfcoding** [comment]
Tried both but no joy. After some more digging I did find a file at `~/.devpi/client/current/json`  with the following content (I've redacted what looks like a token):

```
{
  "auth": {
    "http://192.168.0.44:3141/": [
      "root",
      "[\"root\", []].<redacted>"
    ]
  },
  "features": [
    "server-keyvalue-parsing"
  ],
  "index": "http://192.168.1.218:3141/root/staging",
  "login": "http://192.168.1.218:3141/+login",
  "pypisubmit": "http://192.168.1.218:3141/root/staging/",
  "simpleindex": "http://192.168.1.218:3141/root/staging/+simple/"
}
```

218 is the new server and 44 is the old server. I did have an older version of `devpi-client` installed before on the local machine but in a different venv.

After deleting the `current.json` file I can log in fine with the latest `devpi-client` version.

**Comment by fschulze** [comment]
Using devpi-client 6.0.0 - 6.0.3 once for login should also fix it. The bug was introduced with 6.0.4.
